Repository kyma-project/cloud-manager, pull requests merged in 2023-11, with the labels that each got.

#10 Peering aggregation reconciliation
  apis/cloud-resources/v1beta1/awsvpcpeering_types.go
  apis/cloud-resources/v1beta1/azurevpcpeering_types.go
  apis/cloud-resources/v1beta1/cloudresources_types.go
  apis/cloud-resources/v1beta1/gcpvpcpeering_types.go
  apis/cloud-resources/v1beta1/nfsvolume_types.go
  apis/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_cloudresources.yaml
  controllers/cloud-resources/awsvpcpeering_controller.go
  controllers/cloud-resources/azurevpcpeering_controller.go
  controllers/cloud-resources/cloudresources_controller.go
  controllers/cloud-resources/gcpvpcpeering_controller.go
  go.mod
  go.sum
  main.go
  pkg/common/aggregation/aggregable.go
  pkg/common/aggregation/aggregate.go
  pkg/common/aggregation/aggregateAwsPeering.go
  pkg/common/aggregation/aggregateAzurePeering.go
  pkg/common/aggregation/aggregateGcpPeering.go
  pkg/common/aggregation/aggregateNfsVolume.go
  pkg/common/aggregation/loadCloudResources.go
  pkg/common/aggregation/loadObj.go
  pkg/common/aggregation/saveCloudResources.go
  pkg/common/aggregation/state.go
  pkg/common/composedAction/action.go
  pkg/common/composedAction/action_test.go
  pkg/common/composedAction/predicate.go
  pkg/common/composedAction/predicate_test.go
  pkg/common/composedAction/state.go
  pkg/peering/reconcile/reconciler.go
Labels: size/XXL, lgtm

#13 Migrate to kubebuilder go v4
  Makefile
  PROJECT
  api/cloud-resources/v1beta1/awsvpcpeering_types.go
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  api/cloud-resources/v1beta1/cloudresources_types.go
  api/cloud-resources/v1beta1/gcpvpcpeering_types.go
  api/cloud-resources/v1beta1/groupversion_info.go
  api/cloud-resources/v1beta1/nfsvolume_types.go
  api/cloud-resources/v1beta1/outcome.go
  api/cloud-resources/v1beta1/types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_cloudresources.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_nfsvolumes.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/cloud-resources/awsvpcpeering_controller.go
  internal/controller/cloud-resources/azurevpcpeering_controller.go
  internal/controller/cloud-resources/cloudresources_controller.go
  internal/controller/cloud-resources/gcpvpcpeering_controller.go
  internal/controller/cloud-resources/nfsvolume_controller.go
  internal/controller/cloud-resources/suite_test.go
  pkg/cloudresources/reconcile/handleServed.go
  pkg/cloudresources/reconcile/reconciler.go
  pkg/common/genericActions/aggregable.go
  pkg/common/genericActions/aggregate.go
  pkg/common/genericActions/aggregateAwsPeering.go
  pkg/common/genericActions/aggregateAzurePeering.go
  pkg/common/genericActions/aggregateGcpPeering.go
  pkg/common/genericActions/aggregateNfsVolume.go
  pkg/common/genericActions/loadCloudResources.go
  pkg/common/genericActions/saveCloudResources.go
  pkg/common/genericActions/state.go
  pkg/common/genericActions/types.go
  pkg/peering/reconcile/whenBeingDeleted.go
  pkg/peering/reconcile/whenNoFinalizer.go
  pkg/peering/reconcile/whenOutcomeCreated.go
  pkg/peering/reconcile/whenOutcomeError.go
Labels: size/XXL, lgtm, cla: yes

#12 (NfsVolume) flow and state diagram
  pkg/nfs/reconcile/README.md
  pkg/nfs/reconcile/assets/flow-excalidraw.svg
  pkg/nfs/reconcile/assets/state-drawio.svg
Labels: size/M, lgtm, cla: yes
