Repository kyma-project/cloud-manager, pull requests merged in 2024-03, with the labels that each got.

#123 Gcp IpRange Reconciler unit tests
  pkg/kcp/provider/gcp/client/provider.go
  pkg/kcp/provider/gcp/iprange/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
  pkg/kcp/provider/gcp/iprange/compareStates_test.go
  pkg/kcp/provider/gcp/iprange/loadAddress_test.go
  pkg/kcp/provider/gcp/iprange/loadPsaConnection_test.go
  pkg/kcp/provider/gcp/iprange/state_test.go
  pkg/kcp/provider/gcp/iprange/syncAddress_test.go
  pkg/kcp/provider/gcp/iprange/syncPsaConnection_test.go
  pkg/kcp/provider/gcp/iprange/updateState_test.go
Labels: size/XXL, lgtm, cla: yes

#124 Update main.go
  cmd/main.go
Labels: size/XS, lgtm, cla: yes

#125 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#126 scope fix upon deployment - in Kyma CR module first appears in the st…
  config/rbac/role.yaml
  internal/controller/cloud-control/scope_aws_test.go
  internal/controller/cloud-control/scope_controller.go
  pkg/kcp/scope/findKymaModuleState.go
  pkg/testinfra/dsl/kyma.go
  pkg/testinfra/gherkin.go
Labels: size/M, lgtm, cla: yes

#127 fix kymas finalizers rbac
  config/rbac/role.yaml
  internal/controller/cloud-control/scope_controller.go
Labels: size/XS, lgtm, cla: yes

#128 Updated rbac to include update for Kyma objects
  config/rbac/role.yaml
  internal/controller/cloud-control/scope_controller.go
Labels: size/XS, lgtm, cla: yes

#129 Debug
  config/rbac/role.yaml
  internal/controller/cloud-control/scope_controller.go
  pkg/skr/runtime/looper/runner.go
Labels: size/XS, lgtm, cla: yes

#130 fix docker files chown
  Dockerfile
Labels: size/XS, lgtm, cla: yes

#132 change provider files location and permissions
  Dockerfile
Labels: size/XS, lgtm, cla: yes

#133 change provider files permissions
  Dockerfile
Labels: size/XS, lgtm, cla: yes

#134 use api reader to get secrets
  pkg/composed/state.go
  pkg/kcp/provider/gcp/iprange/state_test.go
  pkg/kcp/provider/gcp/nfsinstance/state_test.go
  pkg/kcp/scope/createGardenerClient.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/state_test.go
  pkg/testinfra/run.go
Labels: size/M, lgtm, cla: yes

#135 gcp structured logging
  cmd/main.go
  go.mod
  pkg/util/gcpLogLevelEncoder.go
Labels: size/M, lgtm, cla: yes

#136 fixed AwsNfsVolume deprovisioning
  internal/controller/cloud-resources/awsnfsvolume_test.go
  pkg/composed/markedForDeletionPredicate.go
  pkg/skr/awsnfsvolume/deleteNfsVol.go
  pkg/skr/awsnfsvolume/loadKcpNfsInstance.go
  pkg/skr/awsnfsvolume/reconciler.go
  pkg/skr/awsnfsvolume/removeFinalizer.go
  pkg/skr/awsnfsvolume/requeueWaitKcpStatus.go
  pkg/skr/awsnfsvolume/stopIfNotBeingDeleted.go
  pkg/skr/awsnfsvolume/updateId.go
  pkg/skr/awsnfsvolume/updateStatus.go
  pkg/skr/awsnfsvolume/waitIpRangeReady.go
  pkg/skr/awsnfsvolume/waitKcpNfsInstanceDeleted.go
  pkg/skr/awsnfsvolume/waitPvDeleted.go
  pkg/testinfra/dsl/commonAssertions.go
  pkg/testinfra/dsl/objActions.go
Labels: size/L, lgtm, cla: yes

#137 Updting Status Condition when Connecting to GCP fails
  pkg/kcp/provider/gcp/client/provider.go
  pkg/kcp/provider/gcp/iprange/client/computeClient.go
  pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
  pkg/kcp/provider/gcp/iprange/new.go
  pkg/kcp/provider/gcp/nfsinstance/client/filestoreClient.go
  pkg/kcp/provider/gcp/nfsinstance/new.go
  pkg/skr/iprange/updateStatus.go
Labels: size/M, lgtm, cla: yes

#138 ipRange and gcpNfsVolume to show Ready/Error status on kubectl get
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  api/cloud-resources/v1beta1/iprange_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
  config/manager/kustomization.yaml
Labels: size/M, lgtm, cla: yes

#139 cli kyma create
  cmd/cli/cmdKymaCreate.go
Labels: size/M, lgtm, cla: yes

#140 awsnfsvolume to show Ready/Error status on kubectl get
  api/cloud-resources/v1beta1/awsnfsvolume_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
Labels: size/S, lgtm, cla: yes

#142 syncing providers
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
Labels: size/M, lgtm, cla: yes

#141 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#144 feat(AWS NfsInstance): deprovisioning
  internal/controller/cloud-control/iprange_aws_test.go
  internal/controller/cloud-control/nfsinstance_aws_test.go
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-resources/awsnfsvolume_test.go
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/kcp/provider/aws/iprange/createSubnets.go
  pkg/kcp/provider/aws/iprange/findCloudResourceSubnets.go
  pkg/kcp/provider/aws/iprange/loadVpc.go
  pkg/kcp/provider/aws/iprange/util.go
  pkg/kcp/provider/aws/mock/nfsStore.go
  pkg/kcp/provider/aws/mock/vpcStore.go
  pkg/kcp/provider/aws/nfsinstance/client/client.go
  pkg/kcp/provider/aws/nfsinstance/deleteEfs.go
  pkg/kcp/provider/aws/nfsinstance/deleteMountTargets.go
  pkg/kcp/provider/aws/nfsinstance/deleteSecurityGroup.go
  pkg/kcp/provider/aws/nfsinstance/loadEfs.go
  pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go
  pkg/kcp/provider/aws/nfsinstance/new.go
  pkg/kcp/provider/aws/nfsinstance/removeFinalizer.go
  pkg/kcp/provider/aws/nfsinstance/removeReadyCondition.go
  pkg/kcp/provider/aws/nfsinstance/updateStatus.go
  pkg/kcp/provider/aws/nfsinstance/validateIpRangeSubnets.go
  pkg/kcp/provider/aws/nfsinstance/waitEfsDeleted.go
  pkg/kcp/provider/aws/nfsinstance/waitMountTargetsDeleted.go
  pkg/kcp/provider/aws/util/ec2tags.go
  pkg/testinfra/dsl/awsIpRange.go
  pkg/testinfra/dsl/awsNfsVolume.go
  pkg/testinfra/dsl/conditions.go
  pkg/testinfra/dsl/nfsInstance.go
Labels: size/XL, lgtm, cla: yes

#145 Update cli readme
  cmd/cli/README.md
  tools/dev/README.md
Labels: size/M, lgtm, cla: yes

#143 Checks if config/dist/skr/crd/bases/providers are up to date.
  .github/workflows/pr-checks.yml
Labels: size/XS, lgtm, cla: yes

#147 chore: aws nfs deprovisioning fix
  pkg/kcp/provider/aws/nfsinstance/deleteEfs.go
  pkg/kcp/provider/aws/nfsinstance/loadEfs.go
  pkg/kcp/provider/aws/nfsinstance/waitEfsDeleted.go
  tools/demo/awsnfsvolume/iprange.yaml
Labels: size/S, lgtm, cla: yes

#148 aws nfs deprovisioning fix
  pkg/kcp/provider/aws/nfsinstance/deleteEfs.go
Labels: size/XS, lgtm, cla: yes

#150 chore: AWS NfsVolume remove owner reference and change name to status.id
  internal/controller/cloud-resources/awsnfsvolume_test.go
  pkg/skr/awsnfsvolume/createVolume.go
  pkg/skr/awsnfsvolume/loadVolume.go
Labels: size/S, lgtm, cla: yes

#149 fix: rc-tag is missing from security scans config
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#152 feat: AWS IpRange deprovisioning
  internal/controller/cloud-control/iprange_aws_test.go
  internal/controller/cloud-control/nfsinstance_aws_test.go
  internal/controller/cloud-control/scope_aws_test.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/kcp/provider/aws/iprange/client/client.go
  pkg/kcp/provider/aws/iprange/deleteSubnets.go
  pkg/kcp/provider/aws/iprange/disassociateVpcAddressSpace.go
  pkg/kcp/provider/aws/iprange/loadVpc.go
  pkg/kcp/provider/aws/iprange/new.go
  pkg/kcp/provider/aws/iprange/removeFinalizer.go
  pkg/kcp/provider/aws/iprange/removeReadyCondition.go
  pkg/kcp/provider/aws/iprange/waitCidrBlockDisassociated.go
  pkg/kcp/provider/aws/iprange/waitSubnetsDeleted.go
  pkg/kcp/provider/aws/mock/vpcStore.go
  pkg/kcp/scope/findKymaModuleState.go
  pkg/skr/iprange/deleteKcpIpRange.go
  pkg/testinfra/gherkin.go
  pkg/util/delayActIgnore.go
Labels: size/XL, lgtm, cla: yes

#154 chore: module deprovisioning fixes
  pkg/kcp/scope/reconciler.go
  pkg/kcp/scope/stopIfReadyAndActive.go
  pkg/skr/runtime/looper/skrLooper.go
Labels: size/M, lgtm, cla: yes

#155 chore: module deprovisioning fix
  pkg/kcp/scope/stopIfReady.go
Labels: size/S, lgtm, cla: yes

#156 chore: module deprovisioning fix
  pkg/kcp/scope/findKymaModuleState.go
  pkg/skr/cloudresources/handleServed.go
Labels: size/S, lgtm, cla: yes

#157 chore: module deprovisioning fix
  internal/controller/cloud-control/scope_aws_test.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/scope/addKymaFinalizer.go
  pkg/kcp/scope/findKymaModuleState.go
  pkg/kcp/scope/predicates.go
  pkg/kcp/scope/reconciler.go
  pkg/kcp/scope/removeKymaFinalizer.go
  pkg/kcp/scope/skrActivate.go
  pkg/kcp/scope/state.go
  pkg/kcp/scope/stopIfReadyAndActive.go
  pkg/skr/runtime/alias.go
  pkg/skr/runtime/looper/checker.go
  pkg/skr/runtime/looper/skrLooper.go
  pkg/testinfra/env.go
  pkg/testinfra/run.go
  pkg/testinfra/types.go
Labels: size/L, lgtm, cla: yes

#158 chore: improve debugging log messages
  pkg/common/actions/focal/loadScopeFromRef.go
  pkg/composed/updateStatus.go
  pkg/kcp/provider/aws/iprange/loadVpc.go
  pkg/kcp/provider/aws/iprange/new.go
  pkg/kcp/provider/aws/iprange/state.go
  pkg/kcp/provider/gcp/iprange/loadAddress_test.go
  pkg/kcp/provider/gcp/iprange/loadPsaConnection_test.go
  pkg/kcp/provider/gcp/iprange/syncAddress_test.go
  pkg/kcp/provider/gcp/iprange/syncPsaConnection_test.go
  pkg/kcp/provider/gcp/iprange/updateState_test.go
  pkg/kcp/provider/gcp/iprange/validateCidr_test.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState_test.go
  pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance_test.go
  pkg/kcp/provider/gcp/nfsinstance/validatePostCreate_test.go
  pkg/skr/gcpnfsvolume/deletePersistenceVolume_test.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance_test.go
  pkg/skr/gcpnfsvolume/updateStatus_test.go
  pkg/skr/gcpnfsvolume/validateSpec_test.go
Labels: size/L, lgtm, cla: yes

#159 chore: fixing scope remove kyma finalizer
  pkg/kcp/scope/removeKymaFinalizer.go
  pkg/util/gcpLogLevelEncoder.go
Labels: size/XS, lgtm, cla: yes

#160 fix: aws cached client
  pkg/kcp/provider/aws/client/provider.go
  pkg/kcp/provider/aws/iprange/client/client.go
  pkg/kcp/provider/aws/nfsinstance/client/client.go
  pkg/kcp/scope/client/awsStsClient.go
Labels: size/M, lgtm, cla: yes

#163 Update sec-scanners-config.yaml v20240327-3713616a
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#161 fix: Error messages during Gcp reconcile
  pkg/kcp/provider/gcp/iprange/checkGcpOperation.go
  pkg/skr/iprange/updateStatus.go
Labels: size/S, lgtm, cla: yes

#164 fix: ctx must be supplied to LogErrorAndReturn()
  pkg/common/actions/removeFinalizer.go
  pkg/composed/logger.go
  pkg/kcp/nfsinstance/loadIpRange.go
  pkg/kcp/provider/aws/iprange/checkCidrBlockStatus.go
  pkg/kcp/provider/aws/iprange/checkCidrOverlap.go
  pkg/kcp/provider/aws/iprange/ensureShootZonesAndRangeSubnetsMatch.go
  pkg/kcp/provider/aws/iprange/extendVpcAddressSpace.go
  pkg/kcp/provider/aws/iprange/loadSubnets.go
  pkg/kcp/provider/aws/iprange/splitRangeByZones.go
  pkg/kcp/provider/aws/iprange/updateSuccessStatus.go
  pkg/kcp/provider/aws/nfsinstance/createEfs.go
  pkg/kcp/provider/aws/nfsinstance/createMountTargets.go
  pkg/kcp/provider/aws/nfsinstance/createSecurityGroup.go
  pkg/kcp/provider/aws/nfsinstance/findSecurityGroup.go
  pkg/kcp/provider/aws/nfsinstance/loadEfs.go
  pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go
  pkg/kcp/provider/aws/nfsinstance/loadSecurityGroup.go
  pkg/kcp/provider/aws/nfsinstance/validateExistingMountTargets.go
  pkg/skr/awsnfsvolume/addFinalizer.go
  pkg/skr/cloudresources/addFinalizer.go
  pkg/skr/gcpnfsvolume/addFinalizer.go
  pkg/skr/gcpnfsvolume/createPersistenceVolume.go
  pkg/skr/gcpnfsvolume/deleteKcpNfsInstance.go
  pkg/skr/gcpnfsvolume/deletePersistenceVolume.go
  pkg/skr/gcpnfsvolume/loadKcpIpRange.go
  pkg/skr/gcpnfsvolume/loadKcpNfsInstance.go
  pkg/skr/gcpnfsvolume/loadPersistenceVolume.go
  pkg/skr/gcpnfsvolume/modifyPersistenceVolume.go
  pkg/skr/gcpnfsvolume/removeFinalizer.go
  pkg/skr/gcpnfsvolume/removePersistenceVolumeFinalizer.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/skr/iprange/addFinalizer.go
  pkg/skr/iprange/deleteKcpIpRange.go
Labels: size/M, lgtm, cla: yes

#166 feat: delete installed CRDs
  api/cloud-resources/v1beta1/awsnfsvolume_types.go
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  api/cloud-resources/v1beta1/iprange_types.go
  cmd/cli/cmdKymaModuleStateUpdate.go
  internal/controller/cloud-control/scope_aws_test.go
  internal/controller/cloud-resources/cloudresources_test.go
  internal/controller/cloud-resources/cr/cloudresources_test.go
  internal/controller/cloud-resources/cr/doc.go
  internal/controller/cloud-resources/cr/suite_test.go
  pkg/composed/list.go
  pkg/kcp/scope/reconciler.go
  pkg/skr/cloudresources/deleteCrds.go
  pkg/skr/cloudresources/reconciler.go
  pkg/testinfra/dsl.go
  pkg/testinfra/dsl/create.go
  pkg/testinfra/dsl/deleteAll.go
  pkg/testinfra/dsl/kyma.go
  pkg/testinfra/infra.go
  pkg/testinfra/run.go
  pkg/testinfra/types.go
  pkg/util/cloudCrd.go
  pkg/util/kyma.go
  pkg/util/kyma_test.go
Labels: size/L, lgtm, cla: yes

#167 feat: renew gcp http client periodically
  config/manager/kustomization.yaml
  pkg/kcp/provider/gcp/client/provider.go
  pkg/kcp/provider/gcp/client/provider_test.go
  pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
Labels: size/L, lgtm, cla: yes
