Repository kyma-project/cloud-manager, pull requests merged in 2024-05, with the labels that each got.

#219 feat: Feature flag to disable controller and CRD def deployment
  cmd/main.go
  config/manager/kustomization.yaml
  internal/controller/cloud-resources/gcpnfsvolumebackup_controller.go
  internal/controller/cloud-resources/gcpnfsvolumerestore_controller.go
  pkg/skr/runtime/looper/installer.go
  pkg/util/featureFlag.go
Labels: size/L, lgtm, cla: yes

#220 (bug) gcpnfsvolume-ui namespace
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
Labels: size/XS, lgtm, cla: yes

#221 feat: GCP Principal Credential Authentication tester
  pkg/kcp/provider/gcp/client/provider.go
  pkg/kcp/provider/gcp/client/serviceUsageClient.go
  pkg/kcp/provider/gcp/iprange/client/computeClient.go
  pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
  pkg/kcp/provider/gcp/nfsbackup/client/fileBackupClient.go
  pkg/kcp/provider/gcp/nfsinstance/client/filestoreClient.go
  pkg/kcp/provider/gcp/nfsrestore/client/fileRestoreClient.go
  pkg/metrics/cloudProvider.go
Labels: size/M, lgtm, cla: yes

#222 fix: GCP Authentication Check
  go.mod
  pkg/kcp/provider/gcp/client/provider.go
Labels: size/M, lgtm, cla: yes

#223 feat: GcpNfsVolumeRestore unit tests
  pkg/kcp/provider/gcp/mock/nfsRestoreStore.go
  pkg/kcp/provider/gcp/mock/server.go
  pkg/skr/gcpnfsvolumebackup/loadScope.go
  pkg/skr/gcpnfsvolumerestore/addFinalizer_test.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume_test.go
  pkg/skr/gcpnfsvolumerestore/loadScope_test.go
  pkg/skr/gcpnfsvolumerestore/removeFinalizer_test.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore_test.go
  pkg/skr/gcpnfsvolumerestore/state_test.go
Labels: size/XXL, lgtm, cla: yes

#213 feat: Azure KCP VpcPeering add finalizer when created
  cmd/main.go
  go.mod
  go.sum
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-control/vpcpeering_controller.go
  pkg/kcp/provider/azure/client/provider.go
  pkg/kcp/provider/azure/config/config.go
  pkg/kcp/provider/azure/vpcpeering/addFinalizer.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/azure/vpcpeering/new.go
  pkg/kcp/provider/azure/vpcpeering/state.go
  pkg/kcp/vpcpeering/reconciler.go
Labels: size/L, lgtm, cla: yes

#224 fix: gcpNfsVolume to reference iprange with correct namespace
  pkg/skr/gcpnfsvolume/state_test.go
  pkg/skr/gcpnfsvolume/validateSpec.go
Labels: size/XS, lgtm, cla: yes

#225 fix: GcpNfsVolumeBackup - delete failure when GcpNfsVolume does not exist
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumebackup/reconciler.go
Labels: size/S, lgtm, cla: yes

#226 fix(aws): requeue delayed in case of a retryable error
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/kcp/provider/aws/config/config.go
  pkg/kcp/provider/aws/iprange/createSubnets.go
  pkg/kcp/provider/aws/iprange/deleteSubnets.go
  pkg/kcp/provider/aws/iprange/disassociateVpcAddressSpace.go
  pkg/kcp/provider/aws/iprange/extendVpcAddressSpace.go
  pkg/kcp/provider/aws/iprange/loadSubnets.go
  pkg/kcp/provider/aws/iprange/loadVpc.go
  pkg/kcp/provider/aws/iprange/new.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/nfsinstance/authorizeSecurityGroupIngress.go
  pkg/kcp/provider/aws/nfsinstance/createEfs.go
  pkg/kcp/provider/aws/nfsinstance/createMountTargets.go
  pkg/kcp/provider/aws/nfsinstance/createSecurityGroup.go
  pkg/kcp/provider/aws/nfsinstance/deleteEfs.go
  pkg/kcp/provider/aws/nfsinstance/deleteMountTargets.go
  pkg/kcp/provider/aws/nfsinstance/deleteSecurityGroup.go
  pkg/kcp/provider/aws/nfsinstance/findSecurityGroup.go
  pkg/kcp/provider/aws/nfsinstance/loadEfs.go
  pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go
  pkg/kcp/provider/aws/nfsinstance/loadSecurityGroup.go
  pkg/kcp/provider/aws/nfsinstance/new.go
  pkg/kcp/provider/aws/nfsinstance/removeMountTargetsFromOtherVpcs.go
  pkg/kcp/provider/gcp/client/provider.go
  pkg/metrics/cloudProvider.go
  pkg/metrics/cloudProviderAws.go
  pkg/util/timing.go
Labels: size/L, lgtm, cla: yes

#228 fix(AwsNfsVolume): requeue when mount targets are deleted
  pkg/composed/action.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/nfsinstance/deleteMountTargets.go
  pkg/util/timing.go
Labels: size/S, lgtm, cla: yes

#229 fix(AwsNfsVolume): ignore filesystem not found error when loading mount targets
  pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go
Labels: size/XS, lgtm, cla: yes

#230 fix(AwsNfsVolume): ignore mount target not found error
  pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go
Labels: size/XS, lgtm, cla: yes

#231 fix(AwsNfsVolume): ignore mount target not found error
  pkg/composed/bridge.go
  pkg/composed/errors.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go
Labels: size/M, lgtm, cla: yes

#232 fix(AwsNfsVolume): wait until mount targets are available
  internal/controller/cloud-control/nfsinstance_controller.go
  internal/controller/cloud-resources/cr/suite_test.go
  internal/controller/cloud-resources/quotaIpRange/suite_test.go
  pkg/kcp/provider/aws/nfsinstance/createMountTargets.go
Labels: size/S, lgtm, cla: yes

#235 chore(AwsNfsVolume): wait for security group to be deleted
  pkg/kcp/provider/aws/nfsinstance/deleteSecurityGroup.go
Labels: size/XS, lgtm, cla: yes

#236 chore: sec scan 0.1.9
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#237 test: integration tests for GcpNfsVolumeRestore reconciler
  internal/controller/cloud-resources/gcpnfsvolumerestore_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/kcp/provider/gcp/mock/server.go
  pkg/kcp/provider/gcp/mock/type.go
  pkg/skr/gcpnfsvolume/ignorant.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolumebackup/ignorant.go
  pkg/skr/gcpnfsvolumebackup/reconciler.go
  pkg/testinfra/dsl/gcpNfsVolumeBackup.go
  pkg/testinfra/dsl/gcpNfsVolumeRestore.go
  pkg/testinfra/dsl/loadAndCheck.go
Labels: size/L, lgtm, cla: yes

#238 test: GcpNfsVolumeBackup unit tests
  pkg/skr/gcpnfsvolumebackup/addFinalizer_test.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume_test.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/loadScope.go
  pkg/skr/gcpnfsvolumebackup/loadScope_test.go
  pkg/skr/gcpnfsvolumebackup/removeFinalizer_test.go
  pkg/skr/gcpnfsvolumebackup/state_test.go
  pkg/skr/gcpnfsvolumebackup/updateStatus.go
  pkg/skr/gcpnfsvolumebackup/updateStatus_test.go
Labels: size/XXL, lgtm, cla: yes

#234 feat (AzureVpcPeering): KCP Create VpcPeering from kyma to remote
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/mock/ctx.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/type.go
  pkg/kcp/provider/azure/mock/vpcPeeringStore.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/azure/vpcpeering/new.go
  pkg/kcp/provider/azure/vpcpeering/updateSuccessStatus.go
  pkg/testinfra/dsl/conditions.go
  pkg/testinfra/dsl/kcpVpcPeering.go
  pkg/testinfra/dsl/scope.go
  pkg/testinfra/env.go
  pkg/testinfra/run.go
  pkg/testinfra/types.go
Labels: size/L, lgtm, cla: yes

#196 docs: Adding testing plan document, to introduce Testing Strategy
  docs/contributor/testing-plan.md
  docs/contributor/testing.md
Labels: size/L, lgtm, cla: yes

#239 feat(AzureVpcPeering): KCP Create VpcPeering from remote to Kyma
  api/cloud-control/v1beta1/vpcpeering_types.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/samples/cloud-control_v1beta1_vpcpeering.yaml
  internal/controller/cloud-control/vpcpeering_aws_test.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
  pkg/kcp/provider/azure/mock/vpcPeeringStore.go
  pkg/kcp/provider/azure/util/resources.go
  pkg/kcp/provider/azure/util/resources_test.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeeringRemote.go
  pkg/kcp/provider/azure/vpcpeering/new.go
Labels: size/L, lgtm, cla: yes

#241 test: GcpNfsVolumeBackup integration tests
  internal/controller/cloud-resources/gcpnfsvolumebackup_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/kcp/provider/gcp/mock/nfsBackupStore.go
  pkg/kcp/provider/gcp/mock/server.go
  pkg/kcp/provider/gcp/mock/type.go
  pkg/testinfra/dsl/gcpNfsVolumeBackup.go
Labels: size/L, lgtm, cla: yes

#242 chore: Feature flags
  Makefile
  cmd/main.go
  config/featureToggles/featureToggles.yaml
  config/featureToggles/flag-schema.json
  go.mod
  go.sum
  internal/controller/cloud-resources/quotaIpRange/quotaIpRange_test.go
  pkg/common/actions/addFinalizer.go
  pkg/common/actions/removeFinalizer.go
  pkg/feature/README.md
  pkg/feature/context.go
  pkg/feature/context_test.go
  pkg/feature/ffApiDisabled.go
  pkg/feature/ffApiDisabled_test.go
  pkg/feature/init.go
  pkg/feature/log.go
  pkg/feature/log_test.go
  pkg/feature/object2feature.go
  pkg/feature/object2feature_test.go
  pkg/feature/testdata/apiDisabled.yaml
  pkg/feature/types.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/skr/iprange/checkQuota.go
  pkg/skr/iprange/checkQuota_test.go
  pkg/skr/runtime/looper/installer.go
  pkg/skr/runtime/looper/runner.go
  pkg/skr/runtime/looper/skrLooper.go
  pkg/skr/runtime/manager/factory.go
  pkg/testinfra/gherkin.go
  pkg/util/string.go
Labels: size/XXL, lgtm, cla: yes

#244 chore: feature flags fixes
  api/cloud-resources/v1beta1/awsnfsvolume_types.go
  api/cloud-resources/v1beta1/awsnfsvolumebackup_types.go
  api/cloud-resources/v1beta1/cloudresources_types.go
  api/cloud-resources/v1beta1/condition.go
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
  api/cloud-resources/v1beta1/gcpnfsvolumerestore_types.go
  api/cloud-resources/v1beta1/iprange_types.go
  config/featureToggles/featureToggles.yaml
  pkg/composed/action.go
  pkg/composed/bridge.go
  pkg/composed/list.go
  pkg/feature/README.md
  pkg/feature/context.go
  pkg/feature/context_test.go
  pkg/feature/ffApiDisabled.go
  pkg/feature/ffApiDisabled_test.go
  pkg/feature/log.go
  pkg/feature/log_test.go
  pkg/feature/object2feature.go
  pkg/feature/object2feature_test.go
  pkg/feature/testdata/apiDisabled.yaml
  pkg/feature/types/types.go
  pkg/skr/cloudresources/checkIfResourcesExist.go
  pkg/skr/iprange/preventDeleteOnAwsNfsVolumeUsage.go
  pkg/skr/iprange/preventDeleteOnGcpNfsVolumeUsage.go
  pkg/skr/runtime/looper/installer.go
  pkg/skr/runtime/looper/runner.go
  pkg/skr/runtime/looper/skrLooper.go
  pkg/skr/runtime/manager/factory.go
  pkg/util/string.go
Labels: size/XL, lgtm, cla: yes

#245 feat: GcpNfsVolume and GcpNfsVolumeBackup Status.State
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  internal/controller/cloud-control/nfsinstance_gcp_test.go
  pkg/kcp/provider/gcp/client/gcpConstants.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState_test.go
  pkg/skr/gcpnfsvolume/deletePVForNameChange.go
  pkg/skr/gcpnfsvolume/deletePersistenceVolume.go
  pkg/skr/gcpnfsvolume/deletePersistenceVolume_test.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance_test.go
  pkg/skr/gcpnfsvolume/updateStatus.go
  pkg/skr/gcpnfsvolume/updateStatus_test.go
  pkg/skr/gcpnfsvolume/validatePV.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/skr/gcpnfsvolume/validateSpec_test.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume_test.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadScope.go
  pkg/skr/gcpnfsvolumebackup/updateStatus.go
  pkg/skr/gcpnfsvolumebackup/updateStatus_test.go
Labels: size/L, lgtm, cla: yes

#246 chore(SKR IpRange): SKR CR Statuses Unification
  api/cloud-resources/v1beta1/iprange_types.go
  api/cloud-resources/v1beta1/state.go
  pkg/composed/updateStatus.go
  pkg/skr/iprange/checkQuota.go
  pkg/skr/iprange/createKcpIpRange.go
  pkg/skr/iprange/deleteKcpIpRange.go
  pkg/skr/iprange/preventCidrChange.go
  pkg/skr/iprange/preventCidrOverlap.go
  pkg/skr/iprange/preventDeleteOnAwsNfsVolumeUsage.go
  pkg/skr/iprange/preventDeleteOnGcpNfsVolumeUsage.go
  pkg/skr/iprange/reconciler.go
  pkg/skr/iprange/setProcessingStateForDeletion.go
  pkg/skr/iprange/state.go
  pkg/skr/iprange/updateId.go
  pkg/skr/iprange/updateStatus.go
  pkg/skr/iprange/validateCidr.go
  pkg/skr/runtime/manager/factory.go
Labels: size/L, lgtm, cla: yes

#247 chore(KCP IpRange): preps for KCP IpRange impl v2 and optional cidr
  pkg/kcp/provider/aws/iprange/client/client.go
  pkg/kcp/provider/aws/iprange/new.go
  pkg/kcp/provider/aws/iprange/state.go
  pkg/kcp/provider/aws/iprange/v1/addFinalizer.go
  pkg/kcp/provider/aws/iprange/v1/checkCidrBlockStatus.go
  pkg/kcp/provider/aws/iprange/v1/checkCidrOverlap.go
  pkg/kcp/provider/aws/iprange/v1/checkSubnetOverlap.go
  pkg/kcp/provider/aws/iprange/v1/createSubnets.go
  pkg/kcp/provider/aws/iprange/v1/deleteSubnets.go
  pkg/kcp/provider/aws/iprange/v1/disassociateVpcAddressSpace.go
  pkg/kcp/provider/aws/iprange/v1/ensureShootZonesAndRangeSubnetsMatch.go
  pkg/kcp/provider/aws/iprange/v1/extendVpcAddressSpace.go
  pkg/kcp/provider/aws/iprange/v1/findCloudResourceSubnets.go
  pkg/kcp/provider/aws/iprange/v1/loadSubnets.go
  pkg/kcp/provider/aws/iprange/v1/loadVpc.go
  pkg/kcp/provider/aws/iprange/v1/new.go
  pkg/kcp/provider/aws/iprange/v1/preventCidrEdit.go
  pkg/kcp/provider/aws/iprange/v1/removeFinalizer.go
  pkg/kcp/provider/aws/iprange/v1/removeReadyCondition.go
  pkg/kcp/provider/aws/iprange/v1/splitRangeByZones.go
  pkg/kcp/provider/aws/iprange/v1/state.go
  pkg/kcp/provider/aws/iprange/v1/updateSuccessStatus.go
  pkg/kcp/provider/aws/iprange/v1/util.go
  pkg/kcp/provider/aws/iprange/v1/waitCidrBlockDisassociated.go
  pkg/kcp/provider/aws/iprange/v1/waitSubnetsDeleted.go
  pkg/kcp/provider/aws/mock/vpcStore.go
Labels: size/L, lgtm, cla: yes

#243 feat(AzureVpcPeering): KCP Create VpcPeering change peering name
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/mock/vpcPeeringStore.go
  pkg/kcp/provider/azure/util/resources_test.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeeringConnection.go
Labels: size/M, lgtm, cla: yes

#248 chore(GcpNfsVolumeRestore): Unification of Status and State
  api/cloud-resources/v1beta1/gcpnfsvolumerestore_types.go
  api/cloud-resources/v1beta1/state.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume_test.go
  pkg/skr/gcpnfsvolumerestore/reconciler.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
  pkg/skr/gcpnfsvolumerestore/setProcessing.go
  pkg/skr/gcpnfsvolumerestore/setProcessing_test.go
Labels: size/L, lgtm, cla: yes

#251 feat(AzureVpcPeering): KCP Load vpc peerings
  api/cloud-control/v1beta1/vpcpeering_types.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  go.mod
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/config/config.go
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/vpcPeeringStore.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeeringRemote.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/loadVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/new.go
  pkg/kcp/provider/azure/vpcpeering/state.go
  pkg/testinfra/dsl/scope.go
Labels: size/L, lgtm, cla: yes

#252 feat(AzureVpcPeering): KCP stop when peered and ready
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/new.go
  pkg/kcp/provider/azure/vpcpeering/updateStatus.go
Labels: size/M, lgtm, cla: yes

#250 (feat) updated make and sync file to build and copy ui YAMLs
  Makefile
  config/sync.sh
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/kustomization.yaml
Labels: size/L, lgtm, cla: yes

#254 feat(GCPVpcPeering): KCP GCP VpcPeering
  api/cloud-control/v1beta1/vpcpeering_types.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  go.mod
  go.sum
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-control/vpcpeering_controller.go
  internal/controller/cloud-control/vpcpeering_gcp_test.go
  pkg/kcp/provider/gcp/cloudclient/provider.go
  pkg/kcp/provider/gcp/mock/server.go
  pkg/kcp/provider/gcp/mock/type.go
  pkg/kcp/provider/gcp/mock/vpcPeeringStore.go
  pkg/kcp/provider/gcp/vpcpeering/addFinalizer.go
  pkg/kcp/provider/gcp/vpcpeering/client/cloudComputeClient.go
  pkg/kcp/provider/gcp/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/gcp/vpcpeering/new.go
  pkg/kcp/provider/gcp/vpcpeering/state.go
  pkg/kcp/provider/gcp/vpcpeering/updateSuccessStatus.go
  pkg/kcp/vpcpeering/reconciler.go
  pkg/testinfra/dsl/kcpVpcPeering.go
  pkg/testinfra/dsl/scope.go
  tools/demo/gcpvpcpeering/kcp-gcp-vpcpeering.yaml
  tools/demo/gcpvpcpeering/skr-gcp-vpcpeering.yaml
  tools/dev/README.md
Labels: size/XL, lgtm, cla: yes

#253 chore(AwsNfsVolume): State and Status unification
  api/cloud-resources/v1beta1/awsnfsvolume_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  internal/controller/cloud-resources/awsnfsvolume_test.go
  pkg/skr/awsnfsvolume/createKcpNfsInstance.go
  pkg/skr/awsnfsvolume/deletePv.go
  pkg/skr/awsnfsvolume/loadSkrIpRange.go
  pkg/skr/awsnfsvolume/updateId.go
  pkg/skr/awsnfsvolume/updateStatus.go
  pkg/testinfra/dsl/awsNfsVolume.go
Labels: size/M, lgtm, cla: yes

#256 chore: Check if test GUIDs are unique
  .github/workflows/pr-checks.yml
  internal/controller/cloud-control/vpcpeering_aws_test.go
Labels: size/XS, lgtm, cla: yes

#257 fix: feature context loading
  internal/controller/cloud-control/iprange_controller.go
  internal/controller/cloud-control/nfsinstance_controller.go
  pkg/common/actions/addFinalizer.go
  pkg/common/actions/focal/loadFeatureContext.go
  pkg/common/actions/focal/loadKyma.go
  pkg/common/actions/focal/new.go
  pkg/common/actions/focal/providerPredicate.go
  pkg/common/actions/focal/state.go
  pkg/common/actions/focal/types.go
  pkg/common/actions/removeFinalizer.go
  pkg/feature/context.go
  pkg/feature/loadFeatureContextFromObj.go
  pkg/kcp/iprange/reconciler.go
  pkg/kcp/iprange/state.go
  pkg/kcp/nfsinstance/loadIpRange.go
  pkg/kcp/nfsinstance/reconciler.go
  pkg/kcp/provider/aws/iprange/v1/checkCidrBlockStatus.go
  pkg/kcp/provider/aws/iprange/v1/ensureShootZonesAndRangeSubnetsMatch.go
  pkg/kcp/provider/aws/iprange/v1/extendVpcAddressSpace.go
  pkg/kcp/provider/aws/iprange/v1/loadVpc.go
  pkg/kcp/provider/aws/iprange/v1/splitRangeByZones.go
  pkg/kcp/provider/aws/iprange/v1/updateSuccessStatus.go
  pkg/kcp/provider/aws/iprange/v2/ensureShootZonesAndRangeSubnetsMatch.go
  pkg/kcp/provider/aws/iprange/v2/new.go
  pkg/kcp/provider/aws/iprange/v2/rangeCheckBlockStatus.go
  pkg/kcp/provider/aws/iprange/v2/rangeExtendVpcAddressSpace.go
  pkg/kcp/provider/aws/iprange/v2/rangeSplitByZones.go
  pkg/kcp/provider/aws/iprange/v2/statusSuccess.go
  pkg/kcp/provider/aws/nfsinstance/loadSecurityGroup.go
  pkg/kcp/provider/aws/nfsinstance/validateExistingMountTargets.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadVpc.go
  pkg/kcp/vpcpeering/reconciler.go
  pkg/skr/awsnfsvolume/reconciler.go
  pkg/skr/awsnfsvolumebackup/reconciler.go
  pkg/skr/azurevpcpeering/reconciler.go
  pkg/skr/cloudresources/reconciler.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume_test.go
  pkg/skr/gcpnfsvolumebackup/loadScope_test.go
  pkg/skr/gcpnfsvolumebackup/reconciler.go
  pkg/skr/gcpnfsvolumebackup/updateStatus_test.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume_test.go
  pkg/skr/gcpnfsvolumerestore/loadScope_test.go
  pkg/skr/gcpnfsvolumerestore/reconciler.go
  pkg/skr/gcpnfsvolumerestore/setProcessing_test.go
  pkg/skr/iprange/reconciler.go
Labels: size/L, lgtm, cla: yes

#259 feat: optional SKR IpRange cidr
  api/cloud-resources/v1beta1/iprange_types.go
  config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  internal/controller/cloud-resources/iprange_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/kcp/iprange/allocate/addressSpace.go
  pkg/kcp/iprange/allocate/rangeList.go
  pkg/skr/iprange/deleteKcpIpRange.go
  pkg/skr/iprange/preventCidrChange.go
  pkg/skr/iprange/preventCidrOverlap.go
  pkg/skr/iprange/updateStatus.go
  pkg/skr/iprange/validateCidr.go
  pkg/testinfra/dsl/objActions.go
Labels: size/XL, lgtm, cla: yes

#258 feat(AzureVpcPeering): SKR create KCP peering
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/skr/azurevpcpeering/createKpcVpcPeering.go
  pkg/skr/azurevpcpeering/loadKcpAzureVpcPeering.go
  pkg/skr/azurevpcpeering/reconciler.go
  pkg/skr/azurevpcpeering/state.go
  pkg/skr/azurevpcpeering/updateId.go
  pkg/skr/azurevpcpeering/updateStatus.go
Labels: size/L, lgtm, cla: yes

#260 fix: load of Kyma CR for feature context loading
  config/featureToggles/featureToggles.yaml
  pkg/common/actions/focal/loadKyma.go
Labels: size/S, lgtm, cla: yes
