Repository kyma-project/cloud-manager, pull requests merged in 2024-11, with the labels that each got.

#774 fix(GcpRedisInstance): pass replicaCount to google API
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
Labels: size/XS, lgtm, cla: yes

#775 fix(GcpRedisInstance): standard tier min memorysize to 5gb
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
Labels: size/S, lgtm, cla: yes

#776 test(RedisInstance): add KCP GCP API tests
  internal/api-tests/kcp_redisinstance_gcp_test.go
Labels: size/M, lgtm, cla: yes

#739 docs(AzureRedis): user docs
  docs/user/resources/04-80-azure-redis-instance.md
  docs/user/resources/README.md
Labels: size/M, lgtm, cla: yes

#777 (feat) Added replica support for Azure and GCP Redis Instance
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/details
  config/ui-extensions/azureredisinstances/form
  config/ui-extensions/azureredisinstances/kustomization.yaml
  config/ui-extensions/azureredisinstances/translations
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/details
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpredisinstances/kustomization.yaml
  config/ui-extensions/gcpredisinstances/translations
Labels: size/M, lgtm, cla: yes

#778 feat(GcpRedisInstance): replace tier and memorySizeGb with redisTier
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  config/samples/cloud-resources_v1beta1_gcpredisinstance.yaml
  internal/api-tests/builder_test.go
  internal/api-tests/kcp_redisinstance_gcp_test.go
  internal/api-tests/network_test.go
  internal/api-tests/skr_gcpredisinstance_test.go
  internal/api-tests/vpcpeering_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  pkg/kcp/provider/gcp/redisinstance/modifyMemoryReplicaCount.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/state.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/skr/gcpredisinstance/modifyKcpRedisInstance.go
  pkg/skr/gcpredisinstance/state.go
  pkg/skr/gcpredisinstance/util.go
  pkg/skr/gcpredisinstance/util_test.go
  pkg/testinfra/dsl/gcpRedisInstance.go
Labels: size/XL, lgtm, cla: yes

#781 (feat): updated gcp redis instances with tier abstraction
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/details
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpredisinstances/kustomization.yaml
  config/ui-extensions/gcpredisinstances/translations
Labels: size/M, lgtm, cla: yes

#785 feat(GcpRedisInstance): remove replicaCount from API
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  config/samples/cloud-resources_v1beta1_gcpredisinstance.yaml
  internal/api-tests/skr_gcpredisinstance_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/skr/gcpredisinstance/modifyKcpRedisInstance.go
  pkg/skr/gcpredisinstance/state.go
  pkg/skr/gcpredisinstance/util.go
  pkg/skr/gcpredisinstance/util_test.go
  pkg/testinfra/dsl/gcpRedisInstance.go
Labels: size/L, cla: yes

#786 feat(AzureRedis): remove replica count
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-resources/azureredisinstance_test.go
  pkg/kcp/provider/azure/redisinstance/createRedis.go
  pkg/skr/azureredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/azureRedisInstance.go
Labels: size/M, lgtm, cla: yes

#705 chore: Test with k8s v1.30.0
  Makefile
Labels: size/XS, cla: yes

#789 docs(AwsRedisInstance): add redisTier details
  docs/user/resources/04-70-aws-redis-instance.md
  docs/user/tutorials/01-70-aws-redis-instance.md
Labels: size/M, lgtm, cla: yes

#790 docs(AzureRedis): remove replicas, replace sku.capacity with redisTier
  docs/user/resources/04-80-azure-redis-instance.md
Labels: size/XS, lgtm, cla: yes

#788 (feat): Redis Instance UI Update
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/details
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsredisinstances/kustomization.yaml
  config/ui-extensions/awsredisinstances/translations
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/details
  config/ui-extensions/azureredisinstances/form
  config/ui-extensions/azureredisinstances/kustomization.yaml
  config/ui-extensions/azureredisinstances/translations
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/details
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpredisinstances/kustomization.yaml
  config/ui-extensions/gcpredisinstances/translations
Labels: size/L, lgtm, cla: yes

#782 docs: updates Azure VPC peering service principal
  docs/user/resources/04-40-10-azure-vpc-peering.md
  docs/user/tutorials/01-30-azure-vpc-peering.md
Labels: size/L, cla: yes

#792 docs: Adds Cloud Manager service principal to Kyma landscape mapping
  docs/user/resources/04-40-10-azure-vpc-peering.md
Labels: size/S, cla: yes

#794 docs: Adds Cloud Manager principal to Kyma landscape mapping
  docs/user/resources/04-70-10-aws-vpc-peering.md
Labels: size/S, cla: yes

#791 feat(GcpNfsVolume): add API validators
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/patchAfterMakeManifests.sh
  internal/api-tests/skr_gcpnfsvolume_test.go
Labels: size/L, lgtm, cla: yes

#737 (docs): updated README.md for auto-updating UI ConfigMaps
  docs/contributor/ui/README.md
Labels: size/S, cla: yes

#796 feat(AzureVpcPeering): allows VpcPeering to be deleted if local Network is missing
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/vpcpeering/kcpNetworkLocalLoad.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go
Labels: size/M, lgtm, cla: yes

#798 feat(AzureVpcPeering): allows VpcPeering to be deleted if local Network is missing
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/vpcpeering/kcpNetworkLocalLoad.go
Labels: size/S, cla: yes

#801 fix: fixed bug where kustomize was adding extra |2 to the manifest
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/form
  config/ui-extensions/azureredisinstances/kustomization.yaml
Labels: size/S, lgtm, cla: yes

#779 chore: garden shoot create azure
  cmd/cli/cmdGardenShootCreateAzure.go
Labels: size/L, cla: yes

#800 chore: upgrade to google.golang.org/grpc v1.68.0
  .github/workflows/pr-golang-lint.yml
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#804 fix: prevent kcp network and kcp iprange delete when used
  CODEOWNERS
  api/cloud-control/v1beta1/conditions.go
  api/cloud-control/v1beta1/iprange_ref.go
  api/cloud-control/v1beta1/iprange_types.go
  api/cloud-control/v1beta1/vpcpeering_types.go
  cmd/main.go
  internal/controller/cloud-control/iprange_controller.go
  internal/controller/cloud-control/iprange_delete_test.go
  internal/controller/cloud-control/network_controller.go
  internal/controller/cloud-control/network_reference_test.go
  internal/controller/cloud-control/scope_controller.go
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-control/vpcpeering_aws_test.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/composed/preventDeleteWhenUsed.go
  pkg/kcp/iprange/preventDeleteOnNfsInstanceUsage.go
  pkg/kcp/iprange/preventDeleteOnRedisInstanceUsage.go
  pkg/kcp/iprange/reconciler.go
  pkg/kcp/iprange/statusReady.go
  pkg/kcp/network/preventDeleteWhenUsedByIpRange.go
  pkg/kcp/network/preventDeleteWhenUsedByPeeringLocalNetwork.go
  pkg/kcp/network/preventDeleteWhenUsedByPeeringRemoteNetwork.go
  pkg/kcp/network/reconciler.go
  pkg/skr/iprange/preventDeleteOnAwsNfsVolumeUsage.go
  pkg/skr/iprange/preventDeleteOnAwsRedisInstanceUsage.go
  pkg/skr/iprange/preventDeleteOnAzureRedisInstanceUsage.go
  pkg/skr/iprange/preventDeleteOnGcpNfsVolumeUsage.go
  pkg/skr/iprange/preventDeleteOnGcpRedisInstanceUsage.go
  pkg/testinfra/dsl/conditions.go
  pkg/testinfra/dsl/loadAndCheck.go
  pkg/testinfra/dsl/scope.go
Labels: size/XXL, lgtm, cla: yes

#806 feat(RedisInstance): add API validator to ensure IpRange is defined
  api/cloud-control/v1beta1/redisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  internal/api-tests/kcp_redisinstance_test.go
Labels: size/L, lgtm, cla: yes

#803 (docs): Adjust tutorials' structure
  docs/user/_sidebar.md
  docs/user/resources/04-40-20-aws-redis-instance.md
  docs/user/tutorials/01-20-10-aws-nfs-volume.md
  docs/user/tutorials/01-20-11-aws-nfs-volume-backup.md
  docs/user/tutorials/01-20-12-aws-scheduled-nfs-backup.md
  docs/user/tutorials/01-20-13-aws-nfs-volume-restore.md
  docs/user/tutorials/01-20-20-gcp-nfs-volume.md
  docs/user/tutorials/01-20-21-gcp-nfs-volume-backup.md
  docs/user/tutorials/01-20-22-gcp-scheduled-nfs-backup.md
  docs/user/tutorials/01-20-23-gcp-nfs-volume-restore.md
  docs/user/tutorials/01-30-10-azure-vpc-peering.md
  docs/user/tutorials/01-30-20-aws-vpc-peering.md
  docs/user/tutorials/01-30-30-gcp-vpc-peering.md
  docs/user/tutorials/01-40-10-gcp-redis-instance.md
  docs/user/tutorials/01-40-20-aws-redis-instance.md
  docs/user/tutorials/01-60-gcp-redis-instance.md
  docs/user/tutorials/README.md
Labels: size/XXL, lgtm, cla: yes

#807 feat(Nuke): StopAndForget Completed Nukes
  pkg/kcp/nuke/reconciler.go
  pkg/kcp/nuke/shortCircuitCompleted.go
  pkg/kcp/nuke/statusCompleted.go
Labels: size/S, lgtm, cla: yes

#808 chore: log finalizer removal
  pkg/common/actions/removeFinalizer.go
Labels: size/XS, lgtm, cla: yes

#813 chore(NfsInstance, GCP): add logs to factory
  pkg/kcp/provider/gcp/nfsinstance/new.go
Labels: size/XS, lgtm, cla: yes

#810 doc(TestingStrategy): testing strategy pipelines
  docs/contributor/testing-strategy.md
Labels: size/S, lgtm, cla: yes

#814 fix(RedisInstance): stop KCP loop due to status update
  pkg/kcp/provider/aws/redisinstance/updateStatus.go
  pkg/kcp/provider/azure/redisinstance/updateStatus.go
  pkg/kcp/provider/gcp/redisinstance/updateStatus.go
Labels: size/S, lgtm, cla: yes

#812 fix(NfsBackupSchedule): continuous looping of the one-time schedule
  internal/controller/cloud-resources/aws/awsnfsbackupschedule_test.go
  internal/controller/cloud-resources/gcpnfsbackupschedule_test.go
  pkg/skr/backupschedule/calculateOnetimeSchedule.go
  pkg/skr/backupschedule/calculateOnetimeSchedule_test.go
  pkg/skr/backupschedule/evaluateNextRun.go
  pkg/testinfra/dsl/nfsBackupSchedule.go
Labels: size/M, lgtm, cla: yes

#817 chore: build main tag
  .github/workflows/cloud-manager-build.yml
Labels: size/S, lgtm, cla: yes

#819 test(RedisInstance): handle canceled context in cloud provider fakes
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
Labels: size/L, cla: yes

#818 chore(Network): fix error msg
  pkg/kcp/network/preventDeleteWhenUsedByIpRange.go
Labels: size/XS, cla: yes

#822 chore: splits image build into steps
  .github/workflows/cloud-manager-build.yml
Labels: size/S, lgtm, cla: yes

#824 chore: separates image build into workflows for PR and main
  .github/workflows/build-image-pr.yaml
  .github/workflows/cloud-manager-build.yml
  .github/workflows/image-build-main.yaml
Labels: size/M, lgtm, cla: yes

#821 fix(IpRange): remove kcpNetworkDeleteWait to prevent deadlock while deleting IpRange!
  pkg/kcp/iprange/kcpNetworkDeleteWait.go
  pkg/kcp/iprange/reconciler.go
Labels: size/S, lgtm, cla: yes

#826 chore: updates testing strategy according to workflow changes
  docs/contributor/testing-strategy.md
Labels: size/XS, cla: yes

#820 chore: updates sec-scanners-config
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#830 chore: VpcPeering config
  cmd/main.go
  config/config/vpcpeering.yaml
  pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
  pkg/kcp/provider/aws/vpcpeering/kcpNetworkLocalLoad.go
  pkg/kcp/provider/aws/vpcpeering/kcpNetworkRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/kcpNetworkLocalLoad.go
  pkg/kcp/provider/azure/vpcpeering/kcpNetworkRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/waitNetworkTag.go
  pkg/kcp/provider/gcp/vpcpeering/createKymaVpcPeering.go
  pkg/kcp/vpcpeering/config/config.go
Labels: size/M, lgtm, cla: yes

#831 chore(AwsRedisInstance): update error msg
  pkg/skr/awsredisinstance/modifyKcpRedisInstance.go
Labels: size/XS, lgtm, cla: yes

#832 fix: unable to delete VPC peering when network is in Warning state
  pkg/kcp/provider/aws/vpcpeering/createRemoteClient.go
  pkg/kcp/provider/aws/vpcpeering/kcpNetworkLocalLoad.go
  pkg/kcp/provider/aws/vpcpeering/kcpNetworkRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/kcpNetworkLocalLoad.go
  pkg/kcp/provider/azure/vpcpeering/kcpNetworkRemoteLoad.go
Labels: size/S, lgtm, cla: yes

#834 chore: fixes race condition in tests
  internal/controller/cloud-control/vpcpeering_azure_test.go
Labels: size/S, cla: yes

#833 fix(AzureRedis): retry creating/updating private end point when it is in failed state
  internal/controller/cloud-control/redisinstance_azure_test.go
  pkg/kcp/provider/azure/mock/privateEndPointStore.go
  pkg/kcp/provider/azure/redisinstance/createPrivateEndPoint.go
  pkg/kcp/provider/azure/redisinstance/loadPrivateEndPoint.go
  pkg/kcp/provider/azure/redisinstance/new.go
  pkg/kcp/provider/azure/redisinstance/waitPrivateEndPointAvailable.go
Labels: size/M, lgtm, cla: yes

#837 feat(GcpVpcPeering): print current state during wait
  pkg/kcp/provider/gcp/vpcpeering/waitRemoteVpcPeeringAvailable.go
  pkg/kcp/provider/gcp/vpcpeering/waitVpcPeeringActive.go
Labels: size/S, lgtm, cla: yes

#836 fix(AwsVpcPeering): waits pending acceptance status before accepting connection
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/util/peering.go
  pkg/kcp/provider/aws/vpcpeering/createRemoteClient.go
  pkg/kcp/provider/aws/vpcpeering/createRemoteRoutes.go
  pkg/kcp/provider/aws/vpcpeering/createRoutes.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/deleteRoutes.go
  pkg/kcp/provider/aws/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/new.go
  pkg/kcp/provider/aws/vpcpeering/remotePeeringDelete.go
  pkg/kcp/provider/aws/vpcpeering/remoteRoutesDelete.go
  pkg/kcp/provider/aws/vpcpeering/waitPendingAcceptance.go
  pkg/kcp/provider/aws/vpcpeering/waitVpcPeeringActive.go
Labels: size/L, lgtm, cla: yes

#840 release 1.2.1
  sec-scanners-config.yaml
Labels: size/XS, cla: yes

#809 (docs): Adjust user/README.md to Help Portal structure
  docs/user/00-20-nfs.md
  docs/user/00-30-vpc-peering.md
  docs/user/00-40-redis.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/04-30-10-aws-vpc-peering.md
  docs/user/resources/04-30-20-gcp-vpc-peering.md
  docs/user/resources/04-30-30-azure-vpc-peering.md
  docs/user/resources/04-40-10-aws-redis-instance.md
  docs/user/resources/04-40-20-gcp-redis-instance.md
  docs/user/resources/04-40-30-azure-redis-instance.md
  docs/user/resources/README.md
  docs/user/tutorials/01-30-10-aws-vpc-peering.md
  docs/user/tutorials/01-30-20-gcp-vpc-peering.md
  docs/user/tutorials/01-30-30-azure-vpc-peering.md
  docs/user/tutorials/01-40-10-aws-redis-instance.md
  docs/user/tutorials/01-40-20-gcp-redis-instance.md
  docs/user/tutorials/README.md
Labels: documentation, size/L, area/documentation, cla: yes

#842 feat(AzureRedisInstance): remove shardCount from api
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/patchAfterMakeManifests.sh
  docs/user/resources/04-40-30-azure-redis-instance.md
  pkg/skr/azureredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/azureRedisInstance.go
Labels: size/M, lgtm, cla: yes

#841 fix(AzureVpcPeering): fixes deletion issues when SPN is unauthorized
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteDelete.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go
Labels: size/S, lgtm, cla: yes

#843 fix: upgrade x-text 1.19.0
  go.mod
  go.sum
Labels: size/XS, lgtm, cla: yes

#844 sec scan 1.2.2
  sec-scanners-config.yaml
Labels: cla: yes

#845 fix(AwsVpcPeering): fixes deletion issues when role is unauthorized
  pkg/kcp/provider/aws/vpcpeering/loadRemoteRouteTables.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpcPeeringConnection.go
Labels: size/M, lgtm, cla: yes
