Repository kyma-project/cloud-manager, pull requests merged in 2024-12, with the labels that each got.

#848 fix(AzureVpcPeering): fixes deletion issues when Kyma SPN is unauthorized
  api/cloud-control/v1beta1/vpcpeering_types.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/mock/networkStore.go
  pkg/kcp/provider/azure/mock/type.go
  pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteDelete.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/vpcRemoteLoad.go
Labels: size/L, lgtm, cla: yes

#849 feat: removed shardCount from AzureRedisInstance UI
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/details
  config/ui-extensions/azureredisinstances/form
  config/ui-extensions/azureredisinstances/kustomization.yaml
  config/ui-extensions/azureredisinstances/translations
Labels: size/M, lgtm, cla: yes

#850 docs: Remove the toc
  docs/user/resources/README.md
Labels: size/M, lgtm, cla: yes

#847 fix(AwsVpcPeering): relaxes authorization error requeue
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
Labels: size/M, cla: yes

#856 docs: Fix sidebar
  docs/user/_sidebar.md
Labels: documentation, size/S, lgtm, cla: yes

#829 feat(Nuke): nuke orphaned gcp filestore backups
  api/cloud-control/v1beta1/labels.go
  api/cloud-control/v1beta1/nuke_types.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_nukes.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_nukes.yaml
  internal/controller/cloud-control/nuke_controller.go
  internal/controller/cloud-control/nuke_gcp_test.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/nuke/checkIfAllDeleted.go
  pkg/kcp/nuke/loadResources.go
  pkg/kcp/nuke/reconciler.go
  pkg/kcp/nuke/resourceStatusDeleted.go
  pkg/kcp/nuke/resourceStatusDeleting.go
  pkg/kcp/nuke/resourceStatusDiscovered.go
  pkg/kcp/nuke/shortCircuitCompleted.go
  pkg/kcp/nuke/state.go
  pkg/kcp/nuke/statusCompleted.go
  pkg/kcp/nuke/types/state.go
  pkg/kcp/provider/gcp/client/gcpConstants.go
  pkg/kcp/provider/gcp/mock/nfsBackupStore.go
  pkg/kcp/provider/gcp/nfsbackup/client/fileBackupClient.go
  pkg/kcp/provider/gcp/nuke/checkIfAllProviderResourcesDeleted.go
  pkg/kcp/provider/gcp/nuke/deleteNfsBackups.go
  pkg/kcp/provider/gcp/nuke/loadNfsBackups.go
  pkg/kcp/provider/gcp/nuke/new.go
  pkg/kcp/provider/gcp/nuke/providerResourceStatusDeleted.go
  pkg/kcp/provider/gcp/nuke/providerResourceStatusDeleting.go
  pkg/kcp/provider/gcp/nuke/providerResourceStatusDiscovered.go
  pkg/kcp/provider/gcp/nuke/state.go
  pkg/skr/gcpnfsvolumebackup/addLabelsToNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/addLabelsToNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/reconciler.go
  pkg/testinfra/dsl/gcpNfsVolumeBackup.go
Labels: size/XXL, lgtm, cla: yes

#855 fix(AwsVpcPeering): relaxes requeuing while waiting peering statuses
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/mock/vpcPeeringStore.go
  pkg/kcp/provider/aws/mock/vpcStore.go
  pkg/kcp/provider/aws/vpcpeering/createRoutes.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go
  pkg/kcp/provider/aws/vpcpeering/waitPendingAcceptance.go
  pkg/kcp/provider/aws/vpcpeering/waitVpcPeeringActive.go
Labels: size/L, cla: yes

#862 fix: kcp kyma network delete
  internal/controller/cloud-control/network_reference_test.go
  internal/controller/cloud-control/scope_aws_test.go
  pkg/common/actions/focal/loadKyma.go
  pkg/common/actions/focal/loadScopeFromRef.go
  pkg/common/actions/focal/new.go
  pkg/common/actions/focal/state.go
  pkg/kcp/network/handleNetworkReference.go
  pkg/kcp/network/logLogicalErrorOnManagedNetworkMissing.go
  pkg/kcp/network/reconciler.go
  pkg/kcp/scope/kymaNetworkReferenceCreate.go
  pkg/kcp/scope/kymaNetworkReferenceDelete.go
  pkg/kcp/scope/reconciler.go
  pkg/kcp/scope/scopeCreate.go
  pkg/kcp/scope/scopeDelete.go
  pkg/kcp/scope/scopeSave.go
  pkg/kcp/scope/skrDeactivate.go
Labels: size/L, lgtm, cla: yes

#867 chore: gh issue template permission change
  .github/ISSUE_TEMPLATE/cm-permissions.yaml
Labels: size/M, cla: yes

#864 chore: remove ipRangeAutomaticCidrAllocation feature toggle
  CODEOWNERS
  config/featureToggles/featureToggles.yaml
  pkg/feature/ffIpRangeAutomaticCidrAllocation.go
Labels: size/S, lgtm, cla: yes

#869 docs: documenting required permissions for filestore backup list and …
  docs/contributor/gcp-permissions.md
Labels: size/XS, lgtm, cla: yes

#866 chore: add printable columns for kcp network and redis
  api/cloud-control/v1beta1/network_types.go
  api/cloud-control/v1beta1/redisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_networks.yaml
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_networks.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
Labels: size/M, cla: yes

#859 refactor(GcpNfsVolume): remove obsolete methods validateCapacity and validateFileShareName
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/skr/gcpnfsvolume/validateSpec_test.go
Labels: size/L, lgtm, cla: yes

#876 refactor(GcpRedisInstance): handle NotFound in action instead of client
  pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
  pkg/kcp/provider/gcp/redisinstance/loadRedis.go
Labels: size/M, cla: yes

#871 fix(AzureVpcPeering): handles CIDR overlap error
  api/cloud-control/v1beta1/conditions.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/remoteClientCreate.go
Labels: size/M, lgtm, cla: yes

#874 chore: feature flag nukeBackupsGcp
  .github/workflows/pr-checks.yml
  config/featureToggles/featureToggles.yaml
  internal/controller/cloud-control/nuke_gcp_test.go
  pkg/composed/predicate.go
  pkg/feature/ffNukeBackupsGcp.go
  pkg/kcp/nuke/reconciler.go
Labels: size/M, cla: yes

#865 chore(AwsVpcPeering): change mock to return cloned object
  pkg/kcp/provider/aws/mock/vpcPeeringStore.go
Labels: size/M, cla: yes

#878 chore: merge gate
  .checkmarx/config.yml
  .github/workflows/merge-gate.yaml
  internal/controller/cloud-resources/iprange_test.go
  pkg/testinfra/dsl/gomega.go
Labels: size/L, cla: yes

#879 chore: merge gate
  .github/workflows/merge-gate.yaml
Labels: size/XS, lgtm, cla: yes

#882 sec scan 1.2.3
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#880 chore(RedisInstance): use .status.state (GCP, AWS)
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/types.go
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-control/redisinstance_gcp_test.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/removeReadyCondition.go
  pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/updateStatus.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
  pkg/kcp/provider/aws/redisinstance/waitUserGroupDeleted.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
  pkg/kcp/provider/gcp/redisinstance/loadRedis.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go
  pkg/kcp/provider/gcp/redisinstance/updateStatus.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisAvailable.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisDeleted.go
Labels: size/M, lgtm, cla: yes

#885 chore(RedisInstance): no longer put cloud provider errors in conditions
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
  pkg/kcp/provider/aws/redisinstance/waitUserGroupDeleted.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
  pkg/kcp/provider/gcp/redisinstance/loadRedis.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/updateRedis.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisAvailable.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisDeleted.go
Labels: size/M, lgtm, cla: yes

#883 chore: run merge-gate on pr label change
  .github/workflows/merge-gate.yaml
Labels: size/XS, lgtm, cla: yes

#886 refactor(RedisInstance): move auth secret to separate file
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  api/cloud-resources/v1beta1/redisinstance_authsecret.go
Labels: size/S, cla: yes

#888 docs(AzureVpcPeering): updating documentation
  docs/user/resources/04-30-30-azure-vpc-peering.md
  docs/user/tutorials/01-30-30-azure-vpc-peering.md
Labels: size/XS, lgtm, cla: yes

#827 chore: upgrade k8s version to 1.31.0
  Makefile
  pkg/testinfra/run.go
Labels: size/XS, lgtm, cla: yes

#893 chore(IpRange): fix flaky test
  internal/controller/cloud-resources/iprange_test.go
Labels: size/XS, lgtm, cla: yes

#877 chore(AzureVpcPeering): improve log messages
  pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteCreate.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteDelete.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/remoteClientCreate.go
  pkg/kcp/provider/azure/vpcpeering/vpcRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/waitNetworkTag.go
Labels: size/M, cla: yes

#889 feat(GcpNfsVolume): remove support for legacy tiers
  api/cloud-control/v1beta1/nfsinstance_gcp_types.go
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/patchAfterMakeManifests.sh
  internal/api-tests/skr_gcpnfsvolume_test.go
  pkg/kcp/provider/gcp/nfsinstance/validations.go
  pkg/kcp/provider/gcp/nfsinstance/validations_test.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/skr/gcpnfsvolume/validateSpec_test.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
Labels: size/L, lgtm, cla: yes

#899 chore: remove fallbacks (featureconfig, envtest)
  pkg/feature/init.go
  pkg/testinfra/run.go
Labels: size/S, lgtm, cla: yes

#872 feat(Nuke): Clean up of AWS Recovery Points when SKR is deleted
  .github/workflows/pr-checks.yml
  cmd/main.go
  config/featureToggles/featureToggles.yaml
  internal/controller/cloud-control/nuke_aws_test.go
  internal/controller/cloud-control/nuke_controller.go
  internal/controller/cloud-control/suite_test.go
  pkg/feature/ffNukeBackupsAws.go
  pkg/kcp/nuke/reconciler.go
  pkg/kcp/provider/aws/nuke/checkIfAllProviderResourcesDeleted.go
  pkg/kcp/provider/aws/nuke/client/client.go
  pkg/kcp/provider/aws/nuke/client/mock.go
  pkg/kcp/provider/aws/nuke/createAwsClient.go
  pkg/kcp/provider/aws/nuke/deleteNfsBackups.go
  pkg/kcp/provider/aws/nuke/loadNfsBackups.go
  pkg/kcp/provider/aws/nuke/new.go
  pkg/kcp/provider/aws/nuke/providerResourceStatusDeleted.go
  pkg/kcp/provider/aws/nuke/providerResourceStatusDeleting.go
  pkg/kcp/provider/aws/nuke/providerResourceStatusDiscovered.go
  pkg/kcp/provider/aws/nuke/state.go
  pkg/skr/awsnfsvolumebackup/client/client.go
  pkg/skr/awsnfsvolumebackup/client/mock.go
Labels: size/XL, lgtm, cla: yes

#898 chore: Removing gcpNfsVolumeAutomaticLocationAllocation FF from cloud…
  .github/workflows/pr-checks.yml
  config/featureToggles/featureToggles.yaml
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  internal/controller/cloud-resources/gcpnfsvolumebackup_test.go
  pkg/feature/ffGcpNfsVolumeAutomaticLocationAllocation.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/skr/gcpnfsvolumebackup/reconciler.go
  pkg/skr/gcpnfsvolumebackup/validateSpec.go
  pkg/skr/gcpnfsvolumebackup/validateSpec_test.go
  pkg/testinfra/gherkin.go
Labels: size/L, lgtm, cla: yes

#895 fix(AzureVpcPeering): handles Azure error InvalidAuthenticationTokenTenant
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteCreate.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/vpcRemoteLoad.go
Labels: size/S, cla: yes

#904 chore: renovate config
  renovate.json
Labels: size/S, cla: yes

#897 chore(AzureVpcPeering): skip status update while waiting local peering connected
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalWaitReady.go
Labels: size/L, cla: yes

#903 fix: bump x-crypto@v0.31.0
  .gitignore
  docs/contributor/dependency-graph.md
  go.mod
  go.sum
  pkg/testinfra/dsl/shoot.go
Labels: size/L, area/dependency, lgtm, cla: yes

#905 chore: added dependabot config
  .github/dependabot.yml
Labels: size/M, lgtm, cla: yes

#917 fix: skip SKR controller name validation
  pkg/skr/runtime/manager/manager.go
Labels: size/XS, lgtm, cla: yes

#913 feat(gcpNfsVolume): preventing reduction of capacity for BASIC tiers
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/patchAfterMakeManifests.sh
  internal/api-tests/skr_gcpnfsvolume_test.go
Labels: size/M, lgtm, cla: yes

#925 fix: nuke does not requeue when no scope
  pkg/kcp/nuke/reconciler.go
Labels: size/XS, cla: yes

#902 feat(GcpRedisInstance): make redisVersion upgradable
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  docs/user/resources/04-40-20-gcp-redis-instance.md
  internal/api-tests/skr_gcpredisinstance_test.go
  pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/state.go
  pkg/kcp/provider/gcp/redisinstance/upgradeRedis.go
  pkg/skr/gcpredisinstance/modifyKcpRedisInstance.go
  pkg/skr/gcpredisinstance/state.go
Labels: size/L, lgtm, cla: yes

#926 chore: remove scope logs when no action is executed
  pkg/kcp/scope/loadScopeObj.go
  pkg/kcp/scope/logScope.go
  pkg/kcp/scope/reconciler.go
Labels: size/M, lgtm, cla: yes
