Repository kyma-project/cloud-manager, pull requests merged in 2024-04, with the labels that each got.

#165 Update CODEOWNERS
  CODEOWNERS
Labels: size/M, lgtm, cla: yes

#168 feat: KCP AWS VpcPeering create
  api/cloud-control/v1beta1/vpcpeering_types.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-control/vpcpeering_aws_test.go
  internal/controller/cloud-control/vpcpeering_controller.go
  pkg/kcp/provider/aws/mock/server.go
  pkg/kcp/provider/aws/mock/type.go
  pkg/kcp/provider/aws/vpcpeering/addFinalizer.go
  pkg/kcp/provider/aws/vpcpeering/client/client.go
  pkg/kcp/provider/aws/vpcpeering/loadVpc.go
  pkg/kcp/provider/aws/vpcpeering/new.go
  pkg/kcp/provider/aws/vpcpeering/state.go
  pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go
  pkg/kcp/vpcpeering/reconciler.go
  pkg/kcp/vpcpeering/state.go
  pkg/kcp/vpcpeering/types/state.go
  pkg/testinfra/dsl/kcpVpcPeering.go
Labels: size/XL, lgtm, cla: yes

#169 feat(AwsNfsVolume): wait for efs mount targets availability
  pkg/kcp/provider/aws/nfsinstance/new.go
  pkg/kcp/provider/aws/nfsinstance/waitMountTargetsAvailable.go
Labels: size/M, lgtm, cla: yes

#170 fix: Gcp IpRange Test
  internal/controller/cloud-control/iprange_gcp_test.go
  internal/controller/cloud-control/nfsinstance_gcp_test.go
  internal/controller/cloud-control/scope_gcp_test.go
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  pkg/testinfra/dsl.go
Labels: size/M, lgtm, cla: yes

#171 fix: let LM delete cloudresources CRD
  pkg/skr/cloudresources/deleteCrds.go
Labels: size/XS, lgtm, cla: yes

#172 feat: prevent IpRanges with length smaller then /16
  internal/controller/cloud-resources/iprange_test.go
  pkg/skr/iprange/reconciler.go
  pkg/skr/iprange/validateCidr.go
  pkg/testinfra/run.go
Labels: size/L, lgtm, cla: yes

#174 feat: AwsNfsVolumeBackup
  PROJECT
  api/cloud-resources/v1beta1/awsnfsvolumebackup_types.go
  api/cloud-resources/v1beta1/cloudresources_types.go
  api/cloud-resources/v1beta1/condition.go
  api/cloud-resources/v1beta1/state.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumebackups.yaml
  config/crd/kustomization.yaml
  config/rbac/cloud-resources_awsnfsvolumebackup_editor_role.yaml
  config/rbac/cloud-resources_awsnfsvolumebackup_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_awsnfsvolumebackup.yaml
  config/samples/kustomization.yaml
  go.mod
  go.sum
  internal/controller/cloud-resources/awsnfsvolumebackup_controller.go
  internal/controller/cloud-resources/cr/cloudresources_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/composed/updateStatus.go
  pkg/kcp/provider/aws/iprange/client/client.go
  pkg/kcp/provider/aws/nfsinstance/client/client.go
  pkg/skr/awsnfsvolumebackup/client/client.go
  pkg/skr/awsnfsvolumebackup/createAwsClient.go
  pkg/skr/awsnfsvolumebackup/loadKcpAwsNfsInstance.go
  pkg/skr/awsnfsvolumebackup/loadSkrAwsNfsVolume.go
  pkg/skr/awsnfsvolumebackup/loadVault.go
  pkg/skr/awsnfsvolumebackup/reconciler.go
  pkg/skr/awsnfsvolumebackup/state.go
  pkg/skr/awsnfsvolumebackup/stopIfVolumeNotReady.go
  pkg/skr/cloudresources/handleServed.go
  pkg/skr/cloudresources/stateReady.go
  pkg/skr/common/scope/loadScope.go
  pkg/skr/common/scope/new.go
  pkg/skr/common/scope/setStatusProcessing.go
  pkg/skr/common/scope/state.go
  pkg/skr/common/scope/waitScopeReady.go
  pkg/testinfra/crd.go
Labels: size/XXL, lgtm, cla: yes

#175 fix: choose correct vpc for IpRange
  internal/controller/cloud-control/iprange_aws_test.go
  internal/controller/cloud-control/nfsinstance_aws_test.go
  internal/controller/cloud-control/vpcpeering_aws_test.go
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  pkg/common/consts.go
  pkg/kcp/provider/aws/iprange/loadVpc.go
  pkg/kcp/provider/aws/nfsinstance/createEfs.go
  pkg/kcp/scope/skrActivate.go
  pkg/kcp/scope/skrDeactivate.go
  pkg/metrics/skrRuntime.go
  pkg/skr/runtime/looper/skrLooper.go
  pkg/testinfra/crd.go
  pkg/testinfra/dsl/ginkgo.go
  pkg/testinfra/gherkin.go
  pkg/testinfra/run.go
Labels: size/L, lgtm, cla: yes

#176 chore(AwsNfsVolume): ensure same vpc mount targets in single efs
  config/samples/cloud-resources_v1beta1_awsnfsvolume.yaml
  config/samples/cloud-resources_v1beta1_cloudresources.yaml
  config/samples/cloud-resources_v1beta1_iprange.yaml
  pkg/kcp/provider/aws/mock/vpcStore.go
  pkg/kcp/provider/aws/nfsinstance/client/client.go
  pkg/kcp/provider/aws/nfsinstance/new.go
  pkg/kcp/provider/aws/nfsinstance/removeMountTargetsFromOtherVpcs.go
Labels: size/L, lgtm, cla: yes

#179 feat: prevent SKR IpRange deletion when used by AwsNfsVolume
  .github/workflows/pr-checks.yml
  api/cloud-resources/v1beta1/awsnfsvolume_types.go
  api/cloud-resources/v1beta1/condition.go
  api/cloud-resources/v1beta1/iprange_types.go
  api/cloud-resources/v1beta1/state.go
  config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
  internal/controller/cloud-resources/iprange_controller.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/skr/awsnfsvolume/ignorant.go
  pkg/skr/iprange/preventCidrChange.go
  pkg/skr/iprange/preventDeleteOnAwsNfsVolumeUsage.go
  pkg/skr/iprange/reconciler.go
  pkg/skr/iprange/updateStatus.go
  pkg/skr/iprange/validateCidr.go
  pkg/skr/runtime/looper/runner.go
  pkg/skr/runtime/registry/indexer.go
  pkg/skr/runtime/registry/registry.go
  pkg/testinfra/crd.go
Labels: size/L, lgtm, cla: yes

#177 fix: Separate timer values for test and actual GCP provider calls
  cmd/main.go
  config/manager/kustomization.yaml
  internal/controller/cloud-control/iprange_controller.go
  internal/controller/cloud-control/nfsinstance_controller.go
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  pkg/kcp/provider/gcp/client/gcpConstants.go
  pkg/kcp/provider/gcp/iprange/checkGcpOperation.go
  pkg/kcp/provider/gcp/iprange/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/iprange/state.go
  pkg/kcp/provider/gcp/iprange/state_test.go
  pkg/kcp/provider/gcp/iprange/syncAddress.go
  pkg/kcp/provider/gcp/iprange/syncAddress_test.go
  pkg/kcp/provider/gcp/iprange/syncPsaConnection.go
  pkg/kcp/provider/gcp/iprange/syncPsaConnection_test.go
  pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
  pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance.go
  pkg/kcp/provider/gcp/nfsinstance/state.go
  pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance.go
  pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance_test.go
Labels: size/L, lgtm, cla: yes

#180 chore: sec scan config v0.1.4
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#181 chore: sec scan config 0.1.4
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#182 chore: Checkmarx Error Handling azure/nfsinstance
  pkg/kcp/provider/azure/nfsinstance/new.go
Labels: size/XS, lgtm, cla: yes

#178 feat: KCP AWS VpcPeering mock
  api/cloud-control/v1beta1/vpcpeering_types.go
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/mock/type.go
  pkg/kcp/provider/aws/mock/vpcPeeringStore.go
  pkg/kcp/provider/aws/vpcpeering/client/client.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/new.go
  pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go
  pkg/kcp/vpcpeering/reconciler.go
Labels: size/L, lgtm, cla: yes

#184 chore: reduce scope logging
  pkg/composed/predicate.go
  pkg/kcp/scope/findKymaModuleState.go
  pkg/kcp/scope/loadKyma.go
  pkg/kcp/scope/loadScopeObj.go
  pkg/skr/awsnfsvolume/updateStatus.go
  pkg/skr/runtime/looper/installer.go
  pkg/skr/runtime/looper/runner.go
  pkg/skr/runtime/looper/skrLooper.go
Labels: size/M, lgtm, cla: yes

#185 chore: sec scan 0.1.5
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#186 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm, cla: yes

#187 fix: skr installer update new CRD version
  Makefile
  config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
  config/patchAfterMakeManifests.sh
  pkg/skr/runtime/looper/installer.go
Labels: size/XL, lgtm, cla: yes

#189 fix: skr installer update new CRD version
  pkg/skr/runtime/looper/installer.go
Labels: size/S, lgtm, cla: yes

#190 fix: skr installer update new CRD version
  pkg/skr/runtime/looper/installer.go
Labels: size/XS, lgtm, cla: yes

#191 fix: skr installer update new CRD version
  pkg/skr/runtime/looper/installer.go
Labels: size/XS, lgtm, cla: yes

#192 chore: security scanner 0.1.6
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#183 GcpNfsVolumeBackup POC
  PROJECT
  api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/crd/kustomization.yaml
  config/rbac/cloud-resources_gcpnfsvolumebackup_editor_role.yaml
  config/rbac/cloud-resources_gcpnfsvolumebackup_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_gcpnfsvolumebackup.yaml
  config/samples/kustomization.yaml
  internal/controller/cloud-resources/gcpnfsvolumebackup_controller.go
  pkg/kcp/provider/gcp/client/gcpConstants.go
  pkg/kcp/provider/gcp/nfsbackup/client/fileBackupClient.go
Labels: size/XL, lgtm, cla: yes

#188 fix: cli is not picking the env variable value
  cmd/cli/helper/k8s.go
Labels: size/S, lgtm, cla: yes

#194 fix: SKR IpRange prevent CIDR overlap
  api/cloud-resources/v1beta1/iprange_types.go
  internal/controller/cloud-resources/awsnfsvolume_test.go
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/skr/awsnfsvolume/updateStatus.go
  pkg/skr/iprange/preventCidrOverlap.go
  pkg/skr/iprange/reconciler.go
  pkg/skr/iprange/validateCidr.go
Labels: size/L, lgtm, cla: yes

#193 fix: AWS VpcPeering propagate roleName
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/state.go
Labels: size/M, lgtm, cla: yes

#197 fix: empty gcpnfsbackup factory
  cmd/main.go
  internal/controller/cloud-resources/gcpnfsvolumebackup_controller.go
Labels: size/S, lgtm, cla: yes

#195 GcpNfsVolumeBackup POC
  cmd/main.go
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/sync.sh
  internal/controller/cloud-resources/gcpnfsvolumebackup_controller.go
  pkg/kcp/provider/gcp/iprange/checkGcpOperation.go
  pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
  pkg/skr/gcpnfsvolumebackup/addFinalizer.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadNfsInstance.go
  pkg/skr/gcpnfsvolumebackup/loadScope.go
  pkg/skr/gcpnfsvolumebackup/reconciler.go
  pkg/skr/gcpnfsvolumebackup/removeFinalizer.go
  pkg/skr/gcpnfsvolumebackup/state.go
  pkg/skr/gcpnfsvolumebackup/updateStatus.go
Labels: size/XL, lgtm, cla: yes

#198 fix: Not starting GcpNfsVolumeBackup controller
  cmd/main.go
Labels: size/XS, lgtm, cla: yes

#200 Aws vpc peering create connection
  pkg/kcp/provider/aws/vpcpeering/client/client.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/state.go
  pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go
Labels: size/M, lgtm, cla: yes

#201 chore: config
  CODEOWNERS
  go.mod
  go.sum
  pkg/common/abstractions/environment.go
  pkg/config/README.md
  pkg/config/binding.go
  pkg/config/config.go
  pkg/config/config_bind_test.go
  pkg/config/config_raw_test.go
  pkg/config/config_watch_test.go
  pkg/config/fieldPath.go
  pkg/config/fieldPath_test.go
  pkg/config/sourceEnv.go
  pkg/config/sourceFile.go
  pkg/config/testdata/file-v1.yaml
  pkg/config/testdata/file-v2.yaml
  pkg/config/testdata/first.json
  pkg/config/testdata/first.yaml
  pkg/config/testdata/resourceQuotaDefault.json
  pkg/config/testdata/resourceQuotaDefault.yaml
  pkg/config/testdata/resourceQuotaOverride.json
  pkg/config/testdata/resourceQuotaOverride.yaml
  pkg/config/testdata/scalar
  pkg/config/types.go
  pkg/config/util_test.go
  pkg/config/watchedState.go
Labels: size/XXL, lgtm, cla: yes

#203 feat: SKR IpRange totalCount quota
  api/cloud-resources/v1beta1/condition.go
  internal/controller/cloud-resources/suite_test.go
  pkg/common/abstractions/environment.go
  pkg/config/config.go
  pkg/config/config_default_test.go
  pkg/config/pathBuilder.go
  pkg/config/types.go
  pkg/quota/skrConfig_test.go
  pkg/quota/skrQuota.go
  pkg/quota/testdata/skrQuotaConfig.yaml
  pkg/skr/iprange/checkQuota.go
  pkg/skr/iprange/reconciler.go
  pkg/testinfra/dsl/conditions.go
  pkg/util/maxint.go
Labels: size/L, lgtm, cla: yes

#204 feat: GcpNfsVolumeRestore
  PROJECT
  api/cloud-resources/v1beta1/condition.go
  api/cloud-resources/v1beta1/gcpnfsvolumerestore_types.go
  api/cloud-resources/v1beta1/state.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  config/crd/kustomization.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  config/rbac/cloud-resources_gcpnfsvolumerestore_editor_role.yaml
  config/rbac/cloud-resources_gcpnfsvolumerestore_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_gcpnfsvolumerestore.yaml
  config/samples/kustomization.yaml
  config/sync.sh
  internal/controller/cloud-resources/gcpnfsvolumerestore_controller.go
  pkg/kcp/provider/gcp/nfsrestore/client/fileRestoreClient.go
  pkg/skr/gcpnfsvolumerestore/addFinalizer.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolumerestore/loadScope.go
  pkg/skr/gcpnfsvolumerestore/reconciler.go
  pkg/skr/gcpnfsvolumerestore/removeFinalizer.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
  pkg/skr/gcpnfsvolumerestore/state.go
Labels: size/XXL, lgtm, cla: yes

#202 feat: AWS VpcPeering accept vpc peering connection
  api/cloud-control/v1beta1/vpcpeering_types.go
  pkg/kcp/provider/aws/mock/vpcPeeringStore.go
  pkg/kcp/provider/aws/vpcpeering/acceptVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/client/client.go
  pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/new.go
Labels: size/L, lgtm, cla: yes

#205 fix: GcpNfsVolumeBackup - removed NfsInstance from reconciliation
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadNfsInstance.go
  pkg/skr/gcpnfsvolumebackup/reconciler.go
  pkg/skr/gcpnfsvolumebackup/state.go
Labels: size/M, lgtm, cla: yes

#208 chore: use config files
  cmd/main.go
  config/config/scope.yaml
  config/config/skrResourceQuota.yaml
  config/config/skrRuntime.yaml
  internal/controller/cloud-control/iprange_controller.go
  internal/controller/cloud-control/nfsinstance_controller.go
  internal/controller/cloud-control/vpcpeering_controller.go
  pkg/config/binding.go
  pkg/config/config.go
  pkg/config/config_bind_test.go
  pkg/config/config_default_test.go
  pkg/config/config_raw_test.go
  pkg/config/config_watch_test.go
  pkg/config/fieldPath.go
  pkg/config/fieldPath_test.go
  pkg/config/pathBuilder.go
  pkg/config/sourceEnv.go
  pkg/config/sourceFile.go
  pkg/config/types.go
  pkg/kcp/provider/aws/config/config.go
  pkg/kcp/provider/aws/config/config_test.go
  pkg/kcp/provider/aws/iprange/state.go
  pkg/kcp/provider/aws/nfsinstance/state.go
  pkg/kcp/provider/aws/vpcpeering/state.go
  pkg/kcp/scope/config.go
  pkg/kcp/scope/config_test.go
  pkg/kcp/scope/createGardenerClient.go
  pkg/quota/skrQuota.go
  pkg/quota/skrQuota_test.go
  pkg/skr/awsnfsvolumebackup/createAwsClient.go
  pkg/skr/runtime/config/config.go
  pkg/skr/runtime/config/config_test.go
  pkg/skr/runtime/looper/runner.go
  pkg/testinfra/dsl.go
  pkg/testinfra/env.go
  pkg/testinfra/run.go
  pkg/testinfra/types.go
Labels: size/XL, lgtm, cla: yes

#209 chore: sec scan rc 0.1.7
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#206 feat: GcpNfsVolume UI First Pass
  config/ui-extensions/awsnfsvolumes/details
  config/ui-extensions/awsnfsvolumes/form
  config/ui-extensions/awsnfsvolumes/general
  config/ui-extensions/awsnfsvolumes/kustomization.yaml
  config/ui-extensions/awsnfsvolumes/list
  config/ui-extensions/awsnfsvolumes/translations
  config/ui-extensions/cloudresources/details
  config/ui-extensions/cloudresources/form
  config/ui-extensions/cloudresources/general
  config/ui-extensions/cloudresources/kustomization.yaml
  config/ui-extensions/cloudresources/list
  config/ui-extensions/cloudresources/translations
  config/ui-extensions/gcpnfsvolumes/details
  config/ui-extensions/gcpnfsvolumes/form
  config/ui-extensions/gcpnfsvolumes/general
  config/ui-extensions/gcpnfsvolumes/kustomization.yaml
  config/ui-extensions/gcpnfsvolumes/list
  config/ui-extensions/gcpnfsvolumes/translations
  config/ui-extensions/ipranges/details
  config/ui-extensions/ipranges/form
  config/ui-extensions/ipranges/general
  config/ui-extensions/ipranges/kustomization.yaml
  config/ui-extensions/ipranges/list
  config/ui-extensions/ipranges/translations
  config/ui-extensions/kustomization.yaml
  config/ui-extensions/nfsshares/details
  config/ui-extensions/nfsshares/form
  config/ui-extensions/nfsshares/general
  config/ui-extensions/nfsshares/kustomization.yaml
  config/ui-extensions/nfsshares/list
  config/ui-extensions/nfsshares/translations
  config/ui-extensions/scopes/details
  config/ui-extensions/scopes/form
  config/ui-extensions/scopes/general
  config/ui-extensions/scopes/kustomization.yaml
  config/ui-extensions/scopes/list
  config/ui-extensions/scopes/translations
  config/ui-extensions/vpcpeerings/details
  config/ui-extensions/vpcpeerings/form
  config/ui-extensions/vpcpeerings/general
  config/ui-extensions/vpcpeerings/kustomization.yaml
  config/ui-extensions/vpcpeerings/list
  config/ui-extensions/vpcpeerings/translations
Labels: size/L, lgtm, cla: yes

#211 fix: SetExclusiveConditions to remove all conditions before setting n…
  pkg/composed/updateStatus.go
Labels: size/XS, lgtm, cla: yes

#214 fix: iprange cidr overlap can be removed
  pkg/skr/iprange/preventCidrOverlap.go
  pkg/skr/iprange/reconciler.go
  pkg/skr/iprange/removeOverlapCondition.go
Labels: size/M, lgtm, cla: yes

#215 fix: quota allow older resources, put error on newer
  pkg/skr/iprange/checkQuota.go
Labels: size/XS, lgtm, cla: yes

#212 feat: PV Spec for GcpNfsVolume
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  pkg/skr/gcpnfsvolume/createPersistenceVolume.go
  pkg/skr/gcpnfsvolume/createPersistenceVolume_test.go
  pkg/skr/gcpnfsvolume/deletePVForNameChange.go
  pkg/skr/gcpnfsvolume/modifyPersistenceVolume.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/removePersistenceVolumeFinalizer.go
  pkg/skr/gcpnfsvolume/util.go
  pkg/skr/gcpnfsvolume/validatePV.go
  pkg/testinfra/dsl/gcpNfsVolume.go
Labels: size/XL, lgtm, cla: yes

#217 fix: SKR IpRange quota
  api/cloud-resources/v1beta1/condition.go
  internal/controller/cloud-resources/cr/doc.go
  internal/controller/cloud-resources/quotaIpRange/doc.go
  internal/controller/cloud-resources/quotaIpRange/quotaIpRange_test.go
  internal/controller/cloud-resources/quotaIpRange/suite_test.go
  pkg/common/ignorant/store.go
  pkg/skr/iprange/checkQuota.go
  pkg/skr/iprange/preventCidrChange.go
  pkg/skr/iprange/validateCidr.go
  pkg/testinfra/infra.go
Labels: size/L, lgtm, cla: yes

#218 chore: sec-scan-0.1.8
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#216 feat: added gcpnfsvolumes ui ConfigMap to provider location
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
Labels: size/M, lgtm, cla: yes
