Repository kyma-project/cloud-manager, pull requests merged in 2024-08, with the labels that each got.

#410 test: GcpNfsVolume optional location tests
  config/featureToggles/featureToggles.yaml
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  pkg/skr/gcpnfsvolume/loadScope_test.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance_test.go
  pkg/skr/gcpnfsvolume/state_test.go
  pkg/testinfra/dsl.go
  pkg/testinfra/dsl/gcpNfsVolume.go
Labels: size/XL, lgtm, cla: yes

#392 feat(AwsRedisInstance): add API to specify parameters
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-resources/awsredisinstance_test.go
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/mock/server.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createParameterGroup.go
  pkg/kcp/provider/aws/redisinstance/deleteParameterGroup.go
  pkg/kcp/provider/aws/redisinstance/loadParameterGroup.go
  pkg/kcp/provider/aws/redisinstance/modifyParameterGroup.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/kcp/provider/aws/redisinstance/util.go
  pkg/skr/awsredisinstance/createKcpRedisInstance.go
  pkg/skr/awsredisinstance/modifyKcpRedisInstance.go
  pkg/skr/awsredisinstance/reconciler.go
  pkg/skr/awsredisinstance/util.go
  pkg/testinfra/dsl/awsRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/XL, lgtm, cla: yes

#403 (feat) AWS VPC Peering UI
  Makefile
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/sync.sh
  config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/details
  config/ui-extensions/awsvpcpeerings/form
  config/ui-extensions/awsvpcpeerings/general
  config/ui-extensions/awsvpcpeerings/kustomization.yaml
  config/ui-extensions/awsvpcpeerings/list
  config/ui-extensions/awsvpcpeerings/translations
Labels: size/L, lgtm, cla: yes

#404 feat (AwsVpcPeering): loads remote VpcPeering
  pkg/kcp/provider/aws/vpcpeering/acceptVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/loadVpc.go
  pkg/kcp/provider/aws/vpcpeering/new.go
  pkg/kcp/provider/aws/vpcpeering/state.go
  pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go
Labels: size/L, lgtm, cla: yes

#412 feat (AzureVpcPeering): allows user to specify remotePeeringName
  api/cloud-control/v1beta1/vpcpeering_types.go
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/skr/azurevpcpeering/createKpcVpcPeering.go
  pkg/testinfra/dsl/kcpVpcPeering.go
Labels: size/M, lgtm, cla: yes

#413 fix(AwsRedisInstance): pass param group name when creating cache
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
Labels: size/XS, lgtm, cla: yes

#414 feat (AzureVpcPeering): adds XValidation rules to RemotePeeringName
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/patchAfterMakeManifests.sh
Labels: size/L, lgtm, cla: yes

#416 refactor(GcpRedisInstance): make redisConfigs map[string]string
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-control/redisinstance_gcp_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/gcpRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#419 (feat) GCP NFS Backup Schedules UI
  Makefile
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/sync.sh
  config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/gcpnfsbackupschedules/details
  config/ui-extensions/gcpnfsbackupschedules/form
  config/ui-extensions/gcpnfsbackupschedules/general
  config/ui-extensions/gcpnfsbackupschedules/kustomization.yaml
  config/ui-extensions/gcpnfsbackupschedules/list
  config/ui-extensions/gcpnfsbackupschedules/translations
Labels: size/XL, lgtm, cla: yes

#420 (bugFix) removed all fields from nfsVolumeRef except name and namespace
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/gcpnfsbackupschedules/form
Labels: size/M, lgtm, cla: yes

#415 AWSRedisInstance & AzureVPCPeering UI Update
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/details
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsredisinstances/translations
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/details
  config/ui-extensions/azurevpcpeerings/form
  config/ui-extensions/azurevpcpeerings/translations
Labels: size/M, lgtm, cla: yes

#323 feat(GCPVpcPeering) Delete VPC Peering
  api/cloud-control/v1beta1/vpcpeering_types.go
  api/cloud-resources/v1beta1/gcpvpcpeering_types.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/samples/cloud-resources_v1beta1_gcpvpcpeering.yaml
  config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/gcpvpcpeerings/details
  config/ui-extensions/gcpvpcpeerings/form
  config/ui-extensions/gcpvpcpeerings/list
  config/ui-extensions/gcpvpcpeerings/translations
  internal/controller/cloud-control/vpcpeering_controller.go
  internal/controller/cloud-control/vpcpeering_gcp_test.go
  pkg/kcp/provider/gcp/mock/server.go
  pkg/kcp/provider/gcp/mock/type.go
  pkg/kcp/provider/gcp/mock/vpcPeeringStore.go
  pkg/kcp/provider/gcp/vpcpeering/addFinalizer.go
  pkg/kcp/provider/gcp/vpcpeering/client/cloudComputeClient.go
  pkg/kcp/provider/gcp/vpcpeering/client/vpcPeeringClient.go
  pkg/kcp/provider/gcp/vpcpeering/createKymaVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/gcp/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/loadKymaVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/loadRemoteVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/new.go
  pkg/kcp/provider/gcp/vpcpeering/removeReadyCondition.go
  pkg/kcp/provider/gcp/vpcpeering/state.go
  pkg/kcp/provider/gcp/vpcpeering/updateStatus.go
  pkg/kcp/provider/gcp/vpcpeering/waitKymaVpcPeeringDeletion.go
  pkg/kcp/provider/gcp/vpcpeering/waitRemoteVpcPeeringAvailable.go
  pkg/kcp/provider/gcp/vpcpeering/waitVpcPeeringActive.go
  pkg/skr/gcpvpcpeering/createKcpVpcPeering.go
  pkg/skr/gcpvpcpeering/deleteKcpVpcPeering.go
  pkg/skr/gcpvpcpeering/reconciler.go
  pkg/skr/gcpvpcpeering/removeFinalizer.go
  pkg/skr/gcpvpcpeering/updateStatus.go
  pkg/skr/gcpvpcpeering/waitKcpStatusUpdate.go
  pkg/skr/gcpvpcpeering/waitSkrStatusReady.go
  pkg/testinfra/dsl/kcpVpcPeering.go
  tools/demo/gcpvpcpeering/kcp-gcp-vpcpeering.yaml
  tools/demo/gcpvpcpeering/skr-gcp-vpcpeering.yaml
Labels: size/XXL, lgtm, cla: yes

#421 (bugFix) updated GCP Redis Instance UI
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/details
  config/ui-extensions/gcpredisinstances/form
Labels: size/L, lgtm, cla: yes

#443 feat(RedisInstance,GcpRedisInstance): put CaCert.pem in auth secret
  api/cloud-control/v1beta1/redisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  pkg/kcp/provider/gcp/redisinstance/updateStatus.go
  pkg/skr/gcpredisinstance/util.go
Labels: size/S, lgtm, cla: yes

#409 feat(AzureRedisInstance): SKR implementation
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/rbac/cloud-resources_azureredisinstance_editor_role.yaml
  config/rbac/cloud-resources_azureredisinstance_viewer_role.yaml
  config/rbac/role.yaml
  config/sync.sh
  internal/controller/cloud-resources/azureredisinstance_controller.go
  internal/controller/cloud-resources/azureredisinstance_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/redisinstance/common/loadIpRange.go
  pkg/kcp/redisinstance/reconciler.go
  pkg/skr/azureredisinstance/createAuthSecret.go
  pkg/skr/azureredisinstance/createKcpRedisInstance.go
  pkg/skr/azureredisinstance/deleteAuthSecret.go
  pkg/skr/azureredisinstance/deleteKcpRedisInstance.go
  pkg/skr/azureredisinstance/loadAuthSecret.go
  pkg/skr/azureredisinstance/loadKcpRedisInstance.go
  pkg/skr/azureredisinstance/reconciler.go
  pkg/skr/azureredisinstance/removeAuthSecretFinalizer.go
  pkg/skr/azureredisinstance/state.go
  pkg/skr/azureredisinstance/updateId.go
  pkg/skr/azureredisinstance/updateStatus.go
  pkg/skr/azureredisinstance/util.go
  pkg/skr/azureredisinstance/waitAuthSecretDeleted.go
  pkg/skr/azureredisinstance/waitKcpRedisInstanceDeleted.go
  pkg/skr/azureredisinstance/waitKcpStatusUpdate.go
  pkg/skr/azureredisinstance/waitSkrStatusReady.go
  pkg/testinfra/dsl/azureRedisInstance.go
  pkg/testinfra/dsl/loadAndCheck.go
Labels: size/XXL, lgtm, cla: yes

#442 feat(GCPVpcPeering) Changing the kyma network peering to be cm-{metadata.name}
  pkg/kcp/provider/gcp/mock/vpcPeeringStore.go
  pkg/kcp/provider/gcp/vpcpeering/client/vpcPeeringClient.go
  pkg/kcp/provider/gcp/vpcpeering/createKymaVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/loadKymaVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/state.go
Labels: size/M, lgtm, cla: yes

#444 feat(GcpRedisInstance): add support for maintenance policy
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  go.mod
  internal/controller/cloud-control/redisinstance_gcp_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/client/util.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/skr/gcpredisinstance/util.go
  pkg/testinfra/dsl/gcpRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#450 feat(GcpRedisInstance): add labels to gcp redis instance
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/util/labels.go
  pkg/util/labels_test.go
Labels: size/M, lgtm, cla: yes

#423 (fix) build failure in linux with go1.22.x
  Makefile
  config/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
  config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumebackups.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_cloudresources.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/skr/crd/bases/cloud-resources.kyma-project.io_cloudresources.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
Labels: size/XXL, lgtm, cla: yes

#457 refactor(GcpRedisInstance): refactor maintenance policy and transit e…
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  config/samples/cloud-resources_v1beta1_gcpredisinstance.yaml
  internal/controller/cloud-control/redisinstance_gcp_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/client/util.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/skr/gcpredisinstance/util.go
  pkg/testinfra/dsl/gcpRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/XL, lgtm, cla: yes

#417 feat (AzureVpcPeering): defaults allowVnetAccess to true
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
Labels: size/XS, lgtm, cla: yes

#461 feat(GcpNfsVolume) Support restore when creating a new FileStore
  api/cloud-control/v1beta1/nfsinstance_gcp_types.go
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  internal/controller/cloud-control/nfsinstance_gcp_test.go
  pkg/kcp/provider/gcp/nfsinstance/state.go
  pkg/skr/gcpnfsvolume/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolume/loadGcpNfsVolumeBackup_test.go
  pkg/skr/gcpnfsvolume/loadScope.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/state.go
  pkg/skr/gcpnfsvolume/state_test.go
  pkg/testinfra/dsl.go
  pkg/testinfra/dsl/nfsInstance.go
Labels: size/L, lgtm, cla: yes

#470 (feat) added sourceBackup for gcpnfsvolumes UI
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/details
  config/ui-extensions/gcpnfsvolumes/form
  config/ui-extensions/gcpnfsvolumes/translations
Labels: size/M, lgtm, cla: yes

#459 (feat) added maintenancePolicy for gcpredisinstance
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/details
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpredisinstances/translations
Labels: size/L, lgtm, cla: yes

#473 feat(AwsRedisInstance): add in-transit encryption toggle
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
  config/samples/cloud-resources_v1beta1_awsredisinstance.yaml
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-resources/awsredisinstance_test.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/mock/server.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/deleteElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/loadElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/kcp/provider/aws/redisinstance/updateStatus.go
  pkg/kcp/provider/aws/redisinstance/updateStatusId.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
  pkg/skr/awsredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/awsRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#476 feat(AwsRedisInstance): add option to define maintenance policy
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
  config/samples/cloud-resources_v1beta1_awsredisinstance.yaml
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-resources/awsredisinstance_test.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/skr/awsredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/awsRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#471 (feat) removed simple: true from all forms
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/ui-extensions/awsnfsvolumes/form
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/form
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/form
  config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/gcpnfsbackupschedules/form
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/form
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/form
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/form
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpredisinstances/translations
  config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/gcpvpcpeerings/form
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/ipranges/form
Labels: size/L, lgtm, cla: yes

#468 feat: AzureRedisInstance UI
  Makefile
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/sync.sh
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/details
  config/ui-extensions/azureredisinstances/form
  config/ui-extensions/azureredisinstances/general
  config/ui-extensions/azureredisinstances/kustomization.yaml
  config/ui-extensions/azureredisinstances/list
  config/ui-extensions/azureredisinstances/translations
Labels: size/XL, lgtm, cla: yes

#479 chore: log on config reload
  .github/workflows/pr-golang-lint.yml
  cmd/main.go
Labels: size/XS, lgtm, cla: yes

#477 (feat) added preferredMaintenanceWindow and transitEncryptionEnabled
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/details
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsredisinstances/translations
Labels: size/M, lgtm, cla: yes

#465 feat(GCPVpcPeering) Short shootName on peering challenge
  api/cloud-resources/v1beta1/gcpvpcpeering_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  pkg/kcp/provider/gcp/vpcpeering/client/vpcPeeringClient.go
  pkg/kcp/provider/gcp/vpcpeering/createKymaVpcPeering.go
  pkg/kcp/provider/gcp/vpcpeering/state.go
  pkg/skr/gcpvpcpeering/createKcpVpcPeering.go
  pkg/skr/gcpvpcpeering/loadKcpGcpVpcPeering.go
Labels: size/M, lgtm, cla: yes

#482 feat(GCPVpcPeering) Deleting unnecessary files
  pkg/skr/gcpvpcpeering/addFinalizer.go
  pkg/skr/gcpvpcpeering/removeFinalizer.go
Labels: size/M, lgtm, cla: yes

#489 fix(GcpNfsVolumeBackup): Fix for GCP Filestore backup naming
  api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/state_test.go
  pkg/skr/gcpnfsvolumerestore/addFinalizer.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
  pkg/skr/gcpnfsvolumerestore/state_test.go
Labels: size/L, lgtm, cla: yes

#478 Peering/azure/credentials
  pkg/kcp/provider/azure/config/config.go
  pkg/kcp/provider/azure/redisinstance/state.go
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/state.go
Labels: size/M, lgtm, cla: yes

#481 feat(AwsRedisInstance): add option to enable auth token
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
  go.mod
  go.sum
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-resources/awsredisinstance_test.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/mock/server.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createAuthTokenSecret.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/deleteAuthTokenSecret.go
  pkg/kcp/provider/aws/redisinstance/loadAuthTokenSecret.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/kcp/provider/aws/redisinstance/updateStatus.go
  pkg/kcp/provider/aws/redisinstance/util.go
  pkg/skr/awsredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/awsRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#458 feat(GCPVpcPeering) Adding documentation and tutorial for the feature
  docs/user/00-10-glossary.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/04-50-gcp-vpc-peering.md
  docs/user/resources/README.md
  docs/user/tutorials/01-30-gcp-vpc-peering.md
  docs/user/tutorials/README.md
Labels: size/L, lgtm, cla: yes

#493 feat(AwsVpcPeering): peering credentials
  pkg/kcp/provider/aws/config/config.go
  pkg/kcp/provider/aws/config/config_test.go
  pkg/kcp/provider/aws/iprange/v1/state.go
  pkg/kcp/provider/aws/iprange/v2/state.go
  pkg/kcp/provider/aws/nfsinstance/state.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/kcp/provider/aws/vpcpeering/state.go
  pkg/skr/awsnfsvolumebackup/createAwsClient.go
Labels: size/M, lgtm, cla: yes

#495 fix(GcpNfsVolume): Fix for blocking legacy filestore tiers
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/skr/gcpnfsvolume/validateSpec_test.go
Labels: size/L, lgtm, cla: yes

#496 fix: Updating the versions of SKR CRDs so they get patched
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/patchAfterMakeManifests.sh
Labels: size/XXL, lgtm, cla: yes

#500 feat(GcpRedisInstance): make RedisConfigs and MemorySizeGb mutable
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  go.mod
  pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/kcp/provider/gcp/redisinstance/modifyMemorySizeGb.go
  pkg/kcp/provider/gcp/redisinstance/modifyRedisConfigs.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/state.go
  pkg/kcp/provider/gcp/redisinstance/updateRedis.go
  pkg/kcp/provider/gcp/redisinstance/util.go
  pkg/skr/gcpredisinstance/modifyKcpRedisInstance.go
  pkg/skr/gcpredisinstance/reconciler.go
  pkg/skr/gcpredisinstance/state.go
  pkg/skr/gcpredisinstance/util.go
Labels: size/L, lgtm, cla: yes

#503 chore: lint pkg/kcp/provider/aws/redisinstance/util.go
  pkg/kcp/provider/aws/redisinstance/util.go
Labels: size/XS, lgtm, cla: yes

#508 feat(GcpRedisInstance): make maintenance policy mutable
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
  pkg/kcp/provider/gcp/redisinstance/modifyMaintenancePolicy.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/state.go
  pkg/kcp/provider/gcp/redisinstance/util.go
  pkg/skr/gcpredisinstance/modifyKcpRedisInstance.go
  pkg/skr/gcpredisinstance/state.go
Labels: size/L, lgtm, cla: yes

#494 feat(AzureRedisInstance): mutable SKU
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-resources/azureredisinstance_test.go
  pkg/kcp/provider/azure/mock/redisCacheClientFake.go
  pkg/kcp/provider/azure/redisinstance/client/client.go
  pkg/kcp/provider/azure/redisinstance/modifyRedis.go
  pkg/kcp/provider/azure/redisinstance/new.go
  pkg/kcp/provider/azure/redisinstance/updateStatus.go
  pkg/kcp/provider/azure/redisinstance/updateStatusId.go
  pkg/skr/azureredisinstance/modifyKcpRedisInstance.go
  pkg/skr/azureredisinstance/reconciler.go
  pkg/testinfra/dsl/azureRedisInstance.go
Labels: size/XXL, lgtm, cla: yes

#506 fix: linter error for using jws package
  go.mod
  pkg/kcp/provider/gcp/client/provider.go
Labels: size/L, lgtm, cla: yes

#518 feat(GcpNfsVolumeBackup): make location optional
  api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-resources/gcpnfsvolumebackup_test.go
  pkg/skr/backupschedule/backupImpl.go
  pkg/skr/backupschedule/calculateOnetimeSchedule_test.go
  pkg/skr/backupschedule/createBackup_test.go
  pkg/skr/backupschedule/evaluateNextRun.go
  pkg/skr/backupschedule/state_test.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance_test.go
  pkg/skr/gcpnfsvolume/state_test.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/reconciler.go
  pkg/skr/gcpnfsvolumebackup/state_test.go
  pkg/skr/gcpnfsvolumebackup/validateSpec.go
  pkg/skr/gcpnfsvolumebackup/validateSpec_test.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore_test.go
  pkg/skr/gcpnfsvolumerestore/state_test.go
  pkg/skr/runtime/looper/cyclicQueue_smoke_test.go
  pkg/testinfra/dsl/gcpNfsVolumeBackup.go
Labels: size/XL, lgtm, cla: yes

#520 feat(GcpRedisInstance): make authEnabled mutable
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
  pkg/kcp/provider/gcp/redisinstance/modifyAuthEnabled.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/state.go
  pkg/kcp/provider/gcp/redisinstance/updateStatus.go
  pkg/skr/gcpredisinstance/modifyAuthSecret.go
  pkg/skr/gcpredisinstance/modifyKcpRedisInstance.go
  pkg/skr/gcpredisinstance/reconciler.go
  pkg/skr/gcpredisinstance/state.go
  pkg/skr/gcpredisinstance/util.go
Labels: size/L, lgtm, cla: yes

#504 (feat) disableOnEdit on immutable fields
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/form
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/form
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/form
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/form
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/form
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/translations
  config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/gcpvpcpeerings/form
Labels: size/L, lgtm, cla: yes

#522 (feat) UI Parity 20240822
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/details
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsredisinstances/translations
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/form
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/details
  config/ui-extensions/gcpnfsvolumebackups/form
  config/ui-extensions/gcpnfsvolumebackups/translations
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/form
Labels: size/L, lgtm, cla: yes

#532 feat(NfsInstance): KCP NfsInstance change size
  api/cloud-control/v1beta1/nfsinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  internal/controller/cloud-control/nfsinstance_ccee_test.go
  pkg/kcp/nfsinstance/copyStatusHostsToHost.go
  pkg/kcp/nfsinstance/reconciler.go
  pkg/kcp/provider/aws/nfsinstance/updateStatus.go
  pkg/kcp/provider/ccee/client/config.go
  pkg/kcp/provider/ccee/client/provider.go
  pkg/kcp/provider/ccee/config/config.go
  pkg/kcp/provider/ccee/config/config_test.go
  pkg/kcp/provider/ccee/gardener/infrastructure.go
  pkg/kcp/provider/ccee/meta/metadata.go
  pkg/kcp/provider/ccee/mock/nfsStore.go
  pkg/kcp/provider/ccee/nfsinstance/accessLoad.go
  pkg/kcp/provider/ccee/nfsinstance/client/client.go
  pkg/kcp/provider/ccee/nfsinstance/new.go
  pkg/kcp/provider/ccee/nfsinstance/shareCreate.go
  pkg/kcp/provider/ccee/nfsinstance/shareExpandShrink.go
  pkg/kcp/provider/ccee/nfsinstance/shareNetworkDelete.go
  pkg/kcp/provider/ccee/nfsinstance/shareUpdateStatusCapacity.go
  pkg/kcp/provider/ccee/nfsinstance/state.go
  pkg/kcp/provider/ccee/nfsinstance/statusDeleting.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
  pkg/testinfra/dsl/gcpNfsVolume.go
  pkg/testinfra/dsl/nfsInstance.go
  tools/dev/README.md
  tools/dev/kind/create-all-in-one.sh
  tools/dev/kind/kind-all-in-one-config.yaml
Labels: size/XL, lgtm, cla: yes

#525 feat(GcpRedisInstance, AwsRedisInstance): add host and port to auth s…
  pkg/kcp/provider/gcp/vpcpeering/new.go
  pkg/skr/awsredisinstance/util.go
  pkg/skr/azureredisinstance/util.go
  pkg/skr/gcpredisinstance/util.go
Labels: size/M, lgtm, cla: yes

#533 chore: cholang-lint-ci mandatory
  .github/workflows/pr-golang-lint.yml
  pkg/kcp/provider/azure/mock/server.go
  pkg/skr/backupschedule/calculateOnetimeSchedule_test.go
  pkg/skr/backupschedule/loadScope_test.go
  pkg/skr/backupschedule/removeFinalizer_test.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore_test.go
Labels: size/XS, lgtm, cla: yes

#534 feat: adding reasonable timeout to GCP API calls for google-api-go-cl…
  config/manager/kustomization.yaml
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/kcp/provider/gcp/client/gcpConstants.go
  pkg/kcp/provider/gcp/client/provider.go
  pkg/kcp/provider/gcp/cloudclient/provider.go
  pkg/kcp/provider/gcp/iprange/v1/state_test.go
  pkg/kcp/provider/gcp/iprange/v2/state_test.go
Labels: size/M, lgtm, cla: yes

#540 (feat) UI switch disable on edit
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/form
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/gcpvpcpeerings/form
Labels: size/M, lgtm, cla: yes

#541 feat(CceeNfsVolume): initial CRD and boilerplate
  PROJECT
  api/cloud-resources/v1beta1/cceenfsvolume_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_cceenfsvolumes.yaml
  config/crd/kustomization.yaml
  config/rbac/cloud-resources_cceenfsvolume_editor_role.yaml
  config/rbac/cloud-resources_cceenfsvolume_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_cceenfsvolume.yaml
  config/samples/kustomization.yaml
  internal/controller/cloud-resources/awsnfsvolume_test.go
  internal/controller/cloud-resources/cceenfsvolume_controller.go
  internal/controller/cloud-resources/cceenfsvolume_controller_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/skr/cceenfsvolume/reconciler.go
  pkg/skr/cceenfsvolume/state.go
Labels: size/XL, lgtm, cla: yes

#544 feat(IpRange): forbid IpRange delete if RedisInstance is using it
  internal/controller/cloud-resources/iprange_controller.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/skr/awsredisinstance/ignorant.go
  pkg/skr/gcpredisinstance/ignorant.go
  pkg/skr/iprange/preventDeleteOnAwsRedisInstanceUsage.go
  pkg/skr/iprange/preventDeleteOnGcpRedisInstanceUsage.go
  pkg/skr/iprange/reconciler.go
Labels: size/XL, lgtm, cla: yes

#523 docs(GcpRedisInstance): add resource docs
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/04-60-gcp-redis-instance.md
  docs/user/resources/README.md
  docs/user/tutorials/01-60-gcp-redis-instance.md
  docs/user/tutorials/README.md
Labels: size/L, lgtm, cla: yes

#547 fix(AwsNfsVolumeBackup): Idempotent create request
  api/cloud-resources/v1beta1/awsnfsvolumebackup_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumebackups.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumebackups.yaml
  config/patchAfterMakeManifests.sh
  pkg/skr/awsnfsvolumebackup/createAwsBackup.go
  pkg/skr/awsnfsvolumebackup/reconciler.go
  pkg/skr/awsnfsvolumebackup/setIdempotencyToken.go
  pkg/skr/awsnfsvolumebackup/setIdempotencyToken_test.go
Labels: size/XL, lgtm, cla: yes

#553 (feat) AWS NFS Volume Backup UI
  Makefile
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
  config/sync.sh
  config/ui-extensions/awsnfsvolumebackups/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
  config/ui-extensions/awsnfsvolumebackups/details
  config/ui-extensions/awsnfsvolumebackups/form
  config/ui-extensions/awsnfsvolumebackups/general
  config/ui-extensions/awsnfsvolumebackups/kustomization.yaml
  config/ui-extensions/awsnfsvolumebackups/list
  config/ui-extensions/awsnfsvolumebackups/translations
Labels: size/L, lgtm, cla: yes
