Repository kyma-project/cloud-manager, pull requests merged in 2024-07, with the labels that each got.

#307 feat (AwsVpcPeering): network tag challenge
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/mock/vpcPeeringStore.go
  pkg/kcp/provider/aws/vpcpeering/acceptVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
  pkg/kcp/provider/aws/vpcpeering/client/client.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/new.go
  pkg/kcp/provider/aws/vpcpeering/removeFinalizer.go
  pkg/kcp/provider/aws/vpcpeering/removeReadyCondition.go
  pkg/kcp/provider/aws/vpcpeering/state.go
Labels: size/L, lgtm, cla: yes

#308 feat (AzureVpcPeering): handling API errors
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
Labels: size/S, lgtm, cla: yes

#310 feat(RedisInstance): add KCP GCP RedisInstance reconciler
  PROJECT
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/rbac/cloud-control_redisinstance_editor_role.yaml
  config/rbac/cloud-control_redisinstance_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/cloud-control_v1beta1_redisinstance.yaml
  config/samples/kustomization.yaml
  go.mod
  go.sum
  internal/controller/cloud-control/redisinstance_controller.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
  pkg/kcp/provider/gcp/redisinstance/loadRedis.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go
  pkg/kcp/provider/gcp/redisinstance/state.go
  pkg/kcp/provider/gcp/redisinstance/updateStatus.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisAvailable.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisDeleted.go
  pkg/kcp/redisinstance/loadIpRange.go
  pkg/kcp/redisinstance/reconciler.go
  pkg/kcp/redisinstance/state.go
  pkg/kcp/redisinstance/types/state.go
Labels: size/XXL, lgtm, cla: yes

#311 feat(RedisInstance): add option to configure redis (KCP)
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
Labels: size/L, lgtm, cla: yes

#314 feat (AwsVpcPeering): SKR API
  PROJECT
  api/cloud-resources/v1beta1/awsvpcpeering_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_cloud-resources_awsvpcpeerings.yaml
  config/crd/patches/webhook_in_cloud-resources_awsvpcpeerings.yaml
  config/rbac/cloud-resources_awsvpcpeering_editor_role.yaml
  config/rbac/cloud-resources_awsvpcpeering_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_awsvpcpeering.yaml
  config/samples/kustomization.yaml
  internal/controller/cloud-resources/awsvpcpeering_controller.go
  pkg/skr/awsvpcpeering/addFinalizer.go
  pkg/skr/awsvpcpeering/reconciler.go
  pkg/skr/awsvpcpeering/state.go
Labels: size/XL, lgtm, cla: yes

#318 feat(GcpRedisInstance): add reconciler wireframe
  PROJECT
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/cli/README.md
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/crd/kustomization.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/rbac/cloud-resources_gcpredisinstance_editor_role.yaml
  config/rbac/cloud-resources_gcpredisinstance_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_gcpredisinstance.yaml
  config/samples/kustomization.yaml
  config/sync.sh
  internal/controller/cloud-resources/gcpredisinstance_controller.go
  pkg/feature/ffApiDisabled_test.go
  pkg/feature/testdata/apiDisabled.yaml
  pkg/feature/types/types.go
  pkg/skr/gcpredisinstance/reconciler.go
  pkg/skr/gcpredisinstance/state.go
  pkg/skr/gcpredisinstance/updateId.go
Labels: size/XL, lgtm, cla: yes

#316 feat (AzureVpcPeering): handling authorization and resource not found
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpc.go
  pkg/skr/azurevpcpeering/updateId.go
  pkg/skr/azurevpcpeering/updateStatus.go
Labels: size/M, lgtm, cla: yes

#317 feat (AwsVpcPeering): SKR delete
  api/cloud-resources/v1beta1/awsvpcpeering_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  pkg/skr/awsvpcpeering/createKcpVpcPeering.go
  pkg/skr/awsvpcpeering/deleteKcpVpcPeering.go
  pkg/skr/awsvpcpeering/loadKcpAwsVpcPeering.go
  pkg/skr/awsvpcpeering/reconciler.go
  pkg/skr/awsvpcpeering/removeFinalizer.go
  pkg/skr/awsvpcpeering/state.go
  pkg/skr/awsvpcpeering/updateId.go
  pkg/skr/awsvpcpeering/updateStatus.go
Labels: size/L, lgtm, cla: yes

#319 feat(GcpRedisInstance): add SKR reconciler
  api/cloud-resources/v1beta1/condition.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  api/cloud-resources/v1beta1/labels.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/samples/cloud-resources_v1beta1_gcpredisinstance.yaml
  pkg/skr/gcpredisinstance/createAuthSecret.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/skr/gcpredisinstance/deleteAuthSecret.go
  pkg/skr/gcpredisinstance/deleteKcpRedisInstance.go
  pkg/skr/gcpredisinstance/loadAuthSecret.go
  pkg/skr/gcpredisinstance/loadKcpRedisInstance.go
  pkg/skr/gcpredisinstance/reconciler.go
  pkg/skr/gcpredisinstance/removeAuthSecretFinalizer.go
  pkg/skr/gcpredisinstance/state.go
  pkg/skr/gcpredisinstance/updateId.go
  pkg/skr/gcpredisinstance/updateStatus.go
  pkg/skr/gcpredisinstance/util.go
  pkg/skr/gcpredisinstance/waitAuthSecretDeleted.go
  pkg/skr/gcpredisinstance/waitKcpRedisInstanceDeleted.go
  pkg/skr/gcpredisinstance/waitKcpStatusUpdate.go
  pkg/skr/gcpredisinstance/waitSkrStatusReady.go
Labels: size/XL, lgtm, cla: yes

#320 chore (AzureVpcPeering): fixing typo in log message
  pkg/skr/azurevpcpeering/updateId.go
Labels: size/XS, lgtm, cla: yes

#315 docs: user documentation for NFS
  .github/workflows/lint-markdown-links.yml
  .github/workflows/pr-docu-check.yaml
  docs/technical/README.md
  docs/technical/assets/api-and-reconcilers.excalidraw
  docs/technical/assets/api-and-reconcilers.png
  docs/technical/assets/skr-controller-manager.excalidraw
  docs/technical/assets/skr-controller-manager.png
  docs/user/05-glossary.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/04-10-iprange.md
  docs/user/resources/04-20-10-aws-nfs-volume.md
  docs/user/resources/04-30-10-gcp-nfs-volume.md
  docs/user/resources/README.md
  docs/user/tutorials/01-10-aws-nfs-volume.md
  docs/user/tutorials/README.md
Labels: size/XL, lgtm, cla: yes

#326 feat(GcpRedisInstance): add auth settings to API
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/skr/gcpredisinstance/deleteKcpRedisInstance.go
Labels: size/L, lgtm, cla: yes

#324 chore: Test with k8s v1.29.3
  Makefile
Labels: size/XS, lgtm, cla: yes

#329 chore(AwsVpcPeering): adjust sync.sh copy path for AwsVpcPeering
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/sync.sh
Labels: size/XS, lgtm, cla: yes

#328 feat(SKR IpRange): change SKR IpRange to cluster scope
  PROJECT
  api/cloud-resources/v1beta1/iprange_ref.go
  api/cloud-resources/v1beta1/iprange_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
  internal/controller/cloud-resources/iprange_controller.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/skr/common/defaultiprange/createDefaultSkrIpRange.go
  pkg/skr/common/defaultiprange/findDefaultSkrIpRange.go
  pkg/skr/common/defaultiprange/new.go
  pkg/skr/gcpnfsvolume/loadKcpIpRange.go
  pkg/skr/gcpnfsvolume/state_test.go
  pkg/skr/gcpnfsvolume/validateSpec_test.go
  pkg/skr/gcpnfsvolumebackup/state_test.go
  pkg/skr/gcpnfsvolumerestore/state_test.go
  pkg/skr/iprange/createKcpIpRange.go
  pkg/skr/iprange/preventCidrOverlap.go
  pkg/skr/iprange/preventDeleteOnAwsNfsVolumeUsage.go
  pkg/skr/iprange/preventDeleteOnGcpNfsVolumeUsage.go
  pkg/testinfra/dsl/awsNfsVolume.go
  pkg/testinfra/dsl/gcpNfsVolume.go
  pkg/testinfra/dsl/skrIpRange.go
  tools/scripts/kcp/listSkrs.mjs
Labels: size/L, lgtm, cla: yes

#330 chore: added taskrun script moduleDisable
  internal/controller/cloud-control/iprange_aws_test.go
  internal/controller/cloud-control/iprange_gcp_test.go
  pkg/common/actions/focal/loadScopeFromRef.go
  pkg/testinfra/dsl/awsIpRange.go
  pkg/testinfra/dsl/kcpIpRange.go
  tools/scripts/kcp/listSkrs.mjs
  tools/scripts/taskrun/moduleDisable.mjs
Labels: size/M, lgtm, cla: yes

#331 test(GcpRedisInstance): add scenario tests
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  internal/controller/cloud-resources/awsnfsvolume_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  internal/controller/cloud-resources/iprange_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/testinfra/dsl/awsNfsVolume.go
  pkg/testinfra/dsl/commonIpRange.go
  pkg/testinfra/dsl/gcpRedisInstance.go
  pkg/testinfra/dsl/loadAndCheck.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/XXL, lgtm, cla: yes

#335 feat(GcpNfsVolume, AwsNfsVolume): change default PV name
  internal/controller/cloud-resources/awsnfsvolume_test.go
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  pkg/skr/awsnfsvolume/util.go
  pkg/skr/awsnfsvolume/validatePersistentVolume_test.go
  pkg/skr/gcpnfsvolume/createPersistenceVolume_test.go
  pkg/skr/gcpnfsvolume/updateId.go
  pkg/skr/gcpnfsvolume/util.go
  pkg/skr/gcpnfsvolume/validatePV_test.go
Labels: size/M, lgtm, cla: yes

#338 fix(GcpNfsVolume) : Fix for GCP NfsInstance naming.
  pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance.go
  pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance_test.go
  pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance.go
  pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance_test.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/setProcessing.go
  pkg/skr/gcpnfsvolume/setProcessing_test.go
Labels: size/L, lgtm, cla: yes

#340 test(RedisInstance): add scenario tests
  internal/controller/cloud-control/nfsinstance_aws_test.go
  internal/controller/cloud-control/nfsinstance_gcp_test.go
  internal/controller/cloud-control/redisinstance_gcp_test.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
  pkg/kcp/provider/gcp/mock/server.go
  pkg/kcp/provider/gcp/mock/type.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/updateStatus.go
  pkg/kcp/provider/gcp/redisinstance/updateStatusId.go
  pkg/skr/gcpredisinstance/deleteKcpRedisInstance.go
  pkg/testinfra/dsl/commonAssertions.go
  pkg/testinfra/dsl/commonIpRange.go
  pkg/testinfra/dsl/nfsInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#334 chore: feature logs landscape
  README.md
  pkg/feature/log.go
  pkg/feature/testdata/apiDisabled.yaml
  pkg/skr/runtime/looper/runner.go
Labels: size/S, lgtm, cla: yes

#342 fix: feature landscape logging
  pkg/skr/runtime/looper/skrLooper.go
Labels: size/XS, lgtm, cla: yes

#343 feat(GcpRedisInstance): swap gcp redis instance name prefix to 'cm'
  pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/client/util.go
  pkg/skr/gcpredisinstance/updateId.go
Labels: size/M, lgtm, cla: yes

#344 chore: SKR runner additional log attributes
  pkg/skr/runtime/looper/runner.go
Labels: size/XS, lgtm, cla: yes

#341 chore: golang ci lint
  .github/workflows/pr-golang-lint.yml
  .golangci.yaml
  pkg/common/actions/focal/loadObj.go
  pkg/composed/predicate.go
  pkg/config/config_bind_test.go
  pkg/kcp/provider/aws/iprange/client/client.go
  pkg/kcp/provider/aws/iprange/v1/checkCidrBlockStatus.go
  pkg/kcp/provider/aws/iprange/v1/checkCidrOverlap.go
  pkg/kcp/provider/aws/iprange/v1/splitRangeByZones.go
  pkg/kcp/provider/aws/iprange/v2/ensureShootZonesAndRangeSubnetsMatch.go
  pkg/kcp/provider/aws/mock/error.go
  pkg/kcp/provider/aws/mock/vpcPeeringStore.go
  pkg/kcp/provider/aws/nfsinstance/client/client.go
  pkg/kcp/provider/aws/util/ec2tags.go
  pkg/kcp/provider/aws/vpcpeering/acceptVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
  pkg/kcp/provider/azure/mock/networkStore.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/storeSubscriptionContext.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/waitNetworkTag.go
  pkg/kcp/provider/gcp/iprange/v1/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/iprange/v1/compareStates_test.go
  pkg/kcp/provider/gcp/iprange/v2/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/iprange/v2/compareStates_test.go
  pkg/kcp/provider/gcp/iprange/v2/state_test.go
  pkg/kcp/provider/gcp/mock/iprangeStore.go
  pkg/kcp/provider/gcp/mock/server.go
  pkg/kcp/provider/gcp/vpcpeering/client/cloudComputeClient.go
  pkg/kcp/scope/createScopeAws.go
  pkg/kcp/scope/ignoreScopeObj.go
  pkg/kcp/scope/loadScopeObj.go
  pkg/metrics/cloudProviderAws.go
  pkg/skr/awsnfsvolume/loadSkrIpRange.go
  pkg/skr/awsnfsvolume/reconciler.go
  pkg/skr/awsnfsvolume/waitIpRangeReady.go
  pkg/skr/awsnfsvolumebackup/client/client.go
  pkg/skr/awsnfsvolumebackup/stopIfVolumeNotReady.go
  pkg/skr/gcpnfsvolume/createPersistenceVolume_test.go
  pkg/skr/gcpnfsvolume/createPersistentVolumeClaim_test.go
  pkg/skr/gcpnfsvolume/modifyPersistenceVolume_test.go
  pkg/skr/gcpnfsvolume/updateId.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
  pkg/skr/gcpnfsvolumerestore/addFinalizer_test.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation_test.go
  pkg/skr/runtime/looper/installer.go
  pkg/skr/runtime/looper/skrLooper.go
  pkg/testinfra/dsl/awsIpRange.go
  pkg/testinfra/infra.go
  pkg/util/cidr.go
Labels: size/L, lgtm, cla: yes

#345 chore: change import alias to match the actual import
  pkg/kcp/redisinstance/loadIpRange.go
  pkg/kcp/redisinstance/reconciler.go
Labels: size/S, lgtm, cla: yes

#347 chore: feature from unstructured crd and busola cm
  api/cloud-resources/v1beta1/nfsbackupschedule_types.go
  pkg/feature/context.go
  pkg/feature/object2feature.go
  pkg/feature/object2feature_test.go
  pkg/feature/objectKinds.go
  pkg/feature/objectKinds_test.go
  pkg/feature/types/types.go
Labels: size/XL, lgtm, cla: yes

#348 chore: config reload
  cmd/main.go
  pkg/config/config.go
  pkg/config/types.go
Labels: size/S, lgtm, cla: yes

#336 (chore) bring UI parity for existing cloud manager items
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/ui-extensions/awsnfsvolumes/details
  config/ui-extensions/awsnfsvolumes/form
  config/ui-extensions/awsnfsvolumes/translations
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/details
  config/ui-extensions/gcpnfsvolumebackups/translations
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/details
  config/ui-extensions/gcpnfsvolumes/form
  config/ui-extensions/gcpnfsvolumes/translations
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/ipranges/form
  config/ui-extensions/ipranges/list
Labels: size/L, lgtm, cla: yes

#349 docs: Update sidebar.md and formatting
  docs/README.md
  docs/user/00-10-glossary.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: documentation, area/documentation, size/M, lgtm, cla: yes

#346 feat(RedisInstance): add KCP Azure specs
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  go.mod
  go.sum
  internal/controller/cloud-control/redisinstance_controller.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/type.go
  pkg/kcp/provider/azure/redisinstance/client/client.go
  pkg/kcp/provider/azure/redisinstance/new.go
  pkg/kcp/provider/azure/redisinstance/state.go
  pkg/kcp/redisinstance/reconciler.go
Labels: size/L, lgtm, cla: yes

#309 (chore) UI Documentation
  docs/contributor/ui/README.md
Labels: size/L, lgtm, cla: yes

#352 docs: Update Main Readme
  README.md
Labels: size/M, lgtm, cla: yes

#332 docs: user tutorial for GCP NFS
  docs/user/00-10-glossary.md
  docs/user/_sidebar.md
  docs/user/resources/04-30-10-gcp-nfs-volume.md
  docs/user/tutorials/01-20-gcp-nfs-volume.md
  docs/user/tutorials/README.md
Labels: size/L, lgtm, cla: yes

#351 chore(docs): moved technical to contributor/architecture
  docs/contributor/architecture/README.md
  docs/contributor/architecture/assets/api-and-reconcilers.drawio.svg
  docs/contributor/architecture/assets/skr-controller-manager.drawio.svg
  docs/contributor/assets/nfs-design-approach.excalidraw
  docs/contributor/assets/nfs-design-approach.png
  docs/contributor/design-approach.md
  docs/technical/README.md
  docs/technical/assets/api-and-reconcilers.excalidraw
  docs/technical/assets/api-and-reconcilers.png
  docs/technical/assets/client-go-controller-interaction.jpeg
  docs/technical/assets/skr-controller-manager.excalidraw
  docs/technical/assets/skr-controller-manager.png
Labels: size/XXL, lgtm, cla: yes

#306 docs(testing-strategy): add testing strategy and test plan documents drafts
  docs/contributor/assets/v-model.png
  docs/contributor/test-plan-template.md
  docs/contributor/test-plan-unittesting.md
  docs/contributor/test-plan-validation.md
  docs/contributor/testing-strategy.md
Labels: size/L, lgtm, cla: yes

#354 feat(RedisInstance): add AWS KCP reconciler
  cmd/main.go
  go.mod
  go.sum
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-control/redisinstance_controller.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/mock/server.go
  pkg/kcp/provider/aws/mock/type.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/createSubnetGroup.go
  pkg/kcp/provider/aws/redisinstance/deleteElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/deleteSubnetGroup.go
  pkg/kcp/provider/aws/redisinstance/loadElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/loadSubnetGroup.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/aws/redisinstance/removeReadyCondition.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/kcp/provider/aws/redisinstance/updateStatus.go
  pkg/kcp/provider/aws/redisinstance/updateStatusId.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
  pkg/kcp/redisinstance/reconciler.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/XXL, lgtm, cla: yes

#355 chore: SKR Looper configurable concurrency
  pkg/config/binding.go
  pkg/skr/runtime/config/config.go
  pkg/skr/runtime/looper/cyclicQueue.go
  pkg/skr/runtime/looper/cyclicQueue_smoke_test.go
  pkg/skr/runtime/looper/skrLooper.go
Labels: size/L, lgtm, cla: yes

#356 chore: skrLooper log field workerId
  pkg/skr/runtime/looper/skrLooper.go
Labels: size/S, lgtm, cla: yes

#357 feat(Scope): enable GCP MemoryStore for Redis
  pkg/kcp/provider/gcp/client/gcpConstants.go
  pkg/kcp/scope/enableApisGcp.go
Labels: size/S, lgtm, cla: yes

#360 fix(AwsRedisInstance): prefix resources with '-cm'
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/createSubnetGroup.go
  pkg/kcp/provider/aws/redisinstance/loadElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/loadSubnetGroup.go
  pkg/kcp/provider/aws/redisinstance/util.go
  pkg/skr/awsredisinstance/waitKcpRedisInstanceDeleted.go
  pkg/skr/gcpredisinstance/loadKcpRedisInstance.go
  pkg/skr/gcpredisinstance/reconciler.go
  pkg/skr/gcpredisinstance/waitKcpRedisInstanceDeleted.go
Labels: size/M, lgtm, cla: yes

#361 feat: CC Scope
  api/cloud-control/v1beta1/providerType.go
  api/cloud-control/v1beta1/scope_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  pkg/kcp/scope/createScope.go
  pkg/kcp/scope/createScopeOpenStack.go
Labels: size/L, lgtm, cla: yes

#365 chore: ccee scope installer fix
  config/dist/skr/crd/bases/providers/openstack/.gitignore
  pkg/skr/runtime/looper/installer.go
Labels: size/XS, lgtm, cla: yes

#366 feat(GcpNfsVolume): make location optional
  api/cloud-control/v1beta1/scope_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  config/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/patchAfterMakeManifests.sh
  pkg/feature/ffGcpNfsVolumeAutomaticLocationAllocation.go
  pkg/kcp/scope/createScope.go
  pkg/kcp/scope/createScopeAws.go
  pkg/kcp/scope/createScopeAzure.go
  pkg/kcp/scope/createScopeGcp.go
  pkg/kcp/scope/loadScopeObj.go
  pkg/kcp/scope/reconciler.go
  pkg/kcp/scope/saveScope.go
  pkg/skr/gcpnfsvolume/loadScope.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/state.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/testinfra/dsl/scope.go
  pkg/testinfra/dsl/shoot.go
Labels: size/L, lgtm, cla: yes

#367 docs: Update sample GcpNfsVolume in GcpNfsVolume resource doc
  docs/user/resources/04-30-10-gcp-nfs-volume.md
Labels: size/XS, lgtm, cla: yes

#368 feat(AwsRedisInstance): add specs for definition of machine details
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/samples/cloud-resources_v1beta1_awsredisinstance.yaml
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-resources/awsredisinstance_test.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/createSubnetGroup.go
  pkg/skr/awsredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/awsRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#375 chore: upgrade to kubebuilder 4.1.1 and go 1.22
  Dockerfile
  go.mod
  go.sum
  pkg/kcp/provider/gcp/iprange/v2/allocateIpRange_test.go
  pkg/kcp/provider/gcp/iprange/v2/copyCidrToStatus_test.go
  pkg/kcp/provider/gcp/iprange/v2/preventCidrEdit_test.go
  pkg/skr/runtime/manager/manager.go
  pkg/skr/runtime/registry/builder.go
Labels: size/XL, lgtm, cla: yes

#381 chore: upgrade golangci-lint action to v6.0.1
  .github/workflows/pr-golang-lint.yml
Labels: size/XS, lgtm, cla: yes

#371 fix(IpRange): change GCP IpRange naming strategy
  api/cloud-control/v1beta1/iprange_types.go
  config/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
  pkg/kcp/provider/gcp/iprange/v2/compareStates.go
  pkg/kcp/provider/gcp/iprange/v2/compareStates_test.go
  pkg/kcp/provider/gcp/iprange/v2/loadAddress.go
  pkg/kcp/provider/gcp/iprange/v2/loadAddress_test.go
  pkg/kcp/provider/gcp/iprange/v2/new.go
  pkg/kcp/provider/gcp/iprange/v2/state.go
  pkg/kcp/provider/gcp/iprange/v2/state_test.go
  pkg/kcp/provider/gcp/iprange/v2/syncAddress.go
  pkg/kcp/provider/gcp/iprange/v2/syncAddress_test.go
  pkg/kcp/provider/gcp/iprange/v2/updateStatusId.go
  pkg/kcp/provider/gcp/iprange/v2/util.go
  pkg/kcp/provider/gcp/iprange/v2/validateCidr.go
  pkg/kcp/provider/gcp/meta/metadata.go
  pkg/kcp/provider/gcp/nfsinstance/state.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
Labels: size/XL, lgtm, cla: yes

#385 chore(IpRange): add logs for .status.id update
  pkg/kcp/provider/gcp/iprange/v2/updateStatusId.go
Labels: size/XS, lgtm, cla: yes

#374 feat(GcpRedisInstance,RedisInstance) update types
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
Labels: size/XXL, lgtm, cla: yes

#384 refactor(GcpRedisInstance, AwsRedisInstance): track secret ownership via parent .status.id label
  api/cloud-resources/v1beta1/labels.go
  internal/controller/cloud-resources/awsredisinstance_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  pkg/skr/awsredisinstance/deleteAuthSecret.go
  pkg/skr/awsredisinstance/loadAuthSecret.go
  pkg/skr/awsredisinstance/util.go
  pkg/skr/gcpredisinstance/deleteAuthSecret.go
  pkg/skr/gcpredisinstance/loadAuthSecret.go
  pkg/skr/gcpredisinstance/util.go
Labels: size/M, lgtm, cla: yes

#369 feat(AzureRedisInstance): add KCP reconciler - load, create, delete
  api/cloud-control/v1beta1/redisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  go.mod
  go.sum
  internal/controller/cloud-control/redisinstance_azure_test.go
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/mock/redisCacheClientFake.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/type.go
  pkg/kcp/provider/azure/redisinstance/client/client.go
  pkg/kcp/provider/azure/redisinstance/createRedis.go
  pkg/kcp/provider/azure/redisinstance/createResourceGroup.go
  pkg/kcp/provider/azure/redisinstance/deleteRedis.go
  pkg/kcp/provider/azure/redisinstance/deleteResourceGroup.go
  pkg/kcp/provider/azure/redisinstance/loadRedis.go
  pkg/kcp/provider/azure/redisinstance/loadResourceGroup.go
  pkg/kcp/provider/azure/redisinstance/new.go
  pkg/kcp/provider/azure/redisinstance/state.go
  pkg/kcp/provider/azure/redisinstance/updateStatus.go
  pkg/kcp/provider/azure/redisinstance/updateStatusId.go
  pkg/kcp/provider/azure/redisinstance/waitRedisAvailable.go
  pkg/kcp/provider/azure/redisinstance/waitRedisDeleted.go
  pkg/kcp/provider/azure/redisinstance/waitResourceGroupDeleted.go
  pkg/kcp/provider/azure/util/resources.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/XXL, lgtm, cla: yes

#388 refactor: change names too match context
  api/cloud-resources/v1beta1/labels.go
  internal/controller/cloud-resources/awsredisinstance_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  pkg/kcp/provider/gcp/redisinstance/state.go
  pkg/skr/awsredisinstance/loadAuthSecret.go
  pkg/skr/awsredisinstance/loadKcpRedisInstance.go
  pkg/skr/awsredisinstance/reconciler.go
  pkg/skr/awsredisinstance/util.go
  pkg/skr/awsredisinstance/waitKcpRedisInstanceDeleted.go
  pkg/skr/gcpredisinstance/loadAuthSecret.go
  pkg/skr/gcpredisinstance/util.go
Labels: size/S, lgtm, cla: yes

#386 feat (AzureVpcPeering): adds validation for immutable fields
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
Labels: size/M, lgtm, cla: yes

#387 feat (AwsVpcPeering): adds validation for immutable fields
  api/cloud-resources/v1beta1/awsvpcpeering_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
Labels: size/M, lgtm, cla: yes

#377 feat (AwsVpcPeering): supports peering remote vpc network with multiple kyma clusters
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/mock/vpcPeeringStore.go
  pkg/kcp/provider/aws/util/ec2tags.go
  pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
  pkg/kcp/provider/aws/vpcpeering/client/client.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/skr/awsvpcpeering/createKcpVpcPeering.go
Labels: size/M, lgtm, cla: yes

#376 feat (AzureVpcPeering): supports peering remote vpc network with multiple kyma clusters
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/vpcpeering/waitNetworkTag.go
  pkg/skr/azurevpcpeering/createKpcVpcPeering.go
Labels: size/S, lgtm, cla: yes

#304 feat(NfsBackupSchedule) reconciler
  PROJECT
  api/cloud-resources/v1beta1/condition.go
  api/cloud-resources/v1beta1/gcpnfsbackupschedule_types.go
  api/cloud-resources/v1beta1/labels.go
  api/cloud-resources/v1beta1/nfsbackupschedule_types.go
  api/cloud-resources/v1beta1/state.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/crd/kustomization.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/rbac/cloud-resources_gcpnfsbackupschedule_editor_role.yaml
  config/rbac/cloud-resources_gcpnfsbackupschedule_viewer_role.yaml
  config/samples/cloud-resources_v1beta1_gcpnfsbackupschedule.yaml
  config/samples/kustomization.yaml
  config/sync.sh
  go.mod
  go.sum
  internal/controller/cloud-resources/gcpnfsbackupschedule_controller.go
  internal/controller/cloud-resources/gcpnfsbackupschedule_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/skr/backupschedule/addFinalizer.go
  pkg/skr/backupschedule/addFinalizer_test.go
  pkg/skr/backupschedule/backupImpl.go
  pkg/skr/backupschedule/backupImplGcpNfs.go
  pkg/skr/backupschedule/backupschedule.go
  pkg/skr/backupschedule/calculateOnetimeSchedule.go
  pkg/skr/backupschedule/calculateOnetimeSchedule_test.go
  pkg/skr/backupschedule/calculateRecurringSchedule.go
  pkg/skr/backupschedule/calculateRecurringSchedule_test.go
  pkg/skr/backupschedule/checkCompleted.go
  pkg/skr/backupschedule/checkCompleted_test.go
  pkg/skr/backupschedule/checkSuspension.go
  pkg/skr/backupschedule/checkSuspension_test.go
  pkg/skr/backupschedule/createBackup.go
  pkg/skr/backupschedule/createBackup_test.go
  pkg/skr/backupschedule/deleteBackups.go
  pkg/skr/backupschedule/deleteBackups_test.go
  pkg/skr/backupschedule/deleteCascade.go
  pkg/skr/backupschedule/deleteCascade_test.go
  pkg/skr/backupschedule/evaluateNextRun.go
  pkg/skr/backupschedule/evaluateNextRun_test.go
  pkg/skr/backupschedule/loadBackups.go
  pkg/skr/backupschedule/loadScope.go
  pkg/skr/backupschedule/loadScope_test.go
  pkg/skr/backupschedule/loadSource.go
  pkg/skr/backupschedule/loadSource_test.go
  pkg/skr/backupschedule/reconciler.go
  pkg/skr/backupschedule/removeFinalizer.go
  pkg/skr/backupschedule/removeFinalizer_test.go
  pkg/skr/backupschedule/state.go
  pkg/skr/backupschedule/state_test.go
  pkg/skr/backupschedule/validateSchedule.go
  pkg/skr/backupschedule/validateSchedule_test.go
  pkg/skr/backupschedule/validateTimes.go
  pkg/skr/backupschedule/validateTimes_test.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
  pkg/testinfra/dsl/nfsBackupSchedule.go
Labels: size/XXL, lgtm, cla: yes

#393 Change enable and disable to add and delete in the cloud-manager repo
  cmd/cli/README.md
  docs/contributor/architecture/README.md
  docs/user/README.md
Labels: size/XS, lgtm, cla: yes

#401 [docs] Align diagrams with content guidelines
  docs/contributor/architecture/README.md
  docs/contributor/architecture/assets/api-and-reconcilers.drawio.svg
  docs/contributor/architecture/assets/skr-controller-manager.drawio.svg
Labels: documentation, area/documentation, size/XXL, lgtm, cla: yes
