Repository kyma-project/cloud-manager, pull requests merged in 2024-01, with the labels that each got.

#29 skeleton actions for gcp iprange
  .gitignore
  components/kcp/api/cloud-control/v1beta1/iprange_types.go
  components/kcp/api/cloud-control/v1beta1/zz_generated.deepcopy.go
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
  components/kcp/pkg/provider/gcp/iprange/checkNupdateStatus.go
  components/kcp/pkg/provider/gcp/iprange/loadAddress.go
  components/kcp/pkg/provider/gcp/iprange/loadPsaConnection.go
  components/kcp/pkg/provider/gcp/iprange/new.go
  components/kcp/pkg/provider/gcp/iprange/state.go
  components/kcp/pkg/provider/gcp/iprange/syncAddress.go
  components/kcp/pkg/provider/gcp/iprange/syncPsaConnection.go
Labels: size/L, lgtm, cla: yes

#30 adding gcp client for iprange
  components/kcp/cmd/main.go
  components/kcp/go.mod
  components/kcp/go.sum
  components/kcp/pkg/provider/gcp/client/gcpConstants.go
  components/kcp/pkg/provider/gcp/client/provider.go
  components/kcp/pkg/provider/gcp/client/types.go
  components/kcp/pkg/provider/gcp/iprange/client/computeClient.go
  components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
  components/kcp/pkg/provider/gcp/iprange/state.go
Labels: size/L, lgtm, cla: yes

#31 GCP IPRange GetAddress call to GCP
  components/kcp/api/cloud-control/v1beta1/types.go
  components/kcp/cmd/main.go
  components/kcp/pkg/common/actions/focal/addFinalizer.go
  components/kcp/pkg/common/actions/focal/removeFinalizer.go
  components/kcp/pkg/iprange/reconciler.go
  components/kcp/pkg/provider/gcp/client/gcpConstants.go
  components/kcp/pkg/provider/gcp/client/provider.go
  components/kcp/pkg/provider/gcp/iprange/client/computeClient.go
  components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
  components/kcp/pkg/provider/gcp/iprange/compareStates.go
  components/kcp/pkg/provider/gcp/iprange/loadAddress.go
  components/kcp/pkg/provider/gcp/iprange/new.go
  components/kcp/pkg/provider/gcp/iprange/state.go
  components/kcp/pkg/provider/gcp/iprange/switchToReadyState.go
  components/kcp/pkg/provider/gcp/iprange/validateCidr.go
  components/kcp/pkg/util/cidr.go
Labels: size/L, lgtm, cla: yes

#32 Adding more APIs to gcp ipranges clients
  components/kcp/pkg/provider/gcp/client/gcpConstants.go
  components/kcp/pkg/provider/gcp/iprange/client/computeClient.go
  components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
Labels: size/M, lgtm, cla: yes

#34 SKR looper and controller manager
  components/kcp/cmd/main.go
  components/kcp/internal/controller/cloud-resources/cloudresources_controller.go
  components/kcp/pkg/common/actions/focal/fixInvalidScopeRef.go
  components/kcp/pkg/provider/gcp/iprange/client/computeClient.go
  components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
  components/kcp/pkg/provider/gcp/iprange/loadAddress.go
  components/kcp/pkg/skr/cache/cache.go
  components/kcp/pkg/skr/looper/runner.go
  components/kcp/pkg/skr/looper/skrLooper.go
  components/kcp/pkg/skr/manager/factory.go
  components/kcp/pkg/skr/manager/manager.go
  components/kcp/pkg/skr/registry/builder.go
  components/kcp/pkg/skr/registry/options.go
  components/kcp/pkg/skr/registry/registry.go
  components/kcp/pkg/skr/source/source.go
  components/kcp/pkg/util/scheme.go
  components/kcp/tools/dev/kind/.gitignore
  components/kcp/tools/dev/kind/create-skr.sh
  components/kcp/tools/dev/kind/kind-skr-config.yaml
Labels: size/XXL, lgtm, cla: yes

#35 skr manager stop on empty queue
  components/kcp/pkg/skr/looper/runner.go
  components/kcp/pkg/skr/registry/registry.go
  components/kcp/pkg/skr/source/source.go
Labels: size/M, lgtm, cla: yes

#46 pr checks
  .github/workflows/pr-checks.yml
Labels: size/S, lgtm, cla: yes

#45 Fix - Adding more IPRanges and reconcilation
  components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
  components/kcp/pkg/provider/gcp/iprange/syncAddress.go
  components/kcp/pkg/provider/gcp/iprange/syncPsaConnection.go
  components/kcp/pkg/provider/gcp/iprange/updateState.go
Labels: size/S, lgtm, cla: yes

#47 (Sync) IpRange SKR reconciliation
  components/kcp/api/cloud-resources/v1beta1/condition.go
  components/kcp/cmd/main.go
  components/kcp/pkg/criprange/createKcpIpRange.go
  components/kcp/pkg/criprange/new.go
  components/kcp/pkg/criprange/reconciler.go
  components/kcp/pkg/criprange/updateStatus.go
  components/lib/composed/action_test.go
  components/lib/composed/state.go
  components/lib/composed/updateStatus.go
Labels: size/L, lgtm, cla: yes

#44 Reusing gcp http client
  components/kcp/go.mod
  components/kcp/go.sum
  components/kcp/pkg/provider/gcp/client/provider.go
  components/kcp/pkg/provider/gcp/iprange/client/computeClient.go
  components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
  components/kcp/pkg/provider/gcp/iprange/state.go
Labels: size/L, lgtm, cla: yes

#51 Adding patch API to FilestoreClient and some small fixes
  components/kcp/pkg/provider/gcp/client/provider.go
  components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
  components/kcp/pkg/provider/gcp/iprange/state.go
  components/kcp/pkg/provider/gcp/iprange/syncPsaConnection.go
  components/kcp/pkg/provider/gcp/nfsinstance/client/filestoreClient.go
Labels: size/M, lgtm, cla: yes

#48 adding lib tests
  .github/workflows/pr-checks.yml
  components/lib/composed/action_test.go
Labels: size/M, lgtm, cla: yes

#52 refactor skr package paths
  components/kcp/cmd/main.go
  components/kcp/internal/controller/cloud-resources/awsnfsvolume_controller.go
  components/kcp/internal/controller/cloud-resources/cloudresources_controller.go
  components/kcp/internal/controller/cloud-resources/iprange_controller.go
  components/kcp/pkg/skr/iprange/criprange/addFinalizer.go
  components/kcp/pkg/skr/iprange/criprange/copyCidrToStatus.go
  components/kcp/pkg/skr/iprange/criprange/createKcpIpRange.go
  components/kcp/pkg/skr/iprange/criprange/deleteKcpIpRange.go
  components/kcp/pkg/skr/iprange/criprange/loadKcpIpRange.go
  components/kcp/pkg/skr/iprange/criprange/preventCidrChange.go
  components/kcp/pkg/skr/iprange/criprange/reconciler.go
  components/kcp/pkg/skr/iprange/criprange/removeFinalizer.go
  components/kcp/pkg/skr/iprange/criprange/state.go
  components/kcp/pkg/skr/iprange/criprange/updateStatus.go
  components/kcp/pkg/skr/iprange/criprange/validateCidr.go
  components/kcp/pkg/skr/runtime/alias.go
  components/kcp/pkg/skr/runtime/cache/cache.go
  components/kcp/pkg/skr/runtime/looper/runner.go
  components/kcp/pkg/skr/runtime/looper/skrLooper.go
  components/kcp/pkg/skr/runtime/manager/factory.go
  components/kcp/pkg/skr/runtime/manager/manager.go
  components/kcp/pkg/skr/runtime/registry/builder.go
  components/kcp/pkg/skr/runtime/registry/options.go
  components/kcp/pkg/skr/runtime/registry/registry.go
  components/kcp/pkg/skr/runtime/source/source.go
Labels: size/M, lgtm, cla: yes

#50 GCP Nfs Reconciliation
  components/kcp/api/cloud-control/v1beta1/nfsinstance_gcp_types.go
  components/kcp/api/cloud-control/v1beta1/nfsinstance_types.go
  components/kcp/api/cloud-control/v1beta1/zz_generated.deepcopy.go
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  components/kcp/pkg/nfsinstance/loadIpRange.go
  components/kcp/pkg/nfsinstance/reconciler.go
  components/kcp/pkg/provider/gcp/client/gcpConstants.go
  components/kcp/pkg/provider/gcp/nfsinstance/checkNUpdateState.go
  components/kcp/pkg/provider/gcp/nfsinstance/client/filestoreClient.go
  components/kcp/pkg/provider/gcp/nfsinstance/loadNfsInstance.go
  components/kcp/pkg/provider/gcp/nfsinstance/new.go
  components/kcp/pkg/provider/gcp/nfsinstance/state.go
  components/kcp/pkg/provider/gcp/nfsinstance/syncNfsInstance.go
Labels: size/L, lgtm, cla: yes

#53 GCP NFS Instance Reconcilation
  components/kcp/api/cloud-control/v1beta1/iprange_types.go
  components/kcp/api/cloud-control/v1beta1/nfsinstance_types.go
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  components/kcp/pkg/provider/gcp/client/gcpConstants.go
  components/kcp/pkg/provider/gcp/iprange/checkGcpOperation.go
  components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
  components/kcp/pkg/provider/gcp/iprange/new.go
  components/kcp/pkg/provider/gcp/iprange/syncAddress.go
  components/kcp/pkg/provider/gcp/iprange/syncPsaConnection.go
  components/kcp/pkg/provider/gcp/nfsinstance/checkGcpOperation.go
  components/kcp/pkg/provider/gcp/nfsinstance/checkUpdateMask.go
  components/kcp/pkg/provider/gcp/nfsinstance/loadNfsInstance.go
  components/kcp/pkg/provider/gcp/nfsinstance/new.go
  components/kcp/pkg/provider/gcp/nfsinstance/state.go
  components/kcp/pkg/provider/gcp/nfsinstance/syncNfsInstance.go
Labels: size/L, lgtm, cla: yes

#54 Scope reconciler
  components/kcp/api/cloud-control/v1beta1/conditions.go
  components/kcp/api/cloud-control/v1beta1/iprange_types.go
  components/kcp/api/cloud-control/v1beta1/nfsinstance_types.go
  components/kcp/api/cloud-control/v1beta1/scope_types.go
  components/kcp/api/cloud-control/v1beta1/vpcpeering_types.go
  components/kcp/api/cloud-control/v1beta1/zz_generated.deepcopy.go
  components/kcp/cmd/main.go
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  components/kcp/config/rbac/role.yaml
  components/kcp/internal/controller/cloud-control/nfsinstance_controller.go
  components/kcp/internal/controller/cloud-control/scope_controller.go
  components/kcp/pkg/common/actions/focal/fixInvalidScopeRef.go
  components/kcp/pkg/common/actions/focal/loadScopeFromRef.go
  components/kcp/pkg/common/actions/focal/new.go
  components/kcp/pkg/common/actions/focal/types.go
  components/kcp/pkg/common/actions/scope/ensureScopeCommonFields.go
  components/kcp/pkg/common/actions/scope/findScope.go
  components/kcp/pkg/common/actions/scope/loadGardenerCredentials.go
  components/kcp/pkg/common/actions/scope/loadKyma.go
  components/kcp/pkg/common/actions/scope/new.go
  components/kcp/pkg/common/actions/scope/saveScope.go
  components/kcp/pkg/common/actions/scope/state.go
  components/kcp/pkg/common/actions/scope/updateScopeRef.go
  components/kcp/pkg/common/actions/scope/whenNoScopeCreated.go
  components/kcp/pkg/common/actions/scope/whenNoScopeRef.go
  components/kcp/pkg/iprange/reconciler.go
  components/kcp/pkg/kcp/scope/addKymaFinalizer.go
  components/kcp/pkg/kcp/scope/client/awsStsClient.go
  components/kcp/pkg/kcp/scope/createGardenerClient.go
  components/kcp/pkg/kcp/scope/createScope.go
  components/kcp/pkg/kcp/scope/createScopeAws.go
  components/kcp/pkg/kcp/scope/createScopeAzure.go
  components/kcp/pkg/kcp/scope/createScopeGcp.go
  components/kcp/pkg/kcp/scope/ensureScopeCommonFields.go
  components/kcp/pkg/kcp/scope/findKymaModuleState.go
  components/kcp/pkg/kcp/scope/findShootName.go
  components/kcp/pkg/kcp/scope/loadGardenerCredentials.go
  components/kcp/pkg/kcp/scope/loadKyma.go
  components/kcp/pkg/kcp/scope/loadScopeObj.go
  components/kcp/pkg/kcp/scope/loadShoot.go
  components/kcp/pkg/kcp/scope/reconciler.go
  components/kcp/pkg/kcp/scope/saveScope.go
  components/kcp/pkg/kcp/scope/skrActivate.go
  components/kcp/pkg/kcp/scope/state.go
  components/kcp/pkg/nfsinstance/reconciler.go
  components/kcp/pkg/provider/azure/iprange/new.go
  components/kcp/pkg/skr/iprange/criprange/createKcpIpRange.go
  components/kcp/pkg/skr/runtime/alias.go
  components/kcp/pkg/skr/runtime/looper/skrLooper.go
  components/kcp/pkg/util/kyma.go
  components/lib/composed/state.go
Labels: size/XXL, lgtm, cla: yes

#55 Removed Add/Remove Finalizers actions from focal package
  components/kcp/pkg/common/actions/addFinalizer.go
  components/kcp/pkg/common/actions/focal/types.go
  components/kcp/pkg/common/actions/removeFinalizer.go
  components/kcp/pkg/provider/gcp/client/gcpConstants.go
  components/kcp/pkg/provider/gcp/iprange/compareStates.go
  components/kcp/pkg/provider/gcp/iprange/new.go
  components/kcp/pkg/provider/gcp/iprange/state.go
  components/kcp/pkg/provider/gcp/iprange/syncAddress.go
  components/kcp/pkg/provider/gcp/iprange/syncPsaConnection.go
  components/kcp/pkg/provider/gcp/nfsinstance/checkNUpdateState.go
  components/kcp/pkg/provider/gcp/nfsinstance/checkUpdateMask.go
  components/kcp/pkg/provider/gcp/nfsinstance/new.go
  components/kcp/pkg/provider/gcp/nfsinstance/state.go
  components/kcp/pkg/provider/gcp/nfsinstance/syncNfsInstance.go
Labels: size/L, lgtm, cla: yes

#58 GCP NFS Validations
  components/kcp/api/cloud-control/v1beta1/conditions.go
  components/kcp/api/cloud-control/v1beta1/nfsinstance_gcp_types.go
  components/kcp/pkg/provider/gcp/client/gcpConstants.go
  components/kcp/pkg/provider/gcp/nfsinstance/new.go
  components/kcp/pkg/provider/gcp/nfsinstance/state.go
  components/kcp/pkg/provider/gcp/nfsinstance/syncNfsInstance.go
  components/kcp/pkg/provider/gcp/nfsinstance/validateAlways.go
  components/kcp/pkg/provider/gcp/nfsinstance/validatePostCreate.go
  components/kcp/pkg/provider/gcp/nfsinstance/validations.go
Labels: size/L, lgtm, cla: yes

#59 (PHX-35) Updating GcpNfsVolume CR and adding parts of SKR reconciler …
  components/kcp/api/cloud-control/v1beta1/iprange_ref.go
  components/kcp/api/cloud-control/v1beta1/nfsinstance_types.go
  components/kcp/api/cloud-control/v1beta1/zz_generated.deepcopy.go
  components/kcp/api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  components/kcp/api/cloud-resources/v1beta1/iprange_ref.go
  components/kcp/api/cloud-resources/v1beta1/types.go
  components/kcp/api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  components/kcp/config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  components/kcp/pkg/nfsinstance/loadIpRange.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/addFinalizer.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/createKcpNfsInstance.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/deleteKcpNfsInstance.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/loadKcpNfsInstance.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/reconciler.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/removeFinalizer.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/state.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/updateStatus.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/validateSpec.go
Labels: size/XL, lgtm, cla: yes

#60 GCP NfsInstance Validations
  components/kcp/api/cloud-control/v1beta1/nfsinstance_gcp_types.go
  components/kcp/api/cloud-control/v1beta1/nfsinstance_types.go
  components/kcp/config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  components/kcp/pkg/provider/gcp/iprange/compareStates.go
  components/kcp/pkg/provider/gcp/iprange/loadAddress.go
  components/kcp/pkg/provider/gcp/iprange/state.go
  components/kcp/pkg/provider/gcp/iprange/syncAddress.go
  components/kcp/pkg/provider/gcp/nfsinstance/state.go
  components/kcp/pkg/provider/gcp/nfsinstance/validateAlways.go
  components/kcp/pkg/provider/gcp/nfsinstance/validatePostCreate.go
  components/kcp/pkg/provider/gcp/nfsinstance/validations.go
Labels: size/L, lgtm, cla: yes

#61 Identifying and adding actions for gcpNfsVolume
  components/kcp/api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  components/kcp/config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/deletePersistenceVolume.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/loadPersistenceVolume.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/modifyKcpNfsInstance.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/modifyPersistenceVolume.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/reconciler.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/removePersistenceVolumeFinalizer.go
  components/kcp/pkg/skr/nfs/crgcpnfsvolume/validateSpec.go
Labels: size/M, lgtm, cla: yes

#57 aws mock & envtest suite
  components/kcp/Makefile
  components/kcp/cmd/main.go
  components/kcp/config/crd/gardener/core.gardener.cloud_secretbindings.yaml
  components/kcp/config/crd/gardener/core.gardener.cloud_shoots.yaml
  components/kcp/config/crd/operator/operator.kyma-project.io_kymas.yaml
  components/kcp/go.sum
  components/kcp/internal/controller/cloud-control/iprange_controller.go
  components/kcp/internal/controller/cloud-control/nfsinstance_controller.go
  components/kcp/internal/controller/cloud-control/scope_aws_test.go
  components/kcp/internal/controller/cloud-control/scope_controller.go
  components/kcp/internal/controller/cloud-control/suite_test.go
  components/kcp/internal/controller/cloud-control/vpcpeering_controller.go
  components/kcp/pkg/iprange/reconciler.go
  components/kcp/pkg/kcp/scope/addKymaFinalizer.go
  components/kcp/pkg/kcp/scope/createGardenerClient.go
  components/kcp/pkg/kcp/scope/createScopeAws.go
  components/kcp/pkg/kcp/scope/ensureScopeCommonFields.go
  components/kcp/pkg/kcp/scope/ignoreScopeObj.go
  components/kcp/pkg/kcp/scope/loadGardenerCredentials.go
  components/kcp/pkg/kcp/scope/loadKyma.go
  components/kcp/pkg/kcp/scope/loadScopeObj.go
  components/kcp/pkg/kcp/scope/loadShoot.go
  components/kcp/pkg/kcp/scope/reconciler.go
  components/kcp/pkg/kcp/scope/saveScope.go
  components/kcp/pkg/kcp/scope/state.go
  components/kcp/pkg/nfsinstance/reconciler.go
  components/kcp/pkg/provider/aws/gardener/infrastructure.go
  components/kcp/pkg/provider/aws/iprange/state.go
  components/kcp/pkg/provider/aws/mock/ctx.go
  components/kcp/pkg/provider/aws/mock/error.go
  components/kcp/pkg/provider/aws/mock/nfsStore.go
  components/kcp/pkg/provider/aws/mock/scopeStore.go
  components/kcp/pkg/provider/aws/mock/server.go
  components/kcp/pkg/provider/aws/mock/type.go
  components/kcp/pkg/provider/aws/mock/vpcStore.go
  components/kcp/pkg/provider/aws/nfsinstance/state.go
  components/kcp/pkg/skr/runtime/alias.go
  components/kcp/pkg/skr/runtime/registry/builder.go
  components/kcp/pkg/skr/runtime/registry/registry.go
  components/kcp/pkg/testinfra/crd.go
  components/kcp/pkg/testinfra/dsl.go
  components/kcp/pkg/testinfra/env.go
  components/kcp/pkg/testinfra/infra.go
  components/kcp/pkg/testinfra/restConfigToKubeconfig.go
  components/kcp/pkg/testinfra/run.go
  components/kcp/pkg/testinfra/scheme.go
  components/kcp/pkg/testinfra/types.go
  components/kcp/pkg/util/debugged/doc.go
  components/kcp/pkg/util/debugged/no.go
  components/kcp/pkg/util/debugged/when.go
  components/kcp/pkg/util/debugged/yes.go
  components/kcp/pkg/util/kyma.go
  components/lib/composed/action.go
  components/lib/composed/action_test.go
  components/lib/go.mod
  components/lib/go.sum
Labels: size/XXL, lgtm, cla: yes

#63 Scope AWS integration test
  Makefile
  PROJECT
  api/cloud-control/v1beta1/providerType.go
  internal/controller/cloud-control/scope.yaml
  internal/controller/cloud-control/scope_aws_test.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/provider/aws/mock/scopeStore.go
  pkg/testinfra/dsl.go
  pkg/testinfra/run.go
Labels: size/L, lgtm, cla: yes

#64 Implementing non-PV actions for GcpNfsVolume
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  internal/controller/cloud-resources/gcpnfsvolume_controller.go
  pkg/skr/nfs/crgcpnfsvolume/loadKcpNfsInstance.go
  pkg/skr/nfs/crgcpnfsvolume/modifyKcpNfsInstance.go
  pkg/skr/nfs/crgcpnfsvolume/reconciler.go
  pkg/skr/nfs/crgcpnfsvolume/updateStatus.go
  pkg/skr/nfs/crgcpnfsvolume/validateSpec.go
Labels: size/L, lgtm, cla: yes

#70 Dockerfile z
  Dockerfile
Labels: size/XS, lgtm, cla: yes

#65 GcpNfsVolume Reconciler PV actions
  pkg/skr/nfs/crgcpnfsvolume/createPersistenceVolume.go
  pkg/skr/nfs/crgcpnfsvolume/deletePersistenceVolume.go
  pkg/skr/nfs/crgcpnfsvolume/loadKcpNfsInstance.go
  pkg/skr/nfs/crgcpnfsvolume/loadPersistenceVolume.go
  pkg/skr/nfs/crgcpnfsvolume/modifyPersistenceVolume.go
  pkg/skr/nfs/crgcpnfsvolume/reconciler.go
  pkg/skr/nfs/crgcpnfsvolume/removePersistenceVolumeFinalizer.go
  pkg/skr/nfs/crgcpnfsvolume/state.go
Labels: size/L, lgtm, cla: yes

#73 fix package paths in pkg/skr/iprange
  pkg/skr/iprange/addFinalizer.go
  pkg/skr/iprange/copyCidrToStatus.go
  pkg/skr/iprange/createKcpIpRange.go
  pkg/skr/iprange/deleteKcpIpRange.go
  pkg/skr/iprange/loadKcpIpRange.go
  pkg/skr/iprange/preventCidrChange.go
  pkg/skr/iprange/reconciler.go
  pkg/skr/iprange/removeFinalizer.go
  pkg/skr/iprange/state.go
  pkg/skr/iprange/updateStatus.go
  pkg/skr/iprange/validateCidr.go
Labels: size/S, lgtm, cla: yes

#74 Refactor package name, and wiring GcpNfsReconciler
  internal/controller/cloud-resources/gcpnfsvolume_controller.go
  pkg/skr/nfs/crgcpnfsvolume/reconciler.go
  pkg/skr/nfs/gcpnfsvolume/addFinalizer.go
  pkg/skr/nfs/gcpnfsvolume/createPersistenceVolume.go
  pkg/skr/nfs/gcpnfsvolume/deleteKcpNfsInstance.go
  pkg/skr/nfs/gcpnfsvolume/deletePersistenceVolume.go
  pkg/skr/nfs/gcpnfsvolume/loadKcpNfsInstance.go
  pkg/skr/nfs/gcpnfsvolume/loadPersistenceVolume.go
  pkg/skr/nfs/gcpnfsvolume/modifyKcpNfsInstance.go
  pkg/skr/nfs/gcpnfsvolume/modifyPersistenceVolume.go
  pkg/skr/nfs/gcpnfsvolume/reconciler.go
  pkg/skr/nfs/gcpnfsvolume/removeFinalizer.go
  pkg/skr/nfs/gcpnfsvolume/removePersistenceVolumeFinalizer.go
  pkg/skr/nfs/gcpnfsvolume/state.go
  pkg/skr/nfs/gcpnfsvolume/updateStatus.go
  pkg/skr/nfs/gcpnfsvolume/validateSpec.go
Labels: size/L, lgtm, cla: yes
