Repository kyma-project/cloud-manager, pull requests merged in 2024-06, with the labels that each got.

#261 feat(AwsNfsVolume): optional iprange
  api/cloud-resources/v1beta1/awsnfsvolume_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  internal/controller/cloud-resources/awsnfsvolume_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/skr/awsnfsvolume/reconciler.go
  pkg/skr/awsnfsvolume/state.go
  pkg/skr/common/defaultiprange/checkIfIpRangeIsSpecified.go
  pkg/skr/common/defaultiprange/createDefaultSkrIpRange.go
  pkg/skr/common/defaultiprange/findDefaultSkrIpRange.go
  pkg/skr/common/defaultiprange/loadSpecifiedIpRange.go
  pkg/skr/common/defaultiprange/new.go
  pkg/skr/common/defaultiprange/state.go
  pkg/skr/common/defaultiprange/waitIpRangeReady.go
  pkg/testinfra/dsl/awsNfsVolume.go
Labels: size/XL, lgtm, cla: yes

#264 fix(SKR IpRange): optional cidr and overlap check
  pkg/skr/iprange/preventCidrOverlap.go
Labels: size/XS, lgtm, cla: yes

#266 (feat) added translations for backups, restores, ipranges
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/translations
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/translations
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/ipranges/list
  config/ui-extensions/ipranges/translations
Labels: size/M, lgtm, cla: yes

#265 feat(AzureVpcPeering): start SKR controller
  cmd/main.go
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/sync.sh
  pkg/kcp/provider/azure/config/config.go
Labels: size/L, lgtm, cla: yes

#267 (feat) cloud-manager: ui-cm label
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/kustomization.yaml
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/kustomization.yaml
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/kustomization.yaml
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/ipranges/kustomization.yaml
Labels: size/S, lgtm, cla: yes

#268 chore(KCP AWS IpRange): additional logs
  pkg/kcp/provider/aws/iprange/v2/subnetsCreate.go
Labels: size/S, lgtm, cla: yes

#269 chore(GcpNfsVolume): Removed Server from the printable column list
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
Labels: size/XS, lgtm, cla: yes

#271 chore(AwsNfsVolume): crd version bump
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/patchAfterMakeManifests.sh
Labels: size/XL, lgtm, cla: yes

#272 fix(SRK runtime): check provider
  pkg/common/objSupportsProvider.go
  pkg/kcp/provider/aws/iprange/v2/statusSuccess.go
  pkg/skr/runtime/looper/installer.go
  pkg/skr/runtime/looper/runner.go
Labels: size/L, lgtm, cla: yes

#273 (feat) GCP NfsVolume, Backup, Restore, IpRange detail polish
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/details
  config/ui-extensions/gcpnfsvolumebackups/translations
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/details
  config/ui-extensions/gcpnfsvolumerestores/translations
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/details
  config/ui-extensions/gcpnfsvolumes/translations
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/ipranges/details
  config/ui-extensions/ipranges/translations
Labels: size/L, lgtm, cla: yes

#263 feat(AwsNfsVolume): automaticaly create and label PVC
  api/cloud-resources/v1beta1/awsnfsvolume_types.go
  api/cloud-resources/v1beta1/condition.go
  api/cloud-resources/v1beta1/labels.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  internal/controller/cloud-resources/awsnfsvolume_test.go
  internal/controller/cloud-resources/cr/suite_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/skr/awsnfsvolume/createPersistentVolumeClaim.go
  pkg/skr/awsnfsvolume/createVolume.go
  pkg/skr/awsnfsvolume/deletePVC.go
  pkg/skr/awsnfsvolume/loadVolumeClaim.go
  pkg/skr/awsnfsvolume/reconciler.go
  pkg/skr/awsnfsvolume/requeueWaitKcpStatus.go
  pkg/skr/awsnfsvolume/sanitizeRelasedVolume.go
  pkg/skr/awsnfsvolume/sanitizeRelasedVolume_test.go
  pkg/skr/awsnfsvolume/state.go
  pkg/skr/awsnfsvolume/state_test.go
  pkg/skr/awsnfsvolume/util.go
  pkg/skr/awsnfsvolume/waitPVCDeleted.go
  pkg/testinfra/dsl/awsNfsVolume.go
  pkg/testinfra/pvcController.go
  pkg/util/labels.go
  pkg/util/labels_test.go
Labels: size/XXL, lgtm, cla: yes

#274 feat(GCPVpcPeering): SKR GCP create VPCPeering
  api/cloud-resources/v1beta1/gcpvpcpeering_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_gcpvpcpeering.yaml
  config/sync.sh
  internal/controller/cloud-resources/gcpvpcpeering_controller.go
  pkg/skr/gcpvpcpeering/addFinalizer.go
  pkg/skr/gcpvpcpeering/createKcpVpcPeering.go
  pkg/skr/gcpvpcpeering/loadKcpGcpVpcPeering.go
  pkg/skr/gcpvpcpeering/reconciler.go
  pkg/skr/gcpvpcpeering/state.go
  pkg/skr/gcpvpcpeering/updateStatus.go
  tools/demo/gcpvpcpeering/skr-gcp-vpcpeering.yaml
Labels: size/XL, lgtm, cla: yes

#275 (feat) AWSnfsvolumes ui
  Makefile
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/sync.sh
  config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/ui-extensions/awsnfsvolumes/details
  config/ui-extensions/awsnfsvolumes/general
  config/ui-extensions/awsnfsvolumes/kustomization.yaml
  config/ui-extensions/awsnfsvolumes/list
  config/ui-extensions/awsnfsvolumes/translations
  config/ui-extensions/kustomization.yaml
Labels: size/L, lgtm, cla: yes

#276 chore: Remove Disabled CRDs flag
  config/manager/kustomization.yaml
  internal/controller/cloud-resources/gcpnfsvolumebackup_controller.go
  internal/controller/cloud-resources/gcpnfsvolumerestore_controller.go
  pkg/util/featureFlag.go
Labels: size/M, lgtm, cla: yes

#278 (feat) gcp vpcpeering UI
  Makefile
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/sync.sh
  config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/gcpvpcpeerings/details
  config/ui-extensions/gcpvpcpeerings/form
  config/ui-extensions/gcpvpcpeerings/general
  config/ui-extensions/gcpvpcpeerings/kustomization.yaml
  config/ui-extensions/gcpvpcpeerings/list
  config/ui-extensions/gcpvpcpeerings/translations
Labels: size/L, lgtm, cla: yes

#281 (feat) added iprange ui to aws provider
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/sync.sh
Labels: size/M, lgtm, cla: yes

#282 fix(IpRange): handle potential error on kcp iprangrange cidr parse
  pkg/kcp/provider/aws/iprange/v1/checkCidrOverlap.go
Labels: size/XS, lgtm, cla: yes

#283 add more logs to modify persistence volume action
  pkg/skr/gcpnfsvolume/modifyPersistenceVolume.go
Labels: size/S, lgtm, cla: yes

#285 (feat) UI Form Polish
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/ui-extensions/awsnfsvolumes/details
  config/ui-extensions/awsnfsvolumes/form
  config/ui-extensions/awsnfsvolumes/translations
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/form
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/form
  config/ui-extensions/gcpnfsvolumebackups/translations
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/form
  config/ui-extensions/gcpnfsvolumerestores/translations
  config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/gcpvpcpeerings/form
Labels: size/XL, lgtm, cla: yes

#286 (feat) updated gcpnfsvolume_types.go so Tier is now an enum
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
Labels: size/S, lgtm, cla: yes

#284 return empty map for annotations if PV(C) does not exist
  pkg/skr/gcpnfsvolume/modifyPersistenceVolume.go
  pkg/skr/gcpnfsvolume/util.go
Labels: size/M, lgtm, cla: yes

#288 fix(GcpNfsVolume): consider annotations equal if actual is superset o…
  pkg/skr/gcpnfsvolume/modifyPersistenceVolume.go
  pkg/skr/gcpnfsvolume/modifyPersistentVolumeClaim.go
  pkg/skr/gcpnfsvolume/util.go
Labels: size/M, lgtm, cla: yes

#289 (chore) updating sec-scanners-config to 0.1.10
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#290 fix(GcpNfsVolume): ensure Error state is set if GcpNfsVolume specifie…
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  pkg/skr/gcpnfsvolume/loadPersistentVolumeClaim.go
  pkg/skr/gcpnfsvolume/loadPersistentVolumeClaim_test.go
Labels: size/M, lgtm, cla: yes

#292 chore(GcpNfsVolume): update scenario test to confirm finalizers are added to PV and PVC
  internal/controller/cloud-resources/gcpnfsvolume_test.go
Labels: size/XS, lgtm, cla: yes

#291 feat(AwsNfsVolume): add finalizer to PV and PVC
  internal/controller/cloud-resources/awsnfsvolume_test.go
  pkg/skr/awsnfsvolume/createPersistentVolumeClaim.go
  pkg/skr/awsnfsvolume/createVolume.go
  pkg/skr/awsnfsvolume/reconciler.go
  pkg/skr/awsnfsvolume/removePersistenceVolumeClaimFinalizer.go
  pkg/skr/awsnfsvolume/removePersistenceVolumeFinalizer.go
Labels: size/M, lgtm, cla: yes

#293 feat(NfsBackupSchedule): CRD APIs for scheduled nfs backups
  PROJECT
  api/cloud-resources/v1beta1/nfsbackupschedule_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_nfsbackupschedules.yaml
  config/crd/kustomization.yaml
  config/rbac/cloud-resources_nfsbackupschedule_editor_role.yaml
  config/rbac/cloud-resources_nfsbackupschedule_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_nfsbackupschedule.yaml
  config/samples/kustomization.yaml
  internal/controller/cloud-resources/nfsbackupschedule_controller.go
  internal/controller/cloud-resources/suite_test.go
Labels: size/XL, lgtm, cla: yes

#295 (chore) Added missing Status on List and Detail
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/details
  config/ui-extensions/gcpnfsvolumes/list
  config/ui-extensions/gcpnfsvolumes/translations
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/ipranges/list
  config/ui-extensions/ipranges/translations
Labels: size/M, lgtm, cla: yes

#299 fix(GcpNfsVolume): fix validatePV and add tests for it
  pkg/skr/gcpnfsvolume/validatePV.go
  pkg/skr/gcpnfsvolume/validatePV_test.go
Labels: size/L, lgtm, cla: yes

#300 chore(GcpNfsVolume): change validatePV and validatePVC error msg format
  pkg/skr/gcpnfsvolume/validatePV.go
  pkg/skr/gcpnfsvolume/validatePVC.go
Labels: size/XS, lgtm, cla: yes

#301 feat(AwsNfsVolume): validate PersistentVolume and PersistentVolumeClaim
  pkg/skr/awsnfsvolume/createPersistentVolumeClaim.go
  pkg/skr/awsnfsvolume/createVolume.go
  pkg/skr/awsnfsvolume/reconciler.go
  pkg/skr/awsnfsvolume/util.go
  pkg/skr/awsnfsvolume/validatePersistentVolume.go
  pkg/skr/awsnfsvolume/validatePersistentVolumeClaim.go
  pkg/skr/awsnfsvolume/validatePersistentVolumeClaim_test.go
  pkg/skr/awsnfsvolume/validatePersistentVolume_test.go
Labels: size/L, lgtm, cla: yes

#296 feat(KCP IpRange): automatic IpRange allocation for GCP
  api/cloud-control/v1beta1/scope_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  internal/controller/cloud-control/iprange_gcp_test.go
  pkg/kcp/provider/gcp/iprange/new.go
  pkg/kcp/provider/gcp/iprange/state.go
  pkg/kcp/provider/gcp/iprange/v1/checkGcpOperation.go
  pkg/kcp/provider/gcp/iprange/v1/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/iprange/v1/compareStates.go
  pkg/kcp/provider/gcp/iprange/v1/compareStates_test.go
  pkg/kcp/provider/gcp/iprange/v1/loadAddress.go
  pkg/kcp/provider/gcp/iprange/v1/loadAddress_test.go
  pkg/kcp/provider/gcp/iprange/v1/loadPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v1/loadPsaConnection_test.go
  pkg/kcp/provider/gcp/iprange/v1/new.go
  pkg/kcp/provider/gcp/iprange/v1/state.go
  pkg/kcp/provider/gcp/iprange/v1/state_test.go
  pkg/kcp/provider/gcp/iprange/v1/syncAddress.go
  pkg/kcp/provider/gcp/iprange/v1/syncAddress_test.go
  pkg/kcp/provider/gcp/iprange/v1/syncPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v1/syncPsaConnection_test.go
  pkg/kcp/provider/gcp/iprange/v1/updateState.go
  pkg/kcp/provider/gcp/iprange/v1/updateState_test.go
  pkg/kcp/provider/gcp/iprange/v1/validateCidr.go
  pkg/kcp/provider/gcp/iprange/v1/validateCidr_test.go
  pkg/kcp/provider/gcp/iprange/v2/allocateIpRange.go
  pkg/kcp/provider/gcp/iprange/v2/allocateIpRange_test.go
  pkg/kcp/provider/gcp/iprange/v2/checkGcpOperation.go
  pkg/kcp/provider/gcp/iprange/v2/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/iprange/v2/compareStates.go
  pkg/kcp/provider/gcp/iprange/v2/compareStates_test.go
  pkg/kcp/provider/gcp/iprange/v2/copyCidrToStatus.go
  pkg/kcp/provider/gcp/iprange/v2/copyCidrToStatus_test.go
  pkg/kcp/provider/gcp/iprange/v2/loadAddress.go
  pkg/kcp/provider/gcp/iprange/v2/loadAddress_test.go
  pkg/kcp/provider/gcp/iprange/v2/loadPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v2/loadPsaConnection_test.go
  pkg/kcp/provider/gcp/iprange/v2/new.go
  pkg/kcp/provider/gcp/iprange/v2/preventCidrEdit.go
  pkg/kcp/provider/gcp/iprange/v2/preventCidrEdit_test.go
  pkg/kcp/provider/gcp/iprange/v2/state.go
  pkg/kcp/provider/gcp/iprange/v2/state_test.go
  pkg/kcp/provider/gcp/iprange/v2/syncAddress.go
  pkg/kcp/provider/gcp/iprange/v2/syncAddress_test.go
  pkg/kcp/provider/gcp/iprange/v2/syncPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v2/syncPsaConnection_test.go
  pkg/kcp/provider/gcp/iprange/v2/updateState.go
  pkg/kcp/provider/gcp/iprange/v2/updateState_test.go
  pkg/kcp/provider/gcp/iprange/v2/validateCidr.go
  pkg/kcp/provider/gcp/iprange/v2/validateCidr_test.go
  pkg/kcp/scope/createScopeGcp.go
  pkg/testinfra/dsl.go
Labels: size/XXL, lgtm, cla: yes

#303 feat(GcpNfsVolume): optional iprange
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
  pkg/skr/gcpnfsvolume/deletePVForNameChange.go
  pkg/skr/gcpnfsvolume/deletePersistenceVolume.go
  pkg/skr/gcpnfsvolume/deletePersistentVolumeClaim.go
  pkg/skr/gcpnfsvolume/loadKcpIpRange.go
  pkg/skr/gcpnfsvolume/loadKcpIpRange_test.go
  pkg/skr/gcpnfsvolume/reconciler.go
  pkg/skr/gcpnfsvolume/state.go
  pkg/skr/gcpnfsvolume/state_test.go
  pkg/skr/gcpnfsvolume/updateStatus.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/testinfra/dsl/gcpNfsVolume.go
Labels: size/L, lgtm, cla: yes

#297 feat (AzureVpcPeering): Handles object deletion
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/mock/storeSubscriptionContext.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/new.go
  pkg/kcp/provider/azure/vpcpeering/removeFinalizer.go
  pkg/kcp/provider/azure/vpcpeering/removeReadyCondition.go
  pkg/skr/azurevpcpeering/deleteKcpVpcPeering.go
  pkg/skr/azurevpcpeering/loadKcpAzureVpcPeering.go
  pkg/skr/azurevpcpeering/reconciler.go
  pkg/skr/azurevpcpeering/removeFinalizer.go
  pkg/skr/azurevpcpeering/updateStatus.go
Labels: size/L, lgtm, cla: yes

#305 feat(GCPVpcPeering) Adding remote network tag check
  go.mod
  go.sum
  internal/controller/cloud-control/vpcpeering_controller.go
  pkg/kcp/provider/gcp/cloudclient/provider.go
  pkg/kcp/provider/gcp/mock/server.go
  pkg/kcp/provider/gcp/mock/type.go
  pkg/kcp/provider/gcp/vpcpeering/client/cloudComputeClient.go
  pkg/kcp/provider/gcp/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/gcp/vpcpeering/state.go
  pkg/skr/gcpvpcpeering/createKcpVpcPeering.go
  pkg/skr/gcpvpcpeering/updateStatus.go
Labels: size/L, lgtm, cla: yes
