Repository kyma-project/cloud-manager, pull requests merged in 2024-10, with the labels that each got.

#673 chore: KCP Scope refactoring
  Makefile
  api/cloud-control/v1beta1/scope_types.go
  config/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  pkg/kcp/scope/addKymaFinalizer.go
  pkg/kcp/scope/addReadyCondition.go
  pkg/kcp/scope/checkGcpOperations.go
  pkg/kcp/scope/enableApisGcp.go
  pkg/kcp/scope/findKymaModuleState.go
  pkg/kcp/scope/loadNetworks.go
  pkg/kcp/scope/predicates.go
  pkg/kcp/scope/reconciler.go
  pkg/kcp/scope/removeKymaFinalizer.go
  pkg/testinfra/run.go
Labels: size/L, lgtm, cla: yes

#677 fix: KCP Managed Network for Azure vnet name
  internal/controller/cloud-control/network_azure_test.go
  pkg/common/network.go
  pkg/kcp/iprange/kcpNetworkInit.go
  pkg/kcp/network/preventCreationOfNonCmManagedNetwork.go
  pkg/kcp/network/reconciler.go
  pkg/kcp/provider/azure/network/initState.go
  pkg/kcp/provider/azure/network/state.go
  pkg/kcp/provider/azure/network/statusReady.go
  pkg/kcp/provider/azure/network/vnetCreate.go
  pkg/kcp/provider/azure/network/vnetDelete.go
  pkg/kcp/provider/azure/network/vnetLoad.go
Labels: size/L, cla: yes

#676 feat(AzureVpcPeering): delete remote peering
  api/cloud-control/v1beta1/vpcpeering_builder.go
  api/cloud-control/v1beta1/vpcpeering_types.go
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  internal/api-tests/vpcpeering_test.go
  internal/controller/cloud-control/vpcpeering_aws_test.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/new.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteDelete.go
  pkg/skr/azurevpcpeering/createKpcVpcPeering.go
Labels: size/M, lgtm, cla: yes

#671 docs: contributor AWS permissions
  .github/workflows/pr-lint-permissions.yml
  ci/docs-permission-sorter.js
  docs/contributor/aws-permissions.md
Labels: size/L, lgtm, cla: yes

#670 docs: contributor GCP permissions
  .github/workflows/pr-lint-permissions.yml
  docs/contributor/gcp-permissions.md
Labels: size/M, lgtm, cla: yes

#682 feat: Add proper categories for CRDs
  api/cloud-resources/v1beta1/awsnfsvolume_types.go
  api/cloud-resources/v1beta1/awsnfsvolumebackup_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  api/cloud-resources/v1beta1/awsvpcpeering_types.go
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  api/cloud-resources/v1beta1/cceenfsvolume_types.go
  api/cloud-resources/v1beta1/cloudresources_types.go
  api/cloud-resources/v1beta1/gcpnfsbackupschedule_types.go
  api/cloud-resources/v1beta1/gcpnfsvolume_types.go
  api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
  api/cloud-resources/v1beta1/gcpnfsvolumerestore_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  api/cloud-resources/v1beta1/gcpvpcpeering_types.go
  api/cloud-resources/v1beta1/iprange_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumebackups.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_cceenfsvolumes.yaml
  config/crd/bases/cloud-resources.kyma-project.io_cloudresources.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/cloud-resources.kyma-project.io_cloudresources.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumebackups.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_ipranges.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
  config/patchAfterMakeManifests.sh
Labels: size/XXL, lgtm, cla: yes

#684 chore(AwsNfsBackupSchedule): add category to cloud-resource
  api/cloud-resources/v1beta1/awsnfsbackupschedule_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
  config/patchAfterMakeManifests.sh
Labels: size/S, lgtm, cla: yes

#679 fix(scope): hardening gcp enableApis and check operation status
  pkg/kcp/scope/checkGcpOperations.go
  pkg/kcp/scope/enableApisGcp.go
Labels: size/M, lgtm, cla: yes

#685 docs(GcpRedisInstance,AwsRedisInstance): fix tutorial
  docs/user/tutorials/01-60-gcp-redis-instance.md
  docs/user/tutorials/01-70-aws-redis-instance.md
Labels: size/S, lgtm, cla: yes

#688 (feat): 20241004 UI parity
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/details
  config/ui-extensions/awsvpcpeerings/form
  config/ui-extensions/awsvpcpeerings/translations
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/details
  config/ui-extensions/azurevpcpeerings/form
  config/ui-extensions/azurevpcpeerings/list
  config/ui-extensions/azurevpcpeerings/translations
Labels: size/M, lgtm, cla: yes

#690 test(BackupSchedule): Fix long running and flaky integration tests
  internal/controller/cloud-resources/aws/awsnfsbackupschedule_test.go
  internal/controller/cloud-resources/gcpnfsbackupschedule_test.go
  pkg/skr/backupschedule/calculateOnetimeSchedule.go
  pkg/skr/backupschedule/calculateRecurringSchedule.go
  pkg/skr/backupschedule/checkCompleted.go
  pkg/skr/backupschedule/checkSuspension.go
  pkg/skr/backupschedule/compare.go
  pkg/skr/backupschedule/createBackup.go
  pkg/skr/backupschedule/createBackup_test.go
  pkg/skr/backupschedule/deleteBackups.go
  pkg/skr/backupschedule/deleteBackups_test.go
  pkg/skr/backupschedule/deleteCascade.go
  pkg/skr/backupschedule/evaluateNextRun.go
  pkg/skr/backupschedule/loadSource.go
  pkg/skr/backupschedule/reconciler.go
  pkg/skr/backupschedule/removeFinalizer.go
  pkg/skr/backupschedule/state.go
  pkg/skr/backupschedule/validateTimes.go
Labels: size/L, lgtm, cla: yes

#686 feat: cleanup orphan KCP resources when Kyma deleted
  PROJECT
  api/cloud-control/v1beta1/nuke_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_nukes.yaml
  config/crd/kustomization.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_nukes.yaml
  config/rbac/cloud-control_nuke_editor_role.yaml
  config/rbac/cloud-control_nuke_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/samples/cloud-control_v1beta1_nuke.yaml
  config/samples/kustomization.yaml
  internal/controller/cloud-control/nuke_controller.go
  internal/controller/cloud-control/nuke_controller_test.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/nuke/allDeleted.go
  pkg/kcp/nuke/deleteResources.go
  pkg/kcp/nuke/loadResources.go
  pkg/kcp/nuke/reconciler.go
  pkg/kcp/nuke/state.go
  pkg/kcp/nuke/statusDeleted.go
  pkg/kcp/nuke/statusDeleting.go
  pkg/kcp/nuke/statusDiscovered.go
  pkg/kcp/redisinstance/ignorant.go
  pkg/kcp/redisinstance/reconciler.go
  pkg/kcp/scope/loadKyma.go
  pkg/kcp/scope/state.go
  pkg/testinfra/dsl/commonAssertions.go
Labels: size/XXL, cla: yes

#691 fix: Nuke deletes Scope when completed
  internal/controller/cloud-control/nuke_controller_test.go
  pkg/kcp/nuke/allDeleted.go
  pkg/kcp/nuke/checkIfAllDeleted.go
  pkg/kcp/nuke/reconciler.go
  pkg/kcp/nuke/resourceStatusDeleted.go
  pkg/kcp/nuke/resourceStatusDeleting.go
  pkg/kcp/nuke/resourceStatusDiscovered.go
  pkg/kcp/nuke/scopeDelete.go
  pkg/kcp/nuke/statusCompleted.go
Labels: size/L, cla: yes

#692 fix: do not create Nuke if Scope does not exist
  pkg/kcp/scope/loadKyma.go
Labels: size/S, cla: yes

#693 fix: copy Kyma labels to Scope
  api/cloud-control/v1beta1/scope_types.go
  internal/controller/cloud-control/scope_aws_test.go
  internal/controller/cloud-control/scope_azure_test.go
  internal/controller/cloud-control/scope_gcp_test.go
  pkg/feature/context.go
  pkg/feature/context_test.go
  pkg/kcp/nuke/scopeDelete.go
  pkg/kcp/scope/ensureScopeCommonFields.go
  pkg/kcp/scope/findShootName.go
  pkg/kcp/scope/loadKyma.go
  pkg/kcp/scope/predicates.go
  pkg/kcp/scope/skrActivate.go
  pkg/kcp/scope/skrDeactivate.go
  pkg/skr/runtime/looper/skrLooper.go
  pkg/testinfra/dsl/kyma.go
Labels: size/L, lgtm, cla: yes

#695 feat(RedisInstance): implement CloneForPatchStatus method
  api/cloud-control/v1beta1/redisinstance_types.go
Labels: size/S, lgtm, cla: yes

#697 (feat) disabled deleteRemotePeering field fo Azure and AWS
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/details
  config/ui-extensions/awsvpcpeerings/form
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/details
  config/ui-extensions/azurevpcpeerings/form
Labels: size/M, lgtm, cla: yes

#698 fix: Azure IpRange fix log message for security group
  pkg/kcp/provider/azure/iprange/securityGroupLoad.go
Labels: size/XS, cla: yes

#701 fix: Azure IpRange use default creds
  pkg/kcp/provider/azure/iprange/state.go
Labels: size/XS, cla: yes

#681 chore: refactor azure permissions and add to permission lint
  .github/workflows/pr-lint-permissions.yml
  docs/contributor/azure-permissions.md
Labels: size/M, lgtm, cla: yes

#694 test(AwsRedisInstance): refactor elastiCacheClientFake to use single mutex
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
Labels: size/L, cla: yes

#696 refactor(GcpRedisInstance): use UpdateStatus to PatchStatus
  pkg/kcp/provider/gcp/redisinstance/addUpdatingCondition.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
  pkg/kcp/provider/gcp/redisinstance/loadRedis.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go
  pkg/kcp/provider/gcp/redisinstance/updateRedis.go
  pkg/kcp/provider/gcp/redisinstance/updateStatus.go
  pkg/kcp/provider/gcp/redisinstance/updateStatusId.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisAvailable.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisDeleted.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/skr/gcpredisinstance/deleteAuthSecret.go
  pkg/skr/gcpredisinstance/deleteKcpRedisInstance.go
  pkg/skr/gcpredisinstance/loadAuthSecret.go
  pkg/skr/gcpredisinstance/updateId.go
  pkg/skr/gcpredisinstance/updateStatus.go
  pkg/skr/gcpredisinstance/waitKcpRedisInstanceDeleted.go
Labels: size/M, lgtm, cla: yes

#661 docs(AwsVpcPeering): documentation
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/04-40-10-azure-vpc-peering.md
  docs/user/resources/04-70-10-aws-vpc-peering.md
  docs/user/resources/README.md
  docs/user/tutorials/01-40-aws-vpc-peering.md
  docs/user/tutorials/README.md
Labels: size/L, cla: yes

#702 chore: patch status can remove condition
  internal/api-tests/patch_status_test.go
Labels: size/M, lgtm, cla: yes

#703 refactor(AwsRedisInstance): replace UpdateStatus with PatchStatus
  pkg/kcp/provider/aws/redisinstance/addUpdatingCondition.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/loadSecurityGroup.go
  pkg/kcp/provider/aws/redisinstance/removeReadyCondition.go
  pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/updateStatus.go
  pkg/kcp/provider/aws/redisinstance/updateStatusId.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
  pkg/kcp/provider/aws/redisinstance/waitUserGroupDeleted.go
  pkg/skr/awsredisinstance/createKcpRedisInstance.go
  pkg/skr/awsredisinstance/deleteAuthSecret.go
  pkg/skr/awsredisinstance/deleteKcpRedisInstance.go
  pkg/skr/awsredisinstance/loadAuthSecret.go
  pkg/skr/awsredisinstance/updateId.go
  pkg/skr/awsredisinstance/updateStatus.go
  pkg/skr/awsredisinstance/waitKcpRedisInstanceDeleted.go
Labels: size/M, lgtm, cla: yes

#710 feat(AwsRedisInstance): set AtRestEncryptionEnabled to true
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
Labels: size/XS, lgtm, cla: yes

#708 chore(AwsVpcPeering): route table tests
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/mock/routeTablesStore.go
  pkg/kcp/provider/aws/mock/vpcPeeringStore.go
  pkg/kcp/provider/aws/vpcpeering/client/client.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
  pkg/testinfra/dsl/kcpVpcPeering.go
Labels: size/L, lgtm, cla: yes

#597 chore: enable GcpRedisInstance on stage
  config/featureToggles/featureToggles.yaml
Labels: size/XS, lgtm, cla: yes

#617 chore: enable AwsRedisInstance on stage
  config/featureToggles/featureToggles.yaml
Labels: size/XS, lgtm, cla: yes

#714 (feat) UI Auto-Update
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/sync.sh
  config/ui-extensions/awsnfsvolumebackups/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
  config/ui-extensions/awsnfsvolumebackups/kustomization.yaml
  config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/ui-extensions/awsnfsvolumes/kustomization.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/kustomization.yaml
  config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/kustomization.yaml
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/kustomization.yaml
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/kustomization.yaml
  config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/gcpnfsbackupschedules/kustomization.yaml
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/kustomization.yaml
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/kustomization.yaml
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/kustomization.yaml
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/kustomization.yaml
  config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/gcpvpcpeerings/kustomization.yaml
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/ipranges/kustomization.yaml
Labels: size/M, cla: yes

#716 chore: block PRs if they have blocking label
  .github/workflows/pr-check-block-via-labels.yaml
Labels: size/M, cla: yes

#715 feat(AwsRedisInstance): update auth secret on data change
  pkg/kcp/provider/aws/redisinstance/updateStatus.go
  pkg/skr/awsredisinstance/modifyAuthSecret.go
  pkg/skr/awsredisinstance/reconciler.go
  pkg/skr/awsredisinstance/util.go
Labels: size/M, lgtm, cla: yes

#719 fix: security issue 124386
  pkg/kcp/iprange/allocate/allocate.go
Labels: size/XS, cla: yes

#723 feat(GcpRedisInstance): set in-transit encryption to always on
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-control/redisinstance_gcp_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/gcpRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#724 feat(AwsRedisInstance): set in transit encryption to enabled always
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-resources/awsredisinstance_test.go
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/modifyTransitEncryptionEnabled.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/skr/awsredisinstance/createKcpRedisInstance.go
  pkg/skr/awsredisinstance/modifyKcpRedisInstance.go
  pkg/skr/awsredisinstance/state.go
  pkg/testinfra/dsl/awsRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#726 (feat) removed transitEncryptionEnabled and transitEncryptionMode
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/details
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsredisinstances/kustomization.yaml
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/details
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpredisinstances/kustomization.yaml
Labels: size/M, lgtm, cla: yes

#733 fix: provider in ff context
  pkg/skr/runtime/looper/runner.go
  pkg/testinfra/env.go
  pkg/util/string.go
  pkg/util/string_test.go
Labels: size/M, lgtm, cla: yes

#722 feat(AwsVpcPeering): allows VpcPeering to be deleted if remote Network is missing
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/vpcpeering/createRemoteClient.go
  pkg/kcp/provider/aws/vpcpeering/kcpNetworkRemoteLoad.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteRouteTables.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpcPeeringConnection.go
Labels: size/L, lgtm, cla: yes

#736 (feat) added status.state to all List and Detail
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/awsnfsvolumebackups/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
  config/ui-extensions/awsnfsvolumebackups/details
  config/ui-extensions/awsnfsvolumebackups/kustomization.yaml
  config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/ui-extensions/awsnfsvolumes/kustomization.yaml
  config/ui-extensions/awsnfsvolumes/list
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/details
  config/ui-extensions/awsredisinstances/kustomization.yaml
  config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/details
  config/ui-extensions/awsvpcpeerings/kustomization.yaml
  config/ui-extensions/awsvpcpeerings/list
  config/ui-extensions/awsvpcpeerings/translations
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/details
  config/ui-extensions/azureredisinstances/kustomization.yaml
  config/ui-extensions/azureredisinstances/translations
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/kustomization.yaml
  config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/gcpnfsbackupschedules/details
  config/ui-extensions/gcpnfsbackupschedules/kustomization.yaml
  config/ui-extensions/gcpnfsbackupschedules/translations
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/kustomization.yaml
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/kustomization.yaml
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/kustomization.yaml
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/kustomization.yaml
  config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/gcpvpcpeerings/kustomization.yaml
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/ipranges/kustomization.yaml
Labels: size/L, lgtm, cla: yes

#740 fix(RedisInstance): adjust patchstatus for conditions
  api/cloud-control/v1beta1/redisinstance_types.go
  internal/api-tests/kcp_redisinstance_test.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
  pkg/kcp/provider/gcp/redisinstance/loadRedis.go
Labels: size/L, lgtm, cla: yes

#741 feat(AzureRedis): remove EnableNonSslPort, force it to default
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-control/redisinstance_azure_test.go
  internal/controller/cloud-resources/azureredisinstance_test.go
  pkg/kcp/provider/azure/mock/redisStore.go
  pkg/kcp/provider/azure/redisinstance/createRedis.go
  pkg/kcp/provider/azure/redisinstance/updateStatus.go
  pkg/skr/azureredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/azureRedisInstance.go
Labels: size/M, lgtm, cla: yes

#735 docs(AzureRedis): add missing spn permissions
  docs/contributor/azure-permissions.md
Labels: size/XS, lgtm, cla: yes

#734 docs(GcpRedisInstance,AwsRedisInstance): update docs
  config/samples/cloud-resources_v1beta1_awsredisinstance.yaml
  config/samples/cloud-resources_v1beta1_gcpredisinstance.yaml
  docs/user/resources/04-60-gcp-redis-instance.md
  docs/user/resources/04-70-aws-redis-instance.md
  docs/user/tutorials/01-60-gcp-redis-instance.md
  docs/user/tutorials/01-70-aws-redis-instance.md
  pkg/feature/README.md
Labels: size/M, lgtm, cla: yes

#742 feat(AzureRedis): remove zonal configuration option
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/patchAfterMakeManifests.sh
  pkg/skr/azureredisinstance/createKcpRedisInstance.go
Labels: size/S, lgtm, cla: yes

#743 Peering/aws/tutorial update
  docs/user/tutorials/01-40-aws-vpc-peering.md
Labels: size/S, cla: yes

#746 (feat): AWSVolumeRestores & AWSNFSBackupSchedules UI
  Makefile
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumerestores_ui.yaml
  config/sync.sh
  config/ui-extensions/awsnfsbackupschedules/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
  config/ui-extensions/awsnfsbackupschedules/details
  config/ui-extensions/awsnfsbackupschedules/form
  config/ui-extensions/awsnfsbackupschedules/general
  config/ui-extensions/awsnfsbackupschedules/kustomization.yaml
  config/ui-extensions/awsnfsbackupschedules/list
  config/ui-extensions/awsnfsbackupschedules/translations
  config/ui-extensions/awsnfsvolumerestores/cloud-resources.kyma-project.io_awsnfsvolumerestores_ui.yaml
  config/ui-extensions/awsnfsvolumerestores/details
  config/ui-extensions/awsnfsvolumerestores/form
  config/ui-extensions/awsnfsvolumerestores/general
  config/ui-extensions/awsnfsvolumerestores/kustomization.yaml
  config/ui-extensions/awsnfsvolumerestores/list
  config/ui-extensions/awsnfsvolumerestores/translations
Labels: size/XL, lgtm, cla: yes

#745 (feat) removed enableNonSslPort and zonal-configuration for azureredisinstances
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/details
  config/ui-extensions/azureredisinstances/form
  config/ui-extensions/azureredisinstances/kustomization.yaml
Labels: size/M, lgtm, cla: yes

#749 fix(GcpRedisInstance,AwsRedisInstance): go back to UpdateStatus
  pkg/kcp/provider/aws/redisinstance/addUpdatingCondition.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/loadSecurityGroup.go
  pkg/kcp/provider/aws/redisinstance/removeReadyCondition.go
  pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/updateStatus.go
  pkg/kcp/provider/aws/redisinstance/updateStatusId.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
  pkg/kcp/provider/aws/redisinstance/waitUserGroupDeleted.go
  pkg/kcp/provider/gcp/redisinstance/addUpdatingCondition.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
  pkg/kcp/provider/gcp/redisinstance/loadRedis.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go
  pkg/kcp/provider/gcp/redisinstance/updateRedis.go
  pkg/kcp/provider/gcp/redisinstance/updateStatus.go
  pkg/kcp/provider/gcp/redisinstance/updateStatusId.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisAvailable.go
  pkg/kcp/provider/gcp/redisinstance/waitRedisDeleted.go
  pkg/skr/awsredisinstance/createKcpRedisInstance.go
  pkg/skr/awsredisinstance/deleteAuthSecret.go
  pkg/skr/awsredisinstance/deleteKcpRedisInstance.go
  pkg/skr/awsredisinstance/loadAuthSecret.go
  pkg/skr/awsredisinstance/updateId.go
  pkg/skr/awsredisinstance/updateStatus.go
  pkg/skr/awsredisinstance/waitKcpRedisInstanceDeleted.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/skr/gcpredisinstance/deleteAuthSecret.go
  pkg/skr/gcpredisinstance/deleteKcpRedisInstance.go
  pkg/skr/gcpredisinstance/loadAuthSecret.go
  pkg/skr/gcpredisinstance/updateId.go
  pkg/skr/gcpredisinstance/updateStatus.go
  pkg/skr/gcpredisinstance/waitKcpRedisInstanceDeleted.go
Labels: size/M, lgtm, cla: yes

#748 fix(AwsNfsBackupSchedule): Remove location
  api/cloud-resources/v1beta1/awsnfsbackupschedule_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
  config/patchAfterMakeManifests.sh
Labels: size/S, lgtm, cla: yes

#753 chore: cli tool status patch and update
  .gitignore
  cmd/cli/cmdStatus.go
  cmd/cli/cmdStatusPatch.go
  cmd/cli/cmdStatusUpdate.go
Labels: size/L, cla: yes

#751 fix(AzureVpcPeering): fixes deletion of local VPC peering
  api/cloud-control/v1beta1/vpcpeering_builder.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
Labels: size/S, cla: yes

#756 chore: print serialized object
  pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go
Labels: size/S, lgtm, cla: yes

#755 fix: drop support for old Redis on GCP
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
Labels: size/S, lgtm, cla: yes

#744 feat(Azureredis): remove replicasPerPrimary
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/patchAfterMakeManifests.sh
  pkg/kcp/provider/azure/redisinstance/createRedis.go
  pkg/skr/azureredisinstance/createKcpRedisInstance.go
Labels: size/M, lgtm, cla: yes

#757 Revert "chore: print serialized object (#756)"
  pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go
Labels: size/S, lgtm, cla: yes

#758 docs(GcpRedisInstance,AwsRedisInstance): update docs
  docs/user/resources/04-60-gcp-redis-instance.md
  docs/user/resources/04-70-aws-redis-instance.md
  docs/user/tutorials/01-60-gcp-redis-instance.md
Labels: size/XS, lgtm, cla: yes

#752 docs(AwsNfsVolumeRestore): user documentation
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/04-100-10-aws-nfs-volume-restore.md
  docs/user/resources/04-90-10-gcp-nfs-volume-restore.md
  docs/user/resources/README.md
  docs/user/tutorials/01-100-aws-nfs-volume-restore.md
  docs/user/tutorials/01-90-gcp-nfs-volume-restore.md
  docs/user/tutorials/README.md
Labels: size/L, lgtm, cla: yes

#700 (feat): Redis UI update
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsredisinstances/kustomization.yaml
  config/ui-extensions/awsredisinstances/translations
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpredisinstances/kustomization.yaml
  config/ui-extensions/gcpredisinstances/translations
Labels: size/L, lgtm, cla: yes

#750 chore(AwsVpcPeering): updating tutorial
  docs/user/tutorials/01-40-aws-vpc-peering.md
Labels: size/M, lgtm, cla: yes

#761 feat(AwsRedisInstance): add support for HA via read replicas
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
  config/samples/cloud-resources_v1beta1_awsredisinstance.yaml
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-resources/awsredisinstance_test.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/skr/awsredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/awsRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/M, lgtm, cla: yes

#763 (feat) AWS and Azure Redis Instance UI Update
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/details
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsredisinstances/kustomization.yaml
  config/ui-extensions/awsredisinstances/translations
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/details
  config/ui-extensions/azureredisinstances/form
  config/ui-extensions/azureredisinstances/kustomization.yaml
  config/ui-extensions/azureredisinstances/translations
Labels: size/M, cla: yes

#762 docs(AwsRedisInstance): add readReplica details
  docs/user/resources/04-70-aws-redis-instance.md
  docs/user/tutorials/01-70-aws-redis-instance.md
Labels: size/XS, lgtm, cla: yes

#764 fix(AwsNfsBackupSchedule): Controller not started
  api/cloud-resources/v1beta1/awsnfsbackupschedule_types.go
Labels: size/XS, lgtm, cla: yes

#765 feat(AzureRedis): prevent ip range delete when in use by redis
  internal/controller/cloud-resources/iprange_controller.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/skr/azureredisinstance/ignorant.go
  pkg/skr/iprange/preventDeleteOnAzureRedisInstanceUsage.go
  pkg/skr/iprange/reconciler.go
  pkg/testinfra/dsl/azureRedisInstance.go
  pkg/testinfra/dsl/commonIpRange.go
Labels: size/L, lgtm, cla: yes

#766 fix(AzureRedis): remove odd param causing panic
  pkg/kcp/provider/azure/iprange/privateDnsZoneCreate.go
Labels: size/XS, lgtm, cla: yes

#768 (fix): fix UI ConfigMap body not copying over
  pkg/skr/runtime/looper/installer.go
Labels: size/XS, lgtm, cla: yes

#769 (fix) fixed error where it was trying to copy "body" field instead of "data"
  pkg/skr/runtime/looper/installer.go
Labels: size/XS, cla: yes

#767 (chore): bump version of AWS Redis Instance UI
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/awsnfsbackupschedules/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
  config/ui-extensions/awsnfsbackupschedules/kustomization.yaml
  config/ui-extensions/awsnfsvolumebackups/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
  config/ui-extensions/awsnfsvolumebackups/kustomization.yaml
  config/ui-extensions/awsnfsvolumerestores/cloud-resources.kyma-project.io_awsnfsvolumerestores_ui.yaml
  config/ui-extensions/awsnfsvolumerestores/kustomization.yaml
  config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
  config/ui-extensions/awsnfsvolumes/kustomization.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/kustomization.yaml
  config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/kustomization.yaml
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/kustomization.yaml
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/kustomization.yaml
  config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/gcpnfsbackupschedules/kustomization.yaml
  config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
  config/ui-extensions/gcpnfsvolumebackups/kustomization.yaml
  config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
  config/ui-extensions/gcpnfsvolumerestores/kustomization.yaml
  config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
  config/ui-extensions/gcpnfsvolumes/kustomization.yaml
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/kustomization.yaml
  config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
  config/ui-extensions/gcpvpcpeerings/kustomization.yaml
  config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
  config/ui-extensions/ipranges/kustomization.yaml
Labels: size/M, cla: yes

#771 chore(AwsVpcPeering): adds State as printable column
  api/cloud-resources/v1beta1/awsvpcpeering_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/patchAfterMakeManifests.sh
Labels: size/S, lgtm, cla: yes

#772 feat(AzureRedis): add replicasPerPrimary setting; allow P5 SKU.Capacity option
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-resources/azureredisinstance_test.go
  pkg/kcp/provider/azure/redisinstance/createRedis.go
  pkg/skr/azureredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/azureRedisInstance.go
Labels: size/M, lgtm, cla: yes

#773 feat(GcpRedisInstance): add replica count field to API
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-control/redisinstance_gcp_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/testinfra/dsl/gcpRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes
