Repository kyma-project/cloud-manager, pull requests merged in 2024-09, with the labels that each got.

#556 feat(githubAction) Build image
  .github/workflows/cloud-manager-build.yml
Labels: size/M, lgtm, cla: yes

#551 feat(AwsRedisInstance): make CacheNodeType mutable"
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/modifyCacheNodeType.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
  pkg/skr/awsredisinstance/modifyKcpRedisInstance.go
  pkg/skr/awsredisinstance/state.go
Labels: size/L, lgtm, cla: yes

#557 chore(GcpRedisInstance): add redis 7.2, and improve comments
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
Labels: size/L, lgtm, cla: yes

#545 feat(AzureVpcPeering): status.State
  api/cloud-control/v1beta1/vpcpeering_types.go
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/storeSubscriptionContext.go
  pkg/kcp/provider/azure/mock/type.go
  pkg/kcp/provider/azure/mock/vpcPeeringStore.go
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/new.go
  pkg/kcp/provider/azure/vpcpeering/updateStatus.go
  pkg/kcp/provider/azure/vpcpeering/waitVpcPeeringReady.go
  pkg/skr/azurevpcpeering/updateStatus.go
Labels: size/L, lgtm, cla: yes

#555 chore: feature flags file
  .github/workflows/pr-feature-toggles.yaml
  CODEOWNERS
  config/featureToggles/featureToggles.yaml
Labels: size/M, lgtm, cla: yes

#559 feat(AzureVpcPeering): removes allowVnetAccess
  api/cloud-control/v1beta1/vpcpeering_types.go
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
  pkg/skr/azurevpcpeering/createKpcVpcPeering.go
  pkg/testinfra/dsl/kcpVpcPeering.go
Labels: size/S, lgtm, cla: yes

#560 chore(githubAction) Build image
  .github/workflows/cloud-manager-build.yml
Labels: size/XS, lgtm, cla: yes

#562 chore(githubAction) Build image
  .github/workflows/cloud-manager-build.yml
Labels: size/XS, lgtm, cla: yes

#563 chore(githubAction) Build image
  .github/workflows/cloud-manager-build.yml
Labels: size/XS, lgtm, cla: yes

#565 chore: KCP Scope print columns
  api/cloud-control/v1beta1/scope_types.go
  config/crd/bases/cloud-control.kyma-project.io_scopes.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_scopes.yaml
Labels: size/S, lgtm, cla: yes

#561 feat(AzureVpcPeering): updates docs and samples
  config/samples/cloud-control_v1beta1_vpcpeering.yaml
  config/samples/cloud-resources_v1beta1_azurevpcpeering.yaml
  docs/user/resources/04-40-10-azure-vpc-peering.md
  docs/user/tutorials/01-30-azure-vpc-peering.md
  docs/user/tutorials/README.md
Labels: size/XS, lgtm, cla: yes

#566 chore: feature flags logger
  cmd/main.go
  internal/controller/cloud-control/nfsinstance_gcp_test.go
  pkg/common/ignorant/store.go
  pkg/composed/state.go
  pkg/feature/ffApiDisabled_test.go
  pkg/feature/ffGcpNfsVolumeAutomaticLocationAllocation.go
  pkg/feature/ffIpRangeAutomaticCidrAllocation.go
  pkg/feature/init.go
  pkg/testinfra/dsl/gcpNfsVolume.go
Labels: size/M, lgtm, cla: yes

#570 chore(AzureVpcPeering): use util.Timing
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/azure/vpcpeering/waitNetworkTag.go
Labels: size/M, lgtm, cla: yes

#571 chore: adjust gitignore for ff toggle
  .gitignore
  config/featureToggles/.gitignore
Labels: size/XS, lgtm, cla: yes

#550 fix (GCP IpRange): error when service connection has invalid ip-range…
  pkg/kcp/provider/gcp/iprange/v2/compareStates.go
  pkg/kcp/provider/gcp/iprange/v2/identifyPeeringIpRanges.go
  pkg/kcp/provider/gcp/iprange/v2/identifyPeeringIpRanges_test.go
  pkg/kcp/provider/gcp/iprange/v2/new.go
  pkg/kcp/provider/gcp/iprange/v2/syncPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v2/syncPsaConnection_test.go
Labels: size/L, lgtm, cla: yes

#519 docs: update 04-30-10-gcp-nfs-volume.md based on latest changes
  docs/user/resources/04-30-10-gcp-nfs-volume.md
Labels: size/M, lgtm, cla: yes

#535 feat(AwsVpcPeering): updates route tables
  api/cloud-control/v1beta1/vpcpeering_types.go
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/composed/errors.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/mock/routeTablesStore.go
  pkg/kcp/provider/aws/mock/server.go
  pkg/kcp/provider/aws/mock/type.go
  pkg/kcp/provider/aws/util/ec2tags.go
  pkg/kcp/provider/aws/vpcpeering/client/client.go
  pkg/kcp/provider/aws/vpcpeering/createRemoteClient.go
  pkg/kcp/provider/aws/vpcpeering/createRemoteRoutes.go
  pkg/kcp/provider/aws/vpcpeering/createRoutes.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/deleteRoutes.go
  pkg/kcp/provider/aws/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteRouteTables.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/loadRouteTables.go
  pkg/kcp/provider/aws/vpcpeering/loadVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/new.go
  pkg/kcp/provider/aws/vpcpeering/state.go
Labels: size/XL, lgtm, cla: yes

#576 feat(AwsRedisInstance): make transitEncryptionMode mutable
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/featureToggles/featureToggles.local.yaml
  config/patchAfterMakeManifests.sh
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/modifyTransitEncryptionEnabled.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/skr/awsredisinstance/modifyKcpRedisInstance.go
  pkg/skr/awsredisinstance/state.go
Labels: size/L, lgtm, cla: yes

#577 (feat) updated AWSredisinstance UI mutable
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/form
Labels: size/XS, lgtm, cla: yes

#578 feat(AwsRedisInstance) make preferredMaintenanceWindow mutable
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/mock/server.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/deleteElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/loadElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/modifyAutoMinorVersionUpgrade.go
  pkg/kcp/provider/aws/redisinstance/modifyCacheNodeType.go
  pkg/kcp/provider/aws/redisinstance/modifyPreferredMaintenanceWindow.go
  pkg/kcp/provider/aws/redisinstance/modifyTransitEncryptionEnabled.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/updateStatus.go
  pkg/kcp/provider/aws/redisinstance/updateStatusId.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
  pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
  pkg/skr/awsredisinstance/modifyKcpRedisInstance.go
  pkg/skr/awsredisinstance/state.go
Labels: size/L, lgtm, cla: yes

#581 chore(AwsVpcPeering): fixes typo in config
  pkg/kcp/provider/aws/config/config.go
Labels: size/XS, lgtm, cla: yes

#554 feat: preventing zombie filestore backups and patching status instead…
  .github/workflows/pr-checks.yml
  api/cloud-resources/v1beta1/gcpnfsbackupschedule_types.go
  api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
  api/cloud-resources/v1beta1/gcpnfsvolumerestore_types.go
  internal/controller/cloud-resources/gcpnfsbackupschedule_test.go
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  internal/controller/cloud-resources/gcpnfsvolumebackup_test.go
  internal/controller/cloud-resources/gcpnfsvolumerestore_test.go
  pkg/skr/backupschedule/addFinalizer.go
  pkg/skr/backupschedule/backupImpl.go
  pkg/skr/backupschedule/calculateOnetimeSchedule.go
  pkg/skr/backupschedule/calculateRecurringSchedule.go
  pkg/skr/backupschedule/checkCompleted.go
  pkg/skr/backupschedule/checkSuspension.go
  pkg/skr/backupschedule/createBackup.go
  pkg/skr/backupschedule/deleteBackups.go
  pkg/skr/backupschedule/deleteCascade.go
  pkg/skr/backupschedule/evaluateNextRun.go
  pkg/skr/backupschedule/loadBackups.go
  pkg/skr/backupschedule/loadScope.go
  pkg/skr/backupschedule/loadSource.go
  pkg/skr/backupschedule/state_test.go
  pkg/skr/backupschedule/validateSchedule.go
  pkg/skr/backupschedule/validateTimes.go
  pkg/skr/gcpnfsvolume/addFinalizer.go
  pkg/skr/gcpnfsvolume/deletePVForNameChange.go
  pkg/skr/gcpnfsvolume/deletePersistenceVolume.go
  pkg/skr/gcpnfsvolume/deletePersistentVolumeClaim.go
  pkg/skr/gcpnfsvolume/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolume/loadScope.go
  pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
  pkg/skr/gcpnfsvolume/setProcessing.go
  pkg/skr/gcpnfsvolume/state_test.go
  pkg/skr/gcpnfsvolume/updateStatus.go
  pkg/skr/gcpnfsvolume/validatePV.go
  pkg/skr/gcpnfsvolume/validatePVC.go
  pkg/skr/gcpnfsvolume/validateSpec.go
  pkg/skr/gcpnfsvolumebackup/addFinalizer.go
  pkg/skr/gcpnfsvolumebackup/checkBackupOperation.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadScope.go
  pkg/skr/gcpnfsvolumebackup/state_test.go
  pkg/skr/gcpnfsvolumebackup/updateStatus.go
  pkg/skr/gcpnfsvolumebackup/validateSpec.go
  pkg/skr/gcpnfsvolumerestore/addFinalizer.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolumerestore/loadScope.go
  pkg/skr/gcpnfsvolumerestore/removeFinalizer.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
  pkg/skr/gcpnfsvolumerestore/setProcessing.go
  pkg/skr/gcpnfsvolumerestore/state_test.go
  pkg/testinfra/dsl/gcpNfsVolume.go
Labels: size/L, lgtm, cla: yes

#583 fix: fix gitignore for local featureToggles file
  .gitignore
  config/featureToggles/.gitignore
  config/featureToggles/featureToggles.local.yaml
Labels: size/M, lgtm, cla: yes

#588 feat: create kyma network when scope is created
  api/cloud-control/v1beta1/network_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  internal/controller/cloud-control/scope_aws_test.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/provider/aws/iprange/client/client.go
  pkg/kcp/provider/aws/iprange/v1/loadVpc.go
  pkg/kcp/provider/aws/iprange/v2/vpcFind.go
  pkg/kcp/provider/aws/mock/vpcStore.go
  pkg/kcp/provider/aws/vpcpeering/client/client.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/loadVpc.go
  pkg/kcp/scope/createKymaNetworkReference.go
  pkg/kcp/scope/loadNetworks.go
  pkg/kcp/scope/reconciler.go
  pkg/kcp/scope/state.go
  pkg/skr/awsnfsvolumebackup/reconciler.go
  pkg/testinfra/dsl/loadAndCheck.go
Labels: size/L, lgtm, cla: yes

#586 fix(GcpNfsVolumeBackup/Restore) optional nfsvolume ref namespace
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
Labels: size/S, lgtm, cla: yes

#590 fix: GcpNfsVolume to recover from timout during creation
  config/manager/kustomization.yaml
  pkg/kcp/provider/gcp/client/gcpConstants.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState_test.go
  pkg/kcp/provider/gcp/nfsinstance/state.go
  pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance.go
  pkg/skr/gcpnfsvolume/deletePersistenceVolume.go
Labels: size/L, lgtm, cla: yes

#592 feat: network reference reconciler
  api/cloud-control/v1beta1/network_builder.go
  api/cloud-control/v1beta1/network_types.go
  api/cloud-control/v1beta1/scope_ref.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
  config/crd/bases/cloud-control.kyma-project.io_networks.yaml
  config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_networks.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  internal/api-tests/kcp_nfsinstance_test.go
  internal/api-tests/network_test.go
  internal/controller/cloud-control/iprange_aws_test.go
  internal/controller/cloud-control/iprange_gcp_test.go
  internal/controller/cloud-control/network_controller.go
  internal/controller/cloud-control/network_test.go
  internal/controller/cloud-control/nfsinstance_aws_test.go
  internal/controller/cloud-control/nfsinstance_ccee_test.go
  internal/controller/cloud-control/nfsinstance_gcp_test.go
  internal/controller/cloud-control/redisinstance_aws_test.go
  internal/controller/cloud-control/redisinstance_azure_test.go
  internal/controller/cloud-control/redisinstance_gcp_test.go
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-control/vpcpeering_aws_test.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  internal/controller/cloud-control/vpcpeering_gcp_test.go
  internal/controller/cloud-resources/aws/awsnfsvolumebackup_test.go
  internal/controller/cloud-resources/gcpnfsvolume_test.go
  pkg/common/actions/addFinalizer.go
  pkg/kcp/network/handleNetworkReference.go
  pkg/kcp/network/reconciler.go
  pkg/kcp/network/state.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/vpcpeering/waitVpcPeeringReady.go
  pkg/testinfra/dsl/awsIpRange.go
  pkg/testinfra/dsl/commonAssertions.go
  pkg/testinfra/dsl/conditions.go
  pkg/testinfra/dsl/create.go
  pkg/testinfra/dsl/kcpIpRange.go
  pkg/testinfra/dsl/kcpVpcPeering.go
  pkg/testinfra/dsl/loadAndCheck.go
  pkg/testinfra/dsl/scope.go
  pkg/testinfra/gherkin.go
  pkg/testinfra/infra.go
  pkg/testinfra/infraScheme/objToClusterType.go
  pkg/testinfra/infraScheme/scheme.go
  pkg/testinfra/infraTypes/clusterType.go
  pkg/testinfra/run.go
  pkg/testinfra/scheme.go
  pkg/testinfra/types.go
Labels: size/XL, lgtm, cla: yes

#591 fix: GCP Config to use the config pkg similar to other configs
  cmd/main.go
  config/config/gcpConfig.yaml
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/kcp/provider/gcp/client/gcpConstants.go
  pkg/kcp/provider/gcp/client/provider.go
  pkg/kcp/provider/gcp/cloudclient/provider.go
  pkg/kcp/provider/gcp/iprange/v1/checkGcpOperation.go
  pkg/kcp/provider/gcp/iprange/v1/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/iprange/v1/state.go
  pkg/kcp/provider/gcp/iprange/v1/state_test.go
  pkg/kcp/provider/gcp/iprange/v1/syncAddress.go
  pkg/kcp/provider/gcp/iprange/v1/syncAddress_test.go
  pkg/kcp/provider/gcp/iprange/v1/syncPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v1/syncPsaConnection_test.go
  pkg/kcp/provider/gcp/iprange/v2/checkGcpOperation.go
  pkg/kcp/provider/gcp/iprange/v2/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/iprange/v2/state.go
  pkg/kcp/provider/gcp/iprange/v2/state_test.go
  pkg/kcp/provider/gcp/iprange/v2/syncAddress.go
  pkg/kcp/provider/gcp/iprange/v2/syncAddress_test.go
  pkg/kcp/provider/gcp/iprange/v2/syncPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v2/syncPsaConnection_test.go
  pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
  pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation_test.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState_test.go
  pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance.go
  pkg/kcp/provider/gcp/nfsinstance/state.go
  pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance.go
  pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance_test.go
  pkg/kcp/provider/gcp/redisinstance/state.go
  pkg/kcp/provider/gcp/vpcpeering/state.go
  pkg/skr/backupschedule/state_test.go
  pkg/skr/gcpnfsvolumebackup/checkBackupOperation.go
  pkg/skr/gcpnfsvolumebackup/checkBackupOperation_test.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume_test.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup_test.go
  pkg/skr/gcpnfsvolumebackup/state.go
  pkg/skr/gcpnfsvolumebackup/state_test.go
  pkg/skr/gcpnfsvolumebackup/updateStatus.go
  pkg/skr/gcpnfsvolumebackup/updateStatus_test.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume_test.go
  pkg/skr/gcpnfsvolumerestore/removeFinalizer.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore_test.go
  pkg/skr/gcpnfsvolumerestore/state.go
  pkg/skr/gcpnfsvolumerestore/state_test.go
  pkg/testinfra/run.go
Labels: size/L, lgtm, cla: yes

#598 feat(AwsVpcPeering): wait peering connection active
  api/cloud-resources/v1beta1/awsvpcpeering_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/mock/vpcPeeringStore.go
  pkg/kcp/provider/aws/vpcpeering/new.go
  pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go
  pkg/kcp/provider/aws/vpcpeering/waitVpcPeeringActive.go
  pkg/skr/awsvpcpeering/updateStatus.go
Labels: size/M, lgtm, cla: yes

#594 chore(AzureVpcPeering): fixes the race condition
  api/cloud-control/v1beta1/vpcpeering_types.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
Labels: size/S, lgtm, cla: yes

#593 chore: refactor Azure mock
  .golangci.yaml
  go.mod
  internal/controller/cloud-control/redisinstance_azure_test.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/mock/networkStore.go
  pkg/kcp/provider/azure/mock/redisCacheClientFake.go
  pkg/kcp/provider/azure/mock/redisStore.go
  pkg/kcp/provider/azure/mock/resourceStore.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/storeSubscriptionContext.go
  pkg/kcp/provider/azure/mock/tenantSubscriptionStore.go
  pkg/kcp/provider/azure/mock/type.go
  pkg/kcp/provider/azure/mock/vpcPeeringStore.go
  pkg/kcp/provider/azure/redisinstance/client/client.go
  pkg/kcp/provider/azure/redisinstance/createRedis.go
  pkg/kcp/provider/azure/redisinstance/createResourceGroup.go
  pkg/kcp/provider/azure/redisinstance/deleteRedis.go
  pkg/kcp/provider/azure/redisinstance/deleteResourceGroup.go
  pkg/kcp/provider/azure/redisinstance/loadRedis.go
  pkg/kcp/provider/azure/redisinstance/loadResourceGroup.go
  pkg/kcp/provider/azure/redisinstance/modifyRedis.go
  pkg/kcp/provider/azure/redisinstance/new.go
  pkg/kcp/provider/azure/redisinstance/state.go
  pkg/kcp/provider/azure/redisinstance/updateStatus.go
  pkg/kcp/provider/azure/redisinstance/waitRedisAvailable.go
  pkg/kcp/provider/azure/redisinstance/waitResourceGroupDeleted.go
  pkg/kcp/provider/azure/util/resources.go
  pkg/kcp/provider/azure/util/resources_test.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/gcp/mock/nfsStore.go
  pkg/kcp/provider/gcp/mock/server.go
  pkg/kcp/provider/gcp/mock/serviceUsageStore.go
  pkg/kcp/provider/gcp/mock/type.go
  pkg/testinfra/dsl/scope.go
  pkg/util/clone.go
  pkg/util/clone_test.go
Labels: size/XXL, lgtm, cla: yes

#601 feat: Azure KCP Network reconciler
  api/cloud-control/v1beta1/network_builder.go
  api/cloud-control/v1beta1/network_types.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_networks.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_networks.yaml
  internal/controller/cloud-control/iprange_controller.go
  internal/controller/cloud-control/network_azure_test.go
  internal/controller/cloud-control/network_controller.go
  internal/controller/cloud-control/network_reference_test.go
  internal/controller/cloud-control/suite_test.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/common/consts.go
  pkg/kcp/iprange/allocate/allocate.go
  pkg/kcp/network/handleNetworkReference.go
  pkg/kcp/network/logLogicalErrorOnManagedNetworkMissing.go
  pkg/kcp/network/reconciler.go
  pkg/kcp/provider/aws/network/new.go
  pkg/kcp/provider/aws/network/state.go
  pkg/kcp/provider/azure/client/types.go
  pkg/kcp/provider/azure/common/resourceGroup.go
  pkg/kcp/provider/azure/iprange/state.go
  pkg/kcp/provider/azure/mock/networkStore.go
  pkg/kcp/provider/azure/mock/redisStore.go
  pkg/kcp/provider/azure/mock/resourceStore.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/tenantSubscriptionStore.go
  pkg/kcp/provider/azure/mock/type.go
  pkg/kcp/provider/azure/network/client/client.go
  pkg/kcp/provider/azure/network/initState.go
  pkg/kcp/provider/azure/network/new.go
  pkg/kcp/provider/azure/network/resourceGroupCreate.go
  pkg/kcp/provider/azure/network/resourceGroupDelete.go
  pkg/kcp/provider/azure/network/resourceGroupLoad.go
  pkg/kcp/provider/azure/network/state.go
  pkg/kcp/provider/azure/network/statusReady.go
  pkg/kcp/provider/azure/network/vnetCreate.go
  pkg/kcp/provider/azure/network/vnetDelete.go
  pkg/kcp/provider/azure/network/vnetLoad.go
  pkg/kcp/provider/azure/util/resources.go
  pkg/kcp/provider/azure/util/resources_test.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/ccee/nfsinstance/statusReady.go
  pkg/kcp/provider/gcp/network/state.go
  pkg/kcp/scope/loadScopeObj.go
Labels: size/XXL, lgtm, cla: yes

#600 feat(AzureVpcPeering): remove PollUntilDone
  api/cloud-control/v1beta1/vpcpeering_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  pkg/kcp/provider/azure/mock/networkStore.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/loadVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/waitVpcPeeringReady.go
  pkg/skr/azurevpcpeering/updateStatus.go
Labels: size/L, lgtm, cla: yes

#602 chore: KCP VpcPeering references networks
  api/cloud-control/v1beta1/vpcpeering_builder.go
  api/cloud-control/v1beta1/vpcpeering_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  internal/api-tests/builder_test.go
  internal/api-tests/kcp_nfsinstance_test.go
  internal/api-tests/network_test.go
  internal/api-tests/vpcpeering_test.go
  pkg/feature/ffAzurePeeringUseNetwork.go
  pkg/skr/awsvpcpeering/createKcpVpcPeering.go
  pkg/skr/azurevpcpeering/createKpcVpcPeering.go
  pkg/skr/gcpvpcpeering/createKcpVpcPeering.go
  pkg/testinfra/dsl/kcpVpcPeering.go
  pkg/testinfra/dsl/namespace.go
Labels: size/XL, lgtm, cla: yes

#604 chore(AzureVpcPeering): removes remoteResourceGroup from docs
  docs/user/resources/04-40-10-azure-vpc-peering.md
  docs/user/tutorials/01-30-azure-vpc-peering.md
Labels: size/XS, lgtm, cla: yes

#607 (feat) updated awsredisinstances_ui
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/form
Labels: size/XS, lgtm, cla: yes

#605 feat(GcpRedisInstance): implement CloneForPatchStatus method
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
Labels: size/S, lgtm, cla: yes

#595 fix(gcpnfsvolumerestore): preventing duplicate filestore restores
  config/config/skrRuntime.yaml
  config/dist/kcp/crd/kustomization.yaml
  pkg/kcp/provider/gcp/mock/nfsRestoreStore.go
  pkg/kcp/provider/gcp/nfsrestore/client/fileRestoreClient.go
  pkg/skr/common/leases/lease.go
  pkg/skr/common/leases/lease_test.go
  pkg/skr/gcpnfsvolumerestore/acquireLease.go
  pkg/skr/gcpnfsvolumerestore/acquireLease_test.go
  pkg/skr/gcpnfsvolumerestore/addFinalizer_test.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/findRestoreOperation_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolumerestore/reconciler.go
  pkg/skr/gcpnfsvolumerestore/releaseLease.go
  pkg/skr/gcpnfsvolumerestore/releaseLease_test.go
  pkg/skr/gcpnfsvolumerestore/removeFinalizer.go
  pkg/skr/gcpnfsvolumerestore/removeFinalizer_test.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore_test.go
  pkg/skr/gcpnfsvolumerestore/setProcessing_test.go
  pkg/skr/gcpnfsvolumerestore/state_test.go
  pkg/skr/runtime/config/config.go
  pkg/skr/runtime/config/config_test.go
Labels: size/XL, lgtm, cla: yes

#609 chore: sanitize logs
  pkg/kcp/provider/gcp/iprange/v1/checkGcpOperation.go
  pkg/kcp/provider/gcp/iprange/v1/loadAddress.go
  pkg/kcp/provider/gcp/iprange/v1/loadPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v1/syncAddress.go
  pkg/kcp/provider/gcp/iprange/v1/syncPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v1/validateCidr.go
  pkg/kcp/provider/gcp/iprange/v2/checkGcpOperation.go
  pkg/kcp/provider/gcp/iprange/v2/identifyPeeringIpRanges.go
  pkg/kcp/provider/gcp/iprange/v2/loadPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v2/syncAddress.go
  pkg/kcp/provider/gcp/iprange/v2/syncPsaConnection.go
  pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
  pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
  pkg/kcp/provider/gcp/nfsinstance/checkUpdateMask.go
  pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance.go
  pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance.go
  pkg/kcp/provider/gcp/nfsinstance/validateAlways.go
  pkg/kcp/provider/gcp/nfsinstance/validatePostCreate.go
  pkg/kcp/scope/checkGcpOperations.go
  pkg/skr/awsnfsvolumebackup/deleteAwsBackup.go
  pkg/skr/awsnfsvolumebackup/setIdempotencyToken.go
  pkg/skr/backupschedule/backupImpl.go
  pkg/skr/backupschedule/calculateOnetimeSchedule.go
  pkg/skr/backupschedule/calculateRecurringSchedule.go
  pkg/skr/backupschedule/checkCompleted.go
  pkg/skr/backupschedule/checkSuspension.go
  pkg/skr/backupschedule/createBackup.go
  pkg/skr/backupschedule/deleteBackups.go
  pkg/skr/backupschedule/deleteCascade.go
  pkg/skr/backupschedule/evaluateNextRun.go
  pkg/skr/backupschedule/loadBackups.go
  pkg/skr/backupschedule/loadSource.go
  pkg/skr/gcpnfsvolume/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolume/setProcessing.go
  pkg/skr/gcpnfsvolumebackup/checkBackupOperation.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
  pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
  pkg/skr/gcpnfsvolumerestore/setProcessing.go
Labels: size/L, lgtm, cla: yes

#611 feat(AwsRedisInstance): add securitygroup to instance
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/mock/server.go
  pkg/kcp/provider/aws/redisinstance/authorizeSecurityGroupIngress.go
  pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/createSecurityGroup.go
  pkg/kcp/provider/aws/redisinstance/deleteSecurityGroup.go
  pkg/kcp/provider/aws/redisinstance/findSecurityGroup.go
  pkg/kcp/provider/aws/redisinstance/loadSecurityGroup.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/kcp/provider/aws/redisinstance/util.go
Labels: size/L, lgtm, cla: yes

#612 chore: refactor Azure peering to use KCP Network
  api/cloud-control/v1beta1/conditions.go
  api/cloud-control/v1beta1/network_types.go
  api/cloud-control/v1beta1/types.go
  api/cloud-control/v1beta1/vpcpeering_types.go
  config/crd/bases/cloud-control.kyma-project.io_networks.yaml
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_networks.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  internal/controller/cloud-control/network_controller.go
  internal/controller/cloud-control/redisinstance_controller.go
  internal/controller/cloud-control/scope_aws_test.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  internal/controller/cloud-control/vpcpeering_controller.go
  pkg/common/network.go
  pkg/composed/predicate.go
  pkg/composed/state.go
  pkg/kcp/provider/azure/client/provider.go
  pkg/kcp/provider/azure/common/resourceGroup.go
  pkg/kcp/provider/azure/meta/metadata.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/type.go
  pkg/kcp/provider/azure/network/client/client.go
  pkg/kcp/provider/azure/network/state.go
  pkg/kcp/provider/azure/network/statusReady.go
  pkg/kcp/provider/azure/redisinstance/client/client.go
  pkg/kcp/provider/azure/redisinstance/state.go
  pkg/kcp/provider/azure/util/resources.go
  pkg/kcp/provider/azure/vpcpeering/addFinalizer.go
  pkg/kcp/provider/azure/vpcpeering/client/client.go
  pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/kcpNetworkLocalLoad.go
  pkg/kcp/provider/azure/vpcpeering/kcpNetworkRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/loadVpcPeering.go
  pkg/kcp/provider/azure/vpcpeering/new.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalWaitReady.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteCreate.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/peeringRemoteRequireSpecifiedName.go
  pkg/kcp/provider/azure/vpcpeering/predicateRequireVNetShootTag.go
  pkg/kcp/provider/azure/vpcpeering/remoteClientCreate.go
  pkg/kcp/provider/azure/vpcpeering/removeFinalizer.go
  pkg/kcp/provider/azure/vpcpeering/removeReadyCondition.go
  pkg/kcp/provider/azure/vpcpeering/state.go
  pkg/kcp/provider/azure/vpcpeering/statusInitiated.go
  pkg/kcp/provider/azure/vpcpeering/statusReady.go
  pkg/kcp/provider/azure/vpcpeering/updateStatus.go
  pkg/kcp/provider/azure/vpcpeering/vpcRemoteLoad.go
  pkg/kcp/provider/azure/vpcpeering/waitVpcPeeringReady.go
  pkg/kcp/scope/createKymaNetworkReference.go
  pkg/testinfra/dsl/commonAssertions.go
  pkg/testinfra/dsl/conditions.go
  pkg/testinfra/dsl/kcpVpcPeering.go
Labels: size/XXL, lgtm, cla: yes

#608 fix: Aws Backup RoleName
  pkg/kcp/provider/aws/config/config.go
  pkg/skr/awsnfsvolumebackup/createAwsBackup.go
  pkg/skr/awsnfsvolumebackup/state.go
Labels: size/S, lgtm, cla: yes

#610 feat(AzureVpcPeering): SKR tests
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
  internal/controller/cloud-resources/azurevpcpeering_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/skr/azurevpcpeering/createKcpRemoteNetwork.go
  pkg/skr/azurevpcpeering/createKpcVpcPeering.go
  pkg/skr/azurevpcpeering/deleteKcpRemoteNetwork.go
  pkg/skr/azurevpcpeering/deleteKcpVpcPeering.go
  pkg/skr/azurevpcpeering/loadKcpRemoteNetwork.go
  pkg/skr/azurevpcpeering/reconciler.go
  pkg/skr/azurevpcpeering/state.go
  pkg/testinfra/dsl/azureVpcPeering.go
  pkg/testinfra/dsl/conditions.go
Labels: size/L, lgtm, cla: yes

#615 fix(GcpNfsBackupSchedule): optional sourceRef namespace name
  api/cloud-resources/v1beta1/gcpnfsbackupschedule_types.go
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/patchAfterMakeManifests.sh
  pkg/skr/backupschedule/backupImplGcpNfs.go
  pkg/skr/backupschedule/deleteCascade.go
  pkg/skr/backupschedule/loadSource.go
Labels: size/S, lgtm, cla: yes

#613 docs(GcpNfsVolumeBackup): user documentation
  docs/user/00-10-glossary.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/04-70-10-gcp-nfs-volume-backup.md
  docs/user/tutorials/01-70-gcp-nfs-volume-backup.md
Labels: size/L, lgtm, cla: yes

#620 docs(GcpRedisInstance): update docs and tutorial
  docs/user/resources/04-60-gcp-redis-instance.md
  docs/user/tutorials/01-60-gcp-redis-instance.md
Labels: size/XS, lgtm, cla: yes

#625 feat(VpcPeering): local peering name
  api/cloud-control/v1beta1/vpcpeering_types.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
Labels: size/XS, lgtm, cla: yes

#614 docs(GcpNfsBackupSchedule): user documentation
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/04-30-30-gcp-nfs-backup-schedule.md
  docs/user/resources/README.md
  docs/user/tutorials/01-80-gcp-scheduled-nfs-backup.md
  docs/user/tutorials/README.md
Labels: size/L, lgtm, cla: yes

#627 feat(AwsRedisInstance): show updating state while instance is modified by cloud provider
  api/cloud-control/v1beta1/conditions.go
  pkg/kcp/provider/aws/redisinstance/addUpdatingCondition.go
  pkg/kcp/provider/aws/redisinstance/new.go
  pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
  pkg/skr/awsredisinstance/updateStatus.go
Labels: size/M, lgtm, cla: yes

#631 chore(AwsRedisInstance): add updating condition to skr
  api/cloud-resources/v1beta1/condition.go
  pkg/skr/awsredisinstance/updateStatus.go
Labels: size/S, lgtm, cla: yes

#624 fix(ScopeOpenStack): preserve obj resource version
  pkg/kcp/scope/createScopeOpenStack.go
Labels: size/XS, lgtm, cla: yes

#622 feat(AzureVpcPeering): warning messages when creating local peering connection
  pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
Labels: size/S, lgtm, cla: yes

#626 feat(AzureVpcPeering): local peering name
  api/cloud-control/v1beta1/vpcpeering_types.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
  pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go
Labels: size/S, lgtm, cla: yes

#619 docs(AwsRedisInstance): add resources and tutorial
  docs/user/resources/04-70-aws-redis-instance.md
  docs/user/resources/README.md
  docs/user/tutorials/01-70-aws-redis-instance.md
  docs/user/tutorials/README.md
Labels: size/L, lgtm, cla: yes

#633 feat(GcpRedisInstance): show updating status while instance is updating
  pkg/kcp/provider/gcp/redisinstance/addUpdatingCondition.go
  pkg/kcp/provider/gcp/redisinstance/new.go
  pkg/skr/gcpredisinstance/updateStatus.go
Labels: size/M, lgtm, cla: yes

#641 feat(AwsVpcPeering): wait KcpVpcPeering deleted before deleting Network
  pkg/kcp/provider/aws/vpcpeering/acceptVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
  pkg/kcp/provider/aws/vpcpeering/createRemoteClient.go
  pkg/kcp/provider/aws/vpcpeering/createRemoteRoutes.go
  pkg/kcp/provider/aws/vpcpeering/createRoutes.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/deleteRoutes.go
  pkg/kcp/vpcpeering/state.go
  pkg/skr/awsvpcpeering/deleteKcpVpcPeering.go
  pkg/skr/awsvpcpeering/reconciler.go
  pkg/skr/awsvpcpeering/waitKcpVpcPeeringDeleted.go
Labels: size/L, lgtm, cla: yes

#642 feat(AzureVpcPeering): wait KcpVpcPeering deleted before deleting Network
  pkg/skr/azurevpcpeering/reconciler.go
  pkg/skr/azurevpcpeering/waitKcpVpcPeeringDeleted.go
Labels: size/S, lgtm, cla: yes

#643 refactor(RedisInstance): adjust error handling
  pkg/kcp/provider/gcp/meta/metadata.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
  pkg/kcp/provider/gcp/redisinstance/loadRedis.go
Labels: size/M, lgtm, cla: yes

#630 docs(GcpNfsVolumeRestore): user documentation
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/04-30-10-gcp-nfs-volume.md
  docs/user/resources/04-90-10-gcp-nfs-volume-restore.md
  docs/user/resources/README.md
  docs/user/tutorials/01-70-gcp-nfs-volume-backup.md
  docs/user/tutorials/01-90-gcp-nfs-volume-restore.md
  docs/user/tutorials/README.md
Labels: size/L, lgtm, cla: yes

#644 chore(GcpRedisInstance,AwsRedisInstance): reduce kcp polling frequency
  pkg/skr/awsredisinstance/waitKcpStatusUpdate.go
  pkg/skr/gcpredisinstance/waitKcpStatusUpdate.go
Labels: size/XS, lgtm, cla: yes

#646 chore: scope network fix
  pkg/kcp/scope/createKymaNetworkReference.go
  pkg/kcp/scope/loadNetworks.go
  pkg/kcp/scope/predicates.go
  pkg/kcp/scope/reconciler.go
  pkg/kcp/scope/state.go
  tools/dev/reconcilers/azure-peering-kyma-cm.png
Labels: size/M, lgtm, cla: yes

#640 fix(gcpNfsVolumeRestore): completed restore should skip most of the r…
  pkg/skr/gcpnfsvolumerestore/acquireLease.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/findRestoreOperation_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup_test.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume_test.go
  pkg/skr/gcpnfsvolumerestore/reconciler.go
  pkg/skr/gcpnfsvolumerestore/releaseLease.go
  pkg/skr/gcpnfsvolumerestore/setProcessing_test.go
Labels: size/M, lgtm, cla: yes

#648 feat(GcpRedisInstance): authEnabled disabled by default
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  docs/user/resources/04-60-gcp-redis-instance.md
  docs/user/tutorials/01-60-gcp-redis-instance.md
  pkg/skr/gcpredisinstance/modifyAuthSecret.go
Labels: size/S, lgtm, cla: yes

#651 feat(GcpRedisInstance): refactor transitEncryption object to transitEncryptionMode string
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  config/samples/cloud-resources_v1beta1_gcpredisinstance.yaml
  docs/user/resources/04-60-gcp-redis-instance.md
  docs/user/tutorials/01-60-gcp-redis-instance.md
  internal/controller/cloud-control/redisinstance_gcp_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
  pkg/kcp/provider/gcp/redisinstance/client/util.go
  pkg/kcp/provider/gcp/redisinstance/createRedis.go
  pkg/skr/gcpredisinstance/createKcpRedisInstance.go
  pkg/skr/gcpredisinstance/util.go
  pkg/testinfra/dsl/gcpRedisInstance.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/L, lgtm, cla: yes

#652 fix(AzureIpRange):add azure iprange yaml into sync script
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_ipranges.yaml
  config/sync.sh
Labels: size/L, lgtm, cla: yes

#653 docs(GcpRedisInstance): update example target redis version
  docs/user/tutorials/01-60-gcp-redis-instance.md
Labels: size/XS, lgtm, cla: yes

#655 chore: build image on tag
  .github/workflows/cloud-manager-build.yml
Labels: size/S, lgtm, cla: yes

#658 (feat) AzureVPCPeering and GCPRedisInstance UI update
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/details
  config/ui-extensions/azurevpcpeerings/form
  config/ui-extensions/azurevpcpeerings/translations
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/details
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpredisinstances/translations
Labels: size/M, lgtm, cla: yes

#650 docs: contributor Azure permissions
  docs/contributor/azure-permissions.md
Labels: size/M, cla: yes

#662 fix: Azure tags removed
  internal/controller/cloud-control/iprange_azure_test.go
  internal/controller/cloud-control/network_azure_test.go
  pkg/kcp/provider/azure/iprange/securityGroupCreate.go
  pkg/kcp/provider/azure/network/initState.go
Labels: size/M, lgtm, cla: yes

#663 AWS Backup Service Role update
  pkg/kcp/provider/aws/config/config.go
  pkg/skr/awsnfsvolumebackup/state.go
Labels: size/XS, lgtm, cla: yes

#660 docs(AzureVpcPeering): adds missing IP_ADDRESS export
  docs/user/tutorials/01-30-azure-vpc-peering.md
Labels: size/XS, lgtm, cla: yes

#665 feat(AzureRedis):skr azure redis - invoke ip range creation
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  internal/controller/cloud-resources/azureredisinstance_test.go
  pkg/skr/azureredisinstance/reconciler.go
  pkg/skr/azureredisinstance/state.go
Labels: size/L, lgtm, cla: yes

#672 chore: tweak KCP IpRange create kcp network error handling
  pkg/kcp/iprange/kcpNetworkCreate.go
  pkg/testinfra/dsl/conditions.go
Labels: size/XS, lgtm, cla: yes

#668 feat(AwsVpcPeering): wait status Active
  api/cloud-resources/v1beta1/awsvpcpeering_types.go
  internal/controller/cloud-resources/awsvpcpeering_test.go
  pkg/skr/awsvpcpeering/reconciler.go
  pkg/skr/awsvpcpeering/updateStatus.go
  pkg/skr/awsvpcpeering/waitStatusActive.go
Labels: size/M, lgtm, cla: yes

#667 feat(AzureVpcPeering): wait status Ready
  api/cloud-resources/v1beta1/azurevpcpeering_types.go
  internal/controller/cloud-resources/azurevpcpeering_test.go
  pkg/skr/azurevpcpeering/reconciler.go
  pkg/skr/azurevpcpeering/updateStatus.go
  pkg/skr/azurevpcpeering/waitStatusReady.go
Labels: size/M, lgtm, cla: yes

#666 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, cla: yes
