Repository kyma-project/cloud-manager, pull requests merged in 2025-03, with the labels that each got.

#1061 feat: AzureRwxVolumeRestore client
  pkg/skr/azurerwxvolumebackup/client/client.go
  pkg/skr/azurerwxvolumebackup/client/constants.go
  pkg/skr/azurerwxvolumebackup/client/jobs.go
  pkg/skr/azurerwxvolumebackup/client/restore.go
Labels: size/L, lgtm

#1062 feat(AwsRedisCluster): implement cloud-resources reconciler
  api/cloud-resources/v1beta1/awsrediscluster_types.go
  api/cloud-resources/v1beta1/labels.go
  config/crd/bases/cloud-resources.kyma-project.io_awsredisclusters.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisclusters.yaml
  config/patchAfterMakeManifests.sh
  config/samples/cloud-resources_v1beta1_awsrediscluster.yaml
  internal/controller/cloud-resources/awsrediscluster_test.go
  internal/controller/cloud-resources/iprange_controller.go
  internal/controller/cloud-resources/iprange_test.go
  pkg/skr/awsrediscluster/createAuthSecret.go
  pkg/skr/awsrediscluster/createKcpRedisInstance.go
  pkg/skr/awsrediscluster/deleteAuthSecret.go
  pkg/skr/awsrediscluster/deleteKcpRedisInstance.go
  pkg/skr/awsrediscluster/ignorant.go
  pkg/skr/awsrediscluster/loadAuthSecret.go
  pkg/skr/awsrediscluster/loadKcpRedisInstance.go
  pkg/skr/awsrediscluster/modifyAuthSecret.go
  pkg/skr/awsrediscluster/modifyKcpRedisInstance.go
  pkg/skr/awsrediscluster/reconciler.go
  pkg/skr/awsrediscluster/removeAuthSecretFinalizer.go
  pkg/skr/awsrediscluster/state.go
  pkg/skr/awsrediscluster/updateId.go
  pkg/skr/awsrediscluster/updateStatus.go
  pkg/skr/awsrediscluster/util.go
  pkg/skr/awsrediscluster/util_test.go
  pkg/skr/awsrediscluster/waitAuthSecretDeleted.go
  pkg/skr/awsrediscluster/waitKcpRedisInstanceDeleted.go
  pkg/skr/awsrediscluster/waitKcpStatusUpdate.go
  pkg/skr/awsrediscluster/waitSkrStatusReady.go
  pkg/skr/iprange/preventDeleteOnAwsRedisClusterUsage.go
  pkg/skr/iprange/reconciler.go
  pkg/testinfra/dsl/awsRedisCluster.go
  pkg/testinfra/dsl/commonIpRange.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/XXL, lgtm

#1063 chore(AzureRwxBackupSchedule): reconciler implementation
  internal/controller/cloud-resources/azurerwxbackupschedule_controller.go
  pkg/skr/backupschedule/backupImpl.go
  pkg/skr/backupschedule/backupImplAzureRwx.go
Labels: size/L, lgtm

#1064 feat: Azure Client handling Poller response
  pkg/skr/azurerwxvolumebackup/client/backup.go
  pkg/skr/azurerwxvolumebackup/client/constants.go
  pkg/skr/azurerwxvolumebackup/client/protectionPolicies.go
  pkg/skr/azurerwxvolumebackup/client/vault.go
Labels: size/L

#1072 feat: created BackupProtectableItemsClient and ProtectedItemsClient
  pkg/skr/azurerwxvolumebackup/client/backupProtectableItems.go
  pkg/skr/azurerwxvolumebackup/client/client.go
  pkg/skr/azurerwxvolumebackup/client/protectedItems.go
Labels: size/L, lgtm

#1073 test: Azure RWX backup schedule
  internal/controller/cloud-resources/aws/awsnfsbackupschedule_test.go
  internal/controller/cloud-resources/azure/azurerwxbackupschedule_test.go
  internal/controller/cloud-resources/azure/suite_test.go
  internal/controller/cloud-resources/gcpnfsbackupschedule_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/skr/backupschedule/backupImpl.go
  pkg/skr/backupschedule/backupImplAwsNfs.go
  pkg/skr/backupschedule/backupImplAzureRwx.go
  pkg/skr/backupschedule/backupImplGcpNfs.go
  pkg/skr/backupschedule/loadSource.go
  pkg/testinfra/dsl/azureRwxVolume.go
  pkg/testinfra/dsl/azureRwxVolumeBackup.go
  pkg/testinfra/dsl/nfsBackupSchedule.go
  pkg/testinfra/dsl/scope.go
Labels: size/XL, lgtm

#1081 (feat)AzureRedisCluster: KCP impl
  api/cloud-control/v1beta1/rediscluster_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_redisclusters.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisclusters.yaml
  internal/controller/cloud-control/rediscluster_azure_test.go
  internal/controller/cloud-control/rediscluster_controller.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/provider/azure/mock/server.go
  pkg/kcp/provider/azure/mock/type.go
  pkg/kcp/provider/azure/rediscluster/client/client.go
  pkg/kcp/provider/azure/rediscluster/createPrivateDnsZoneGroup.go
  pkg/kcp/provider/azure/rediscluster/createPrivateEndPoint.go
  pkg/kcp/provider/azure/rediscluster/createRedisCluster.go
  pkg/kcp/provider/azure/rediscluster/deletePrivateDnsZoneGroup.go
  pkg/kcp/provider/azure/rediscluster/deletePrivateEndPoint.go
  pkg/kcp/provider/azure/rediscluster/deleteRedisCluster.go
  pkg/kcp/provider/azure/rediscluster/loadPrivateDnsZoneGroup.go
  pkg/kcp/provider/azure/rediscluster/loadPrivateEndPoint.go
  pkg/kcp/provider/azure/rediscluster/loadRedisCluster.go
  pkg/kcp/provider/azure/rediscluster/modifyRedisCluster.go
  pkg/kcp/provider/azure/rediscluster/new.go
  pkg/kcp/provider/azure/rediscluster/state.go
  pkg/kcp/provider/azure/rediscluster/updateStatus.go
  pkg/kcp/provider/azure/rediscluster/updateStatusId.go
  pkg/kcp/provider/azure/rediscluster/waitPrivateDnsZoneGroupDeleted.go
  pkg/kcp/provider/azure/rediscluster/waitPrivateEndPointAvailable.go
  pkg/kcp/provider/azure/rediscluster/waitPrivateEndPointDeleted.go
  pkg/kcp/provider/azure/rediscluster/waitRedisClusterAvailable.go
  pkg/kcp/provider/azure/rediscluster/waitRedisClusterDeleted.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/XXL

#1102 docs: Sync DITA and OS content
  docs/user/00-20-nfs.md
  docs/user/00-25-scheduling-best-practices.md
  docs/user/00-30-vpc-peering.md
  docs/user/00-31-vpc-peering-authorization.md
  docs/user/00-40-redis.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/README.md
  docs/user/tutorials/01-20-11-aws-nfs-volume-backup.md
  docs/user/tutorials/01-20-12-aws-scheduled-nfs-backup.md
  docs/user/tutorials/01-20-13-aws-nfs-volume-restore.md
  docs/user/tutorials/01-20-21-gcp-nfs-volume-backup.md
  docs/user/tutorials/01-20-22-gcp-scheduled-nfs-backup.md
  docs/user/tutorials/01-20-23-gcp-nfs-volume-restore.md
  docs/user/tutorials/01-30-10-aws-vpc-peering.md
  docs/user/tutorials/01-30-20-gcp-vpc-peering.md
  docs/user/tutorials/01-30-30-azure-vpc-peering.md
  docs/user/tutorials/README.md
Labels: documentation, area/documentation

#1054 feat: added remoteRouteTableUpdateStrategy to AWS VPC Peerings UI
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
  config/ui-extensions/awsvpcpeerings/details
  config/ui-extensions/awsvpcpeerings/form
  config/ui-extensions/awsvpcpeerings/kustomization.yaml
  config/ui-extensions/awsvpcpeerings/translations
Labels: size/M, cla: yes
