Repository kyma-project/cloud-manager, pull requests merged in 2025-01, with the labels that each got.

#935 feat(RedisInstance): handle authSecret extraData
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  api/cloud-resources/v1beta1/gcpredisinstance_types.go
  api/cloud-resources/v1beta1/redisinstance_authsecret.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
  config/patchAfterMakeManifests.sh
  docs/user/resources/04-40-10-aws-redis-instance.md
  docs/user/resources/04-40-20-gcp-redis-instance.md
  docs/user/resources/04-40-30-azure-redis-instance.md
  internal/controller/cloud-resources/awsredisinstance_test.go
  internal/controller/cloud-resources/azureredisinstance_test.go
  internal/controller/cloud-resources/gcpredisinstance_test.go
  pkg/skr/awsredisinstance/createAuthSecret.go
  pkg/skr/awsredisinstance/modifyAuthSecret.go
  pkg/skr/awsredisinstance/state.go
  pkg/skr/awsredisinstance/util.go
  pkg/skr/azureredisinstance/createAuthSecret.go
  pkg/skr/azureredisinstance/state.go
  pkg/skr/azureredisinstance/util.go
  pkg/skr/gcpredisinstance/createAuthSecret.go
  pkg/skr/gcpredisinstance/modifyAuthSecret.go
  pkg/skr/gcpredisinstance/state.go
  pkg/skr/gcpredisinstance/util.go
  pkg/testinfra/dsl/awsRedisInstance.go
  pkg/testinfra/dsl/azureRedisInstance.go
  pkg/testinfra/dsl/gcpRedisInstance.go
  pkg/util/map.go
  pkg/util/map_test.go
Labels: size/XL, lgtm, cla: yes

#940 refactor(AwsRedisInstance): generic functions for param group management
  pkg/kcp/provider/aws/redisinstance/createParameterGroup.go
  pkg/kcp/provider/aws/redisinstance/deleteParameterGroup.go
  pkg/kcp/provider/aws/redisinstance/modifyParameterGroup.go
  pkg/kcp/provider/aws/redisinstance/new.go
Labels: size/L, lgtm, cla: yes

#942 feat(RedisInstance UI) handle extraData UI
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/details
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsredisinstances/kustomization.yaml
  config/ui-extensions/awsredisinstances/translations
  config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
  config/ui-extensions/azureredisinstances/details
  config/ui-extensions/azureredisinstances/form
  config/ui-extensions/azureredisinstances/kustomization.yaml
  config/ui-extensions/azureredisinstances/translations
  config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
  config/ui-extensions/gcpredisinstances/details
  config/ui-extensions/gcpredisinstances/form
  config/ui-extensions/gcpredisinstances/kustomization.yaml
  config/ui-extensions/gcpredisinstances/translations
Labels: size/L, cla: yes

#927 docs(AwsVpcPeering) find matching image by architecture
  docs/user/tutorials/01-30-10-aws-vpc-peering.md
Labels: size/XS, cla: yes

#956 chore(AwsRedisInstance): up manifest version
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
Labels: size/XS, cla: yes

#960 feat: added warning to AWS Redis Instance Engine Version
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
  config/ui-extensions/awsredisinstances/form
  config/ui-extensions/awsredisinstances/kustomization.yaml
Labels: size/XS, cla: yes

#957 feat(AwsRedisInstance): limit engineVersion values
  api/cloud-control/v1beta1/redisinstance_types.go
  api/cloud-resources/v1beta1/awsredisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
  config/patchAfterMakeManifests.sh
  docs/user/resources/04-40-10-aws-redis-instance.md
  internal/api-tests/skr_awsredisinstance_test.go
  internal/controller/cloud-control/iprange_delete_test.go
Labels: size/L, lgtm, cla: yes

#977 SKR Status
  PROJECT
  api/cloud-control/v1beta1/skrstatus_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cloud-control.kyma-project.io_skrstatuses.yaml
  config/crd/kustomization.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_skrstatuses.yaml
  config/rbac/cloud-control_skrstatus_admin_role.yaml
  config/rbac/cloud-control_skrstatus_editor_role.yaml
  config/rbac/cloud-control_skrstatus_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/samples/cloud-control_v1beta1_skrstatus.yaml
  config/samples/kustomization.yaml
  docs/contributor/ui/README.md
  pkg/feature/context.go
  pkg/skr/runtime/alias.go
  pkg/skr/runtime/looper/installer.go
  pkg/skr/runtime/looper/runner.go
  pkg/skr/runtime/looper/skrLooper.go
  pkg/skr/runtime/looper/skrStatus.go
  pkg/skr/runtime/manager/manager.go
  pkg/testinfra/env.go
Labels: size/XXL, lgtm, cla: yes

#978 fixed SkrStatus clone for patch with labels and annotations
  api/cloud-control/v1beta1/skrstatus_types.go
Labels: size/XS, lgtm, cla: yes

#979 chore: reduce logs for skr iprange
  pkg/composed/action.go
  pkg/composed/conditions.go
  pkg/skr/iprange/loadKcpIpRange.go
  pkg/skr/iprange/updateId.go
  pkg/skr/iprange/updateStatus.go
Labels: size/L, lgtm, cla: yes

#980 chore: dont log controller-runtime starting/stopping logs
  cmd/main.go
  pkg/skr/runtime/looper/cyclicQueue.go
  pkg/skr/runtime/looper/skrLooper.go
  pkg/util/logFilterSink.go
Labels: size/M, cla: yes

#894 Generate release notes
  .github/workflows/.grenrc.json
  .github/workflows/create-release-notes.yaml
Labels: size/M, cla: yes

#982 chore: log reconciliation outcome
  pkg/composed/bridge.go
Labels: size/S, lgtm, cla: yes

#986 fix: Scope finalizer do not add finalizer to Kyma being deleted
  pkg/composed/bridge.go
  pkg/kcp/scope/addKymaFinalizer.go
  pkg/kcp/scope/reconciler.go
Labels: size/S, lgtm, cla: yes

#983 Fix(AzureRedis): Do not update status if state has not changed
  pkg/kcp/provider/azure/redisinstance/updateStatus.go
Labels: size/S, lgtm, cla: yes

#987 chore: made SkrStatus spec.conditions optional
  api/cloud-control/v1beta1/skrstatus_types.go
  config/crd/bases/cloud-control.kyma-project.io_skrstatuses.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_skrstatuses.yaml
Labels: size/XS, lgtm, cla: yes

#990 chore(AwsVpcPeering): improper error handling
  pkg/kcp/provider/aws/mock/routeTablesStore.go
Labels: size/S, lgtm, cla: yes

#991 chore: remove obsolete/non-working cx config
  .checkmarx/config.yml
Labels: size/XS, lgtm, cla: yes

#993 feat: removed unused fields from Azure VPC Peering UI
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
  config/ui-extensions/azurevpcpeerings/details
  config/ui-extensions/azurevpcpeerings/form
  config/ui-extensions/azurevpcpeerings/kustomization.yaml
  config/ui-extensions/azurevpcpeerings/list
  config/ui-extensions/azurevpcpeerings/translations
Labels: size/M, cla: yes

#989 fix(BackupSchedule): flaky test
  pkg/skr/backupschedule/evaluateNextRun_test.go
Labels: size/XS, lgtm, cla: yes

#992 docs(VpcPeering): improve tutorial to identify correct principals
  docs/user/resources/04-30-10-aws-vpc-peering.md
  docs/user/resources/04-30-30-azure-vpc-peering.md
  docs/user/tutorials/01-30-10-aws-vpc-peering.md
  docs/user/tutorials/01-30-30-azure-vpc-peering.md
Labels: size/M, cla: yes
