Repository kyma-project/cloud-manager, pull requests merged in 2025-02, with the labels that each got.

#994 feat(RedisCluster): add cloud-control boilerplate
  PROJECT
  api/cloud-control/v1beta1/rediscluster_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_redisclusters.yaml
  config/crd/kustomization.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisclusters.yaml
  config/rbac/cloud-control_rediscluster_editor_role.yaml
  config/rbac/cloud-control_rediscluster_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/samples/cloud-control_v1beta1_rediscluster.yaml
  config/samples/kustomization.yaml
  internal/controller/cloud-control/rediscluster_controller.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/rediscluster/ignorant.go
  pkg/kcp/rediscluster/loadIpRange.go
  pkg/kcp/rediscluster/reconciler.go
  pkg/kcp/rediscluster/state.go
  pkg/kcp/rediscluster/types/state.go
Labels: size/XL, lgtm, cla: yes

#1002 chore: more logs on finalizer migration
  pkg/migrateFinalizers/migrator.go
  pkg/migrateFinalizers/runner.go
Labels: size/S, lgtm, cla: yes

#1001 feat(RedisCluster): add cloud provider boilereplate
  internal/controller/cloud-control/rediscluster_controller.go
  pkg/kcp/provider/aws/rediscluster/new.go
  pkg/kcp/provider/aws/rediscluster/state.go
  pkg/kcp/provider/azure/rediscluster/new.go
  pkg/kcp/provider/azure/rediscluster/state.go
  pkg/kcp/provider/gcp/rediscluster/new.go
  pkg/kcp/provider/gcp/rediscluster/state.go
  pkg/kcp/rediscluster/reconciler.go
Labels: size/L, lgtm, cla: yes

#918 docs: Add NFS, Redis, and VPC peering feature description
  docs/user/00-20-nfs.md
  docs/user/00-30-vpc-peering.md
  docs/user/00-40-redis.md
  docs/user/README.md
  docs/user/assets/cloud-manager-architecture.drawio.svg
  docs/user/resources/04-30-20-gcp-vpc-peering.md
Labels: documentation, size/L, area/documentation, cla: yes

#1004 fix(BackupSchedule): cron schedule unit test timing issue
  pkg/skr/backupschedule/calculateRecurringSchedule_test.go
Labels: size/XS, lgtm, cla: yes

#1008 fix(NukeAwsBackups) - Load vault before listing the backups
  pkg/kcp/provider/aws/nuke/loadNfsBackups.go
  pkg/kcp/provider/aws/nuke/loadVault.go
  pkg/kcp/provider/aws/nuke/new.go
  pkg/kcp/provider/aws/nuke/state.go
Labels: size/M, lgtm, cla: yes

#1014 chore: trigger generate release notes on non-patch version only
  .github/workflows/create-release-notes.yaml
Labels: size/XS, lgtm, cla: yes

#1013 refactor(RedisInstance): move aws client to common package
  cmd/main.go
  internal/controller/cloud-control/redisinstance_controller.go
  pkg/kcp/provider/aws/client/elastiCacheClient.go
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/mock/server.go
  pkg/kcp/provider/aws/mock/type.go
  pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
  pkg/kcp/provider/aws/redisinstance/state.go
  pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
Labels: size/M, lgtm, cla: yes

#1020 chore(cli): ShootSpec.CloudProfileName is required
  cmd/cli/README.md
  cmd/cli/cmdGardenShootCreateAws.go
  cmd/cli/cmdGardenShootCreateAzure.go
  tools/dev/README.md
Labels: size/M, lgtm, cla: yes

#1022 fix(GcpNfsVolume): no longer tries to edit capacity in spec
  pkg/skr/gcpnfsvolume/modifyPersistentVolumeClaim.go
  pkg/skr/gcpnfsvolume/modifyPersistentVolumeClaim_test.go
Labels: size/M, lgtm, cla: yes

#1012 docs: Group VPC tutorials steps into sections
  docs/user/00-30-vpc-peering.md
  docs/user/00-50-vpc-peering-authorization.md
  docs/user/_sidebar.md
  docs/user/assets/cloud-manager-architecture.drawio.svg
  docs/user/resources/04-30-10-aws-vpc-peering.md
  docs/user/resources/04-30-20-gcp-vpc-peering.md
  docs/user/resources/04-30-30-azure-vpc-peering.md
  docs/user/tutorials/01-30-10-aws-vpc-peering.md
  docs/user/tutorials/01-30-20-gcp-vpc-peering.md
  docs/user/tutorials/01-30-30-azure-vpc-peering.md
Labels: documentation, area/documentation, size/XXL, cla: yes

#1021 chore: migrate finalizer repeat 3 times
  internal/controller/cloud-control/vpcpeering_aws_test.go
  internal/controller/cloud-control/vpcpeering_azure_test.go
  pkg/composed/state.go
  pkg/migrateFinalizers/successHandler.go
  pkg/migrateFinalizers/tests/migrate_finalizers_test.go
Labels: size/L, lgtm, cla: yes

#1023 fix: enhance the log messages of Gcp Nfs Volume/Backup/Restore
  pkg/kcp/provider/gcp/client/serviceUsageClient.go
  pkg/kcp/provider/gcp/iprange/client/computeClient.go
  pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
  pkg/kcp/provider/gcp/iprange/v2/checkGcpOperation.go
  pkg/kcp/provider/gcp/iprange/v2/identifyPeeringIpRanges.go
  pkg/kcp/provider/gcp/iprange/v2/loadPsaConnection.go
  pkg/kcp/provider/gcp/iprange/v2/syncPsaConnection.go
  pkg/kcp/provider/gcp/nfsbackup/client/fileBackupClient.go
  pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
  pkg/kcp/provider/gcp/nfsinstance/client/filestoreClient.go
  pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance.go
  pkg/skr/backupschedule/loadBackups.go
  pkg/skr/backupschedule/loadSource.go
  pkg/skr/backupschedule/validateSchedule.go
  pkg/skr/gcpnfsvolumebackup/checkBackupOperation.go
  pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
  pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
  pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
Labels: size/M, lgtm, cla: yes

#1007 feat(AwsVpcPeering): remote route table update strategy
  api/cloud-control/v1beta1/vpcpeering_builder.go
  api/cloud-control/v1beta1/vpcpeering_types.go
  api/cloud-resources/v1beta1/awsvpcpeering_types.go
  config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-control/vpcpeering_aws_test.go
  pkg/kcp/provider/aws/meta/metadata.go
  pkg/kcp/provider/aws/mock/routeTablesStore.go
  pkg/kcp/provider/aws/util/peering.go
  pkg/kcp/provider/aws/util/peering_test.go
  pkg/kcp/provider/aws/vpcpeering/createRemoteRoutes.go
  pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
  pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
  pkg/kcp/provider/aws/vpcpeering/remoteRoutesDelete.go
  pkg/skr/awsvpcpeering/createKcpVpcPeering.go
  pkg/testinfra/dsl/vpcPeering.go
Labels: size/XL, lgtm, cla: yes

#1026 docs: Update main README and tutorials
  README.md
  docs/user/_sidebar.md
  docs/user/tutorials/01-20-10-aws-nfs-volume.md
  docs/user/tutorials/01-20-11-aws-nfs-volume-backup.md
  docs/user/tutorials/01-20-12-aws-scheduled-nfs-backup.md
  docs/user/tutorials/01-20-13-aws-nfs-volume-restore.md
  docs/user/tutorials/01-20-20-gcp-nfs-volume.md
  docs/user/tutorials/01-20-21-gcp-nfs-volume-backup.md
  docs/user/tutorials/01-20-22-gcp-scheduled-nfs-backup.md
  docs/user/tutorials/01-20-23-gcp-nfs-volume-restore.md
  docs/user/tutorials/README.md
Labels: documentation, area/documentation, size/M, lgtm, cla: yes

#1027 chore: golang version upgrade 1.23 -> 1.23.6
  Dockerfile
  go.mod
Labels: size/XS, lgtm, cla: yes

#1009 feat: Cceenfsvolume
  api/cloud-resources/v1beta1/cceenfsvolume_types.go
  config/crd/bases/cloud-resources.kyma-project.io_cceenfsvolumes.yaml
  internal/controller/cloud-resources/awsnfsvolume_test.go
  internal/controller/cloud-resources/cceenfsvolume_controller_test.go
  internal/controller/cloud-resources/suite_test.go
  pkg/composed/conditionFilter.go
  pkg/composed/conditions.go
  pkg/composed/state.go
  pkg/composed/updateStatus.go
  pkg/migrateFinalizers/migration.go
  pkg/skr/cceenfsvolume/idGenerate.go
  pkg/skr/cceenfsvolume/kcpNfsInstanceCreate.go
  pkg/skr/cceenfsvolume/kcpNfsInstanceDelete.go
  pkg/skr/cceenfsvolume/kcpNfsInstanceLoad.go
  pkg/skr/cceenfsvolume/kcpNfsInstanceWaitDeleted.go
  pkg/skr/cceenfsvolume/pv_create.go
  pkg/skr/cceenfsvolume/pv_delete.go
  pkg/skr/cceenfsvolume/pv_load.go
  pkg/skr/cceenfsvolume/pv_removeClaimRef.go
  pkg/skr/cceenfsvolume/pv_removeFinalizer.go
  pkg/skr/cceenfsvolume/pv_validate.go
  pkg/skr/cceenfsvolume/pv_waitDeleted.go
  pkg/skr/cceenfsvolume/pvc_create.go
  pkg/skr/cceenfsvolume/pvc_delete.go
  pkg/skr/cceenfsvolume/pvc_load.go
  pkg/skr/cceenfsvolume/pvc_removeFinalizer.go
  pkg/skr/cceenfsvolume/pvc_validate.go
  pkg/skr/cceenfsvolume/pvc_waitDeleted.go
  pkg/skr/cceenfsvolume/reconciler.go
  pkg/skr/cceenfsvolume/statusCopy.go
  pkg/skr/cceenfsvolume/stopIfNotBeingDeleted.go
  pkg/skr/cceenfsvolume/updateSize.go
  pkg/skr/cceenfsvolume/waitKcpNfsInstanceStatus.go
  pkg/testinfra/dsl/cceeNfsVolume.go
  pkg/testinfra/dsl/nfsInstance.go
Labels: size/XXL, lgtm, cla: yes

#1025 chore(VpcPeering): log status.id
  pkg/skr/awsvpcpeering/createKcpVpcPeering.go
  pkg/skr/azurevpcpeering/createKpcVpcPeering.go
  pkg/skr/gcpvpcpeering/createKcpVpcPeering.go
Labels: size/XS, cla: yes

#1036 chore(AwsRedisInstance): add shardcount to client
  pkg/kcp/provider/aws/client/elastiCacheClient.go
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
Labels: size/S, lgtm, cla: yes

#1035 fix(NfsVolumeBackup): Short circuit reconciliation loop if completed
  api/cloud-resources/v1beta1/condition.go
  api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
  api/cloud-resources/v1beta1/state.go
  pkg/skr/awsnfsvolumebackup/markFailed.go
  pkg/skr/awsnfsvolumebackup/markFailed_test.go
  pkg/skr/awsnfsvolumebackup/reconciler.go
  pkg/skr/awsnfsvolumebackup/shortCircuit.go
  pkg/skr/awsnfsvolumebackup/shortCircuit_test.go
  pkg/skr/awsnfsvolumebackup/state_test.go
  pkg/skr/gcpnfsvolumebackup/markFailed.go
  pkg/skr/gcpnfsvolumebackup/markFailed_test.go
  pkg/skr/gcpnfsvolumebackup/reconciler.go
  pkg/skr/gcpnfsvolumebackup/shortCircuit.go
  pkg/skr/gcpnfsvolumebackup/shortCircuit_test.go
Labels: size/XXL, lgtm, cla: yes

#1038 docs: Sync OS docu with Help Portal docu
  docs/user/00-20-nfs.md
  docs/user/00-30-vpc-peering.md
  docs/user/00-40-redis.md
  docs/user/00-50-vpc-peering-authorization.md
  docs/user/README.md
  docs/user/resources/README.md
Labels: documentation, size/L, lgtm, cla: yes

#1037 feat(cloud-control): add aws implementation for redis cluster
  api/cloud-control/v1beta1/rediscluster_types.go
  api/cloud-control/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-control.kyma-project.io_redisclusters.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisclusters.yaml
  config/samples/cloud-control_v1beta1_rediscluster.yaml
  internal/controller/cloud-control/rediscluster_aws_test.go
  internal/controller/cloud-control/rediscluster_controller.go
  internal/controller/cloud-control/suite_test.go
  pkg/kcp/provider/aws/client/elastiCacheClient.go
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/rediscluster/addUpdatingCondition.go
  pkg/kcp/provider/aws/rediscluster/authorizeSecurityGroupIngress.go
  pkg/kcp/provider/aws/rediscluster/createAuthTokenSecret.go
  pkg/kcp/provider/aws/rediscluster/createElastiCacheCluster.go
  pkg/kcp/provider/aws/rediscluster/createParameterGroup.go
  pkg/kcp/provider/aws/rediscluster/createSecurityGroup.go
  pkg/kcp/provider/aws/rediscluster/createSubnetGroup.go
  pkg/kcp/provider/aws/rediscluster/createUserGroup.go
  pkg/kcp/provider/aws/rediscluster/deleteAuthTokenSecret.go
  pkg/kcp/provider/aws/rediscluster/deleteElastiCacheCluster.go
  pkg/kcp/provider/aws/rediscluster/deleteParameterGroup.go
  pkg/kcp/provider/aws/rediscluster/deleteSecurityGroup.go
  pkg/kcp/provider/aws/rediscluster/deleteSubnetGroup.go
  pkg/kcp/provider/aws/rediscluster/deleteUserGroup.go
  pkg/kcp/provider/aws/rediscluster/findSecurityGroup.go
  pkg/kcp/provider/aws/rediscluster/loadAuthTokenSecret.go
  pkg/kcp/provider/aws/rediscluster/loadElastiCacheCluster.go
  pkg/kcp/provider/aws/rediscluster/loadMemberClusters.go
  pkg/kcp/provider/aws/rediscluster/loadParameterGroup.go
  pkg/kcp/provider/aws/rediscluster/loadParameterGroupCurrentParams.go
  pkg/kcp/provider/aws/rediscluster/loadParameterGroupFamilyDefaultParams.go
  pkg/kcp/provider/aws/rediscluster/loadSecurityGroup.go
  pkg/kcp/provider/aws/rediscluster/loadSubnetGroup.go
  pkg/kcp/provider/aws/rediscluster/loadUserGroup.go
  pkg/kcp/provider/aws/rediscluster/modifyAuthEnabled.go
  pkg/kcp/provider/aws/rediscluster/modifyAutoMinorVersionUpgrade.go
  pkg/kcp/provider/aws/rediscluster/modifyCacheNodeType.go
  pkg/kcp/provider/aws/rediscluster/modifyParameterGroup.go
  pkg/kcp/provider/aws/rediscluster/modifyPreferredMaintenanceWindow.go
  pkg/kcp/provider/aws/rediscluster/new.go
  pkg/kcp/provider/aws/rediscluster/predicates.go
  pkg/kcp/provider/aws/rediscluster/removeReadyCondition.go
  pkg/kcp/provider/aws/rediscluster/state.go
  pkg/kcp/provider/aws/rediscluster/updateElastiCacheCluster.go
  pkg/kcp/provider/aws/rediscluster/updateStatus.go
  pkg/kcp/provider/aws/rediscluster/updateStatusId.go
  pkg/kcp/provider/aws/rediscluster/util.go
  pkg/kcp/provider/aws/rediscluster/util_test.go
  pkg/kcp/provider/aws/rediscluster/waitElastiCacheAvailable.go
  pkg/kcp/provider/aws/rediscluster/waitElastiCacheDeleted.go
  pkg/kcp/provider/aws/rediscluster/waitUserGroupActive.go
  pkg/kcp/provider/aws/rediscluster/waitUserGroupDeleted.go
  pkg/testinfra/dsl/commonAssertions.go
  pkg/testinfra/dsl/commonIpRange.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/XXL, lgtm, cla: yes

#1039 feat: AzureRwxVolumeBackup CRD
  PROJECT
  api/cloud-resources/v1beta1/azurerwxvolumebackup_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_azurerwxvolumebackups.yaml
  config/crd/kustomization.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxvolumebackups.yaml
  config/patchAfterMakeManifests.sh
  config/rbac/cloud-resources_azurerwxvolumebackup_editor_role.yaml
  config/rbac/cloud-resources_azurerwxvolumebackup_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_azurerwxvolumebackup.yaml
  config/samples/kustomization.yaml
  config/sync.sh
  internal/controller/cloud-resources/azurerwxvolumebackup_controller.go
  internal/controller/cloud-resources/azurerwxvolumebackup_controller_test.go
  pkg/skr/azurerwxvolumebackup/reconciler.go
  pkg/skr/azurerwxvolumebackup/state.go
Labels: size/XL, cla: yes

#1048 feat: AzureRwxVolumeRestore CRD
  PROJECT
  api/cloud-resources/v1beta1/azurerwxvolumerestore_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_azurerwxvolumerestores.yaml
  config/crd/kustomization.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxvolumerestores.yaml
  config/patchAfterMakeManifests.sh
  config/rbac/cloud-resources_azurerwxvolumerestore_editor_role.yaml
  config/rbac/cloud-resources_azurerwxvolumerestore_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_azurerwxvolumerestore.yaml
  config/samples/kustomization.yaml
  config/sync.sh
  internal/controller/cloud-resources/azurerwxvolumerestore_controller.go
  internal/controller/cloud-resources/azurerwxvolumerestore_controller_test.go
  pkg/skr/azurerwxvolumerestore/reconciler.go
  pkg/skr/azurerwxvolumerestore/state.go
Labels: size/XL, lgtm, cla: yes

#1047 feat: AzureRwxBackup Clients
  cmd/main.go
  go.mod
  go.sum
  internal/controller/cloud-resources/azurerwxvolumebackup_controller.go
  pkg/skr/azurerwxvolumebackup/client/backup.go
  pkg/skr/azurerwxvolumebackup/client/client.go
  pkg/skr/azurerwxvolumebackup/client/protectionPolicies.go
  pkg/skr/azurerwxvolumebackup/client/recoveryPoint.go
  pkg/skr/azurerwxvolumebackup/client/vault.go
Labels: size/L, cla: yes

#1041 chore(BackupSchedule): enhancement for MaxRetentionDays, MaxBackups
  api/cloud-resources/v1beta1/awsnfsbackupschedule_types.go
  api/cloud-resources/v1beta1/gcpnfsbackupschedule_types.go
  api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
  config/crd/bases/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
  config/crd/bases/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/patchAfterMakeManifests.sh
  config/ui-extensions/awsnfsbackupschedules/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
  config/ui-extensions/awsnfsbackupschedules/details
  config/ui-extensions/awsnfsbackupschedules/form
  config/ui-extensions/awsnfsbackupschedules/translations
  config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/gcpnfsbackupschedules/details
  config/ui-extensions/gcpnfsbackupschedules/form
  config/ui-extensions/gcpnfsbackupschedules/translations
  pkg/skr/backupschedule/backupschedule.go
  pkg/skr/backupschedule/deleteBackups.go
  pkg/skr/backupschedule/deleteBackups_test.go
  pkg/skr/backupschedule/loadBackups.go
Labels: size/L, lgtm, cla: yes

#1050 fix(BackupSchedule): Incremented UI ConfigMap version
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
  config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/awsnfsbackupschedules/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
  config/ui-extensions/awsnfsbackupschedules/kustomization.yaml
  config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
  config/ui-extensions/gcpnfsbackupschedules/kustomization.yaml
Labels: size/S, lgtm, cla: yes

#1040 docs: Add Azure limitation for VPC peering
  docs/user/00-30-vpc-peering.md
Labels: size/XS, lgtm, cla: yes

#1046 feat(AzureRedis) - allow standard tier - kcp piece
  api/cloud-control/v1beta1/redisinstance_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
  internal/controller/cloud-control/nuke_controller_test.go
  internal/controller/cloud-control/redisinstance_azure_test.go
  pkg/kcp/provider/azure/redisinstance/createRedis.go
  pkg/kcp/provider/azure/redisinstance/modifyRedis.go
  pkg/testinfra/dsl/redisInstance.go
Labels: size/M, lgtm, cla: yes

#1053 feat: Azure Client Implementation
  pkg/skr/azurerwxvolumebackup/client/protectionPolicies.go
  pkg/skr/azurerwxvolumebackup/client/recoveryPoint.go
  pkg/skr/azurerwxvolumebackup/client/vault.go
Labels: size/L, cla: yes

#1052 feat(RedisCluster): make aws redis cluster shard and replica scalable
  api/cloud-control/v1beta1/rediscluster_types.go
  config/crd/bases/cloud-control.kyma-project.io_redisclusters.yaml
  config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisclusters.yaml
  config/samples/cloud-control_v1beta1_rediscluster.yaml
  docs/contributor/aws-permissions.md
  pkg/kcp/provider/aws/client/elastiCacheClient.go
  pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
  pkg/kcp/provider/aws/rediscluster/new.go
  pkg/kcp/provider/aws/rediscluster/scaleElastiCacheClusterReplicas.go
  pkg/kcp/provider/aws/rediscluster/scaleElastiCacheClusterShards.go
  pkg/kcp/provider/aws/rediscluster/state.go
Labels: size/L, lgtm, cla: yes

#1056 feat: AzureRwxBackupSchedule CRD
  PROJECT
  api/cloud-resources/v1beta1/azurerwxbackupschedule_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_azurerwxbackupschedules.yaml
  config/crd/kustomization.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxbackupschedules.yaml
  config/patchAfterMakeManifests.sh
  config/rbac/cloud-resources_azurerwxbackupschedule_editor_role.yaml
  config/rbac/cloud-resources_azurerwxbackupschedule_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_azurerwxbackupschedule.yaml
  config/samples/kustomization.yaml
  config/sync.sh
  internal/controller/cloud-resources/azurerwxbackupschedule_controller.go
Labels: size/XXL, lgtm, cla: yes

#1058 feat(AwsRedisCluster): generate api and add boilerplate
  PROJECT
  api/cloud-resources/v1beta1/awsrediscluster_types.go
  api/cloud-resources/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/cloud-resources.kyma-project.io_awsredisclusters.yaml
  config/crd/kustomization.yaml
  config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisclusters.yaml
  config/patchAfterMakeManifests.sh
  config/rbac/cloud-resources_awsrediscluster_editor_role.yaml
  config/rbac/cloud-resources_awsrediscluster_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/samples/cloud-resources_v1beta1_awsrediscluster.yaml
  config/samples/kustomization.yaml
  config/sync.sh
  internal/controller/cloud-resources/awsrediscluster_controller.go
  internal/controller/cloud-resources/suite_test.go
  pkg/feature/types/types.go
  pkg/skr/awsrediscluster/reconciler.go
  pkg/skr/awsrediscluster/state.go
Labels: size/XL, cla: yes

#1057 feat(AzureRedis): auzre redis basic tier - skr piece
  api/cloud-resources/v1beta1/azureredisinstance_types.go
  config/crd/bases/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances.yaml
  config/patchAfterMakeManifests.sh
  internal/controller/cloud-resources/azureredisinstance_test.go
  pkg/skr/azureredisinstance/createKcpRedisInstance.go
  pkg/skr/azureredisinstance/modifyKcpRedisInstance.go
  pkg/skr/azureredisinstance/util.go
Labels: size/M, lgtm, cla: yes

#1055 doc(NfsBackupSchedule): Documentation update - new schedule attributes
  docs/user/00-25-scheduling-best-practices.md
  docs/user/resources/04-20-12-aws-nfs-backup-schedule.md
  docs/user/resources/04-20-22-gcp-nfs-backup-schedule.md
  docs/user/tutorials/01-20-12-aws-scheduled-nfs-backup.md
  docs/user/tutorials/01-20-22-gcp-scheduled-nfs-backup.md
Labels: size/M, lgtm, cla: yes
